### ISSUE TITLE
MYSQL error

### ISSUE THREAD

**Issue by kidsonk** [Open-Web-Analytics/Open-Web-Analytics#11]
Not sure if this is really a support forum - looks more like development.. 
Sorry if it is development, but I am stuck and can not find anywhere else to post questions.

I am getting MYSQL errors on new windows installation using MYSQL Windows and webserver is IIS7
OWA version 1.5.7 

Incorrect integer value: '' for column 'is_new_visitor'
Incorrect integer value: '' for column 'handled_timestamp'

Any idea why I would be passing blank values ?

**Comment by doom99** [comment]
Hey guys - maybe I missed this on the OWA website but if its not on there, could you PLEASE put it on the wiki?  I just wasted a couple hours on this.  Sadly will probably move on at least until this is fixed in the code as I don't think its appropriate to reduce mysql security.

**Comment by padams** [comment]
Done. thanks. It is possible turn off strict mode for just the OWA tables. I'm going to leave this open as a bug as I'd like to get it fixed.

**Comment by Maaiins** [comment]
> Done. thanks. It is possible turn off strict mode for just the OWA tables. I'm going to leave this open as a bug as I'd like to get it fixed.

@padams You can only turn off the strict mode for the current session. Adding the sql command to the connection logic would be the solution.

**Comment by Maaiins** [comment]
Is this already implemented? See `owa_db_mysql.php` lie 131
```
// turn off strict mode. needed on mysql 5.7 and lter when it is turned on by default.
$this->query( "SET SESSION sql_mode=''" );
```

**Comment by padams** [comment]
It looks that way. But people still seem to be reporting the issue. Not sure why.

It would be good to fix this the right way at some point. 

Maybe we open an issue ticket for supporting strict mode which would require null setting for empty values on INSERT or UPDATE statements.

**Comment by padams** [comment]
Although maybe that report was from before I implemented that fix...

**Comment by Maaiins** [comment]
I think the command is wrong. `SET SESSION sql_mode = 'NO_ENGINE_SUBSTITUTION';` should be right. See: https://www.linode.com/community/questions/17070/how-can-i-disable-mysql-strict-mode

**Comment by Maaiins** [comment]
@padams fixed in master can be closed

**Comment by padams** [comment]
ok.
