### ISSUE TITLE
Referral Page Title not set

### ISSUE THREAD

**Issue by adilreh** [Open-Web-Analytics/Open-Web-Analytics#177]
I am getting the referral page title as not set all other things seem to work well is their anything I need to do. In general configuration I have set Fetch Referring Web Page Info as on. Please help.

**Comment by dac2020** [comment]
Again, I see this is an old issue but in version 1.6.0, I am seeing the same thing. 
When I click on 'not set', then it shows me the referring site.
The only links which do show are if they are the local web site itself. None else show. 
Not sure what to include for information about this. I've searched the net but cannot find much about this.

**Comment by ketodiet** [comment]
Same issue for me - this is a great project and if devs accept donations I’ll be happy to donate for a fix :) thank you

**Comment by Maaiins** [comment]
@padams issue can be closed, fix is contained in master and 1.6.6 release
