### ISSUE TITLE
Remove user from Allowed Users

### ISSUE THREAD

**Issue by Toretu** [Open-Web-Analytics/Open-Web-Analytics#233]
In the Edit Site Profile for <url>
There is a allowed users field at the bottom, but no way to remove users or add if possible...
I need to remove a user and can not. (have tried to press delete button on keyboard and similar...
![owa](https://cloud.githubusercontent.com/assets/25929492/23167435/94a8467a-f844-11e6-9df4-8b968db19f87.PNG)

**Comment by Maaiins** [comment]
You can´t remove users in this screen.To remove users you have to open "User Management" and delete the user there.

Adding or removing user permission for sites works fine in Version 1.6.6

@padams can be closed
