### ISSUE TITLE
Error in the funnel reports

### ISSUE THREAD

**Issue by RodolfoPichardo** [Open-Web-Analytics/Open-Web-Analytics#259]
Using the most recent code (master), the following PHP errors appear when accessing the funnel reports:

```
Notice: Undefined offset: 0 in /{OWA_DIR}/modules/base/reportGoalFunnel.php on line 98
Notice: Undefined offset: 0 in /{OWA_DIR}/modules/base/reportGoalFunnel.php on line 99
```

Also the images don't appear in those reports.

**Comment by Maaiins** [comment]
@padams Could not reproduce in Version 1.6.6. Looks like an incomplete installation.

**Comment by padams** [comment]
me neither. Closing.
