### ISSUE TITLE
List of Metrics and dimensions in Data access APIs

### ISSUE THREAD

**Issue by Mohanvenkatesan** [Open-Web-Analytics/Open-Web-Analytics#268]
From Documentation, I got the list of supported metrics are: visitDuration,bounces,repeatVisitors,newVisitors,visits,pageViews and the list of supported dimensions are date,browserType.

Pls let me know the list of supported metrics and dimensions other than the above list

**Comment by JingleSPOT** [comment]
Aloha

Did you solve this?

**Comment by elena139** [comment]
I also have issues with this, I would like to add hour or timestamp and then PagePath, PriorPagePath, NextPagePath, PageTitle. The link of the list of supported metrics and dimensions is not valid. Where the whole list can be found plus can I add these metrics?

**Comment by padams** [comment]
Here it is: https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Metrics-&-Dimensions
