### ISSUE TITLE
About goal setting and visit length

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [Open-Web-Analytics/Open-Web-Analytics#269]
1. How do I set goals via javascript as in piwiks `_paq.push(['trackGoal', 1]); `?
2. A lot of my visitors have a `Visit Length` of `0:00:00`. What does that mean?
3. How do I sort by `Visit Length` or limit results with a `Visit Length` of at least 8 seconds?

**Comment by ErfolgreichCharismatisch** [comment]
Don't everybody speak up at once!

**Comment by JingleSPOT** [comment]
Aloha,
I'm new here, but wondering if you solved this problem?
Had trouble with Piwik, so testing this software.

**Comment by padams** [comment]
Goals are set via the admin interface not via JavaScript at this time.

See the Metrics and dimension page of the wiki to understand how visit duration is calculated.

You can do complex filters via the API not via the dashboard yet.
