### ISSUE TITLE
Strict Standards: Non-static method owa_sanitize::cleanInput()

### ISSUE THREAD

**Issue by dev-101** [Open-Web-Analytics/Open-Web-Analytics#29]
Hi,

I have enabled strict PHP error reporting in my local dev environment. and I see this in my logs:

`Strict Standards: Non-static method owa_sanitize::cleanInput() should not be called statically in \owa\modules\base\classes\sanitize.php on line 329`

PHP version 5.4.16

Regards

**Comment by RambirSingh** [comment]
I changed the function to "public static" as described but the problem is still same.

Strict Standards: Non-static method owa_sanitize::cleanInput() should not be called statically in /home/......../public_html/owa/modules/base/classes/sanitize.php on line 329

What should i do now
