### ISSUE TITLE
Page titles not being escaped correctly

### ISSUE THREAD

**Issue by LargeGoose** [Open-Web-Analytics/Open-Web-Analytics#294]
I've just upgrade to 1.6.0 and have noticed that the top entry in the latest vsits section of the dashboard has not correctly escaped the page name. Bizarrely the entries below which are the same page name are correctly escaped.

![image](https://user-images.githubusercontent.com/10414231/34264903-41f6b896-e66c-11e7-9c27-adb0efce5fc4.png)

**Comment by LargeGoose** [comment]
Looking at the pages in the DB means I think it must have been before the upgrade. I have just created another site that has a ' in the page title and that also hasn't been unescaped correctly.

**Comment by Maaiins** [comment]
@padams should also be fixed by #459
