### ISSUE TITLE
Domstream and window size 

### ISSUE THREAD

**Issue by likeleto** [Open-Web-Analytics/Open-Web-Analytics#301]
It seems that domstream tracker does not consider page width and height for recordings and heatmap analysis. Without it recording cursor position does not equal to visitor actual cursor position. Cheap solution for it - put page size data to domstream table, and then open player in iframe with these page width and height.

**Comment by padams** [comment]
Agreed would be a nice enhancement.

**Comment by Maaiins** [comment]
I've got some smart suggestion, simply take a screenshot of the site and save them. Why? Domstream got some trouble with privacy popups and so on. You will never have the same screen the user has. Taking a screenshot would solve both problems you've got the right windows size for the movement and the same screen.

See: https://html2canvas.hertzen.com/

**Comment by padams** [comment]
what about recording the browser viewport dimensions and then resizing the window on playback?

**Comment by padams** [comment]
@Maaiins a screen shot won't allow you to manipulate the dom on playback. You would lose scrolling, etc.

**Comment by Maaiins** [comment]
That´s completely true. I came to this idea because initial pop ups eg cookie consent tools will show up on site loading. Sometimes they are hiding elements. Maybe i've got some other idea to solve this in a separate way.
