### ISSUE TITLE
Error giving new user access to specific site

### ISSUE THREAD

**Issue by brianshophero** [Open-Web-Analytics/Open-Web-Analytics#308]
I've created a new user, which I want to only see the analytics on 1 website. I got to that specific site's settings, hilight the new user and hit save users to provide access, but I'm met with an http error 500. Is there another way I can provide a new user access?

![capture](https://user-images.githubusercontent.com/36448320/36156408-2c0cd6b2-1094-11e8-8f01-d8b8cfcafc68.PNG)

**Comment by Maaiins** [comment]
@padams can't reproduce this error. Assigning access permission works fine for me.

**Comment by padams** [comment]
Me too. Closing.
