### ISSUE TITLE
jekyll and github pages integration

### ISSUE THREAD

**Issue by jangorecki** [Open-Web-Analytics/Open-Web-Analytics#31]
is it possible? are there any plans to make it possible?
to use OWA on github pages hosted by [jekyll](https://github.com/jekyll/jekyll).

It may require to setup external host for collecting logs so it might need a little bit more setup than GA.
But still in many use cases it would be a better solution than storing your logs in google when using GA.

**Comment by magwas** [comment]
@jangorecki did you implement it? Could you share how you did it, or point to some documentation from which I could understand the setup needed for that?
