### ISSUE TITLE
Feature request: Show views on the 'Page Detail' page

### ISSUE THREAD

**Issue by Joshfindit** [Open-Web-Analytics/Open-Web-Analytics#335]
Allow seeing who visited the page and when (Not just recent visits, but all for the given time-range)

**Comment by stackprogramer** [comment]
yeah i had same problem in firefox.chrome  in windows,linux
snap shot from owa http://www.mediafire.com/file/23mz1xrn22jvjzj/owa_error.png

**Comment by Joshfindit** [comment]
(To be clear: This is a feature request, not a bug report. OWA Nightly is working properly in my case, but the "Page Detail" page simply does not show who visited or when.)
