### ISSUE TITLE
Recurring requests log.php and blank.php

### ISSUE THREAD

**Issue by mycastle** [Open-Web-Analytics/Open-Web-Analytics#34]
Hi,
I'm using OWA on a static HTML page. There are continuous requests to log.php (POST) and blank.php (GET). It seems those requests are triggered when hovering a hyperlink (e.g. in the menu) after a certain time interval. I couldn't find any documentation on what those requests do exactly and how I could possibly avoid the requests at all. Hope for your help though.

Thanks,
maria

**Comment by hirako2000** [comment]
Any reason this issue was closed ? The requests could be made asynchronous, if not domstream tracking is negatively affecting the end user experience.
