### ISSUE TITLE
How to Set MySQL Port Options?

### ISSUE THREAD

**Issue by elrok123** [Open-Web-Analytics/Open-Web-Analytics#364]
I don't know if I'm being stupid. But I swear there doesn't seem to be any way of setting the port for MySQL on Open Web Analytics (at least not without having a proper inspection under the hood, but even then it still looked like it was just assuming the default port). 

This could be problematic for some people using MySQL on non-default ports. Apologies if I've totally missed the options, but I've had a look through the MySQL options in the installation guide and looked around in the code base where it sets up the MySQL connection.

**Comment by padams** [comment]
very true. happy to look at a patch/PR if you have one.

**Comment by gili77** [comment]
I run into same problem, had to replace the port to able to use database cluster...
Anyway, my solution was following the error and edit the connect function "mysqli_connect".
Edit the file "plugins/db/owa_db_mysql.php" at line 107
change this:
			$this->connection = mysqli_connect(
				$host,
				$this->getConnectionParam('user'),
				$this->getConnectionParam('password'),
				$this->getConnectionParam('name')
	    	);

into this:
			$this->connection = mysqli_connect(
				$host,
				$this->getConnectionParam('user'),
				$this->getConnectionParam('password'),
				$this->getConnectionParam('name'),
				'3307'
	    	);
Note that if you use "mysql_connect" function the solution will be to edit the function 
at the file "includes/pqp/classes/MySqlDatabase.php".

**Comment by Maaiins** [comment]
See #500 added in master. Feel free to reopen if there is still any problem
