### ISSUE TITLE
UTF-8 support not available, like characters in swedish

### ISSUE THREAD

**Issue by manojmohal-nsv** [Open-Web-Analytics/Open-Web-Analytics#408]
I was trying the OWA on swedish website where I had to add "custom variable", "user_name" and "user_email" but instead of saving swedish character, it converts it to some html code or ASCII code

**Comment by Maaiins** [comment]
@padams should be fixed by #459

**Comment by Maaiins** [comment]
@manojmohal-nsv Can you update to the new version and give us some feedback?

**Comment by Maaiins** [comment]
Should be fixed by #459. Feel free to reopen if there is still a problem
