### ISSUE TITLE
"Deprecated ..." message in PHP 7.3, file owa_lib.php

### ISSUE THREAD

**Issue by gioalhaz** [Open-Web-Analytics/Open-Web-Analytics#414]
In file owa_lib.php on line 476 (function fileInclusionFilter) there is deprecated code 
if (strpos($str, null))

According to PHP doc: "Passing a non-string needle to string search functions is deprecated. In the future the needle will be interpreted as a string instead of an ASCII codepoint. Depending on the intended behavior, you should either explicitly cast the needle to string or perform an explicit call to chr(). "

So null in strpos should be changed.

**Comment by Sweepr** [comment]
PHP Deprecated: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /home/public_html/owa/owa_lib.php on line 476

Same here, still no patch?

**Comment by Maaiins** [comment]
@padams issue can be closed, fix is contained in master and 1.6.6 release

**Comment by padams** [comment]
is this one fixed? i don't see a change for the error he's reporting with strpos. or am i missing it?

**Comment by Maaiins** [comment]
I think i fixed this. Let me check this first

**Comment by Maaiins** [comment]
![image](https://user-images.githubusercontent.com/7676540/77467346-21907680-6e0c-11ea-8d70-d95e9c1b617a.png)

**Comment by padams** [comment]
ah. i was looking at he wrong line. thanks. closing.
