### ISSUE TITLE
Unavailable features should be ... well, unavailable

### ISSUE THREAD

**Issue by joho1968** [Open-Web-Analytics/Open-Web-Analytics#416]
Having created a few users with different privilege levels, it would be nice if OWA would hide functionality that isn't available to the privilege level of the currently logged in user.

For example, under "Reporting" (Sites Roster), there's an "Add new" link which doesn't work for a user that only has "View" privileges, nor does the "Goals" and "Delete" links.

The "Administration" button at the top of the page is another "unreachable" option.

**Comment by padams** [comment]
There is a facility for this in templates. 

`<?php if ($this->getCurrentUser()->isCapable(‘some_priviledge’, $currentSiteId ) ) { ... } ?>`

**Comment by Maaiins** [comment]
@padams issue can be closed, fix is contained in master and 1.6.6 release
