### ISSUE TITLE
Referrers Assumption: https referrers doc titles get not resolved 

### ISSUE THREAD

**Issue by znrR** [Open-Web-Analytics/Open-Web-Analytics#443]
Hi Peter,

in the referrers section i see page titles with (not set) as well some which are set:
<img width="175" alt="Screenshot 2020-01-10 at 22 01 30" src="https://user-images.githubusercontent.com/59607366/72187206-50937080-33f7-11ea-8965-0947ffffd768.png">
I had a look in the logfiles and there they look pretty much the same:

`"GET / HTTP/1.1" 200 361977 "http://radreisender.de/ausruestung/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71"`

`"GET / HTTP/1.1" 200 361977 "https://www.facebook.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0"`

but they differ in http protocol, maybe OWA can't resolve doctitles for https sites? i also tested, some of the (not set) referrers are 301 redirects but eg: https://de-de.facebook.com/ is not,  provides a doctitle and shows also (not set) in the stats UI. 

<img width="355" alt="Screenshot 2020-01-10 at 22 16 50" src="https://user-images.githubusercontent.com/59607366/72187205-4ffada00-33f7-11ea-989f-2fc2878d02d1.png">

It would be really good to see referrers with their doctitle to better see from where users are coming from (ok, i can click all the "not sets" but its hard to get an overview this way ;-)

Thanks for your help, Stefan

**Comment by padams** [comment]
Can you put OWA into debug mode and try navigating to your site from that referer? If so then look for ""referer title extract: " in the log files and post that line.

**Comment by Maaiins** [comment]
@padams issue can be closed, fix is contained in master and 1.6.6 release

**Comment by znrR** [comment]
Hi @Maaiins and @padams - wow seeing so many new fixes, really great thanks! In order to see the doc-titles fix in the web-ui taking effect, i guess i need to delete DB rows, correct? can you point me to the right spot? i found referer_id in the table structure but no place where i could edit / delete those?

**Comment by znrR** [comment]
oh wow - just discovered the new setting "Fetch Referring Web Page Info
Controls whether OWA should crawl the web pages that refer visitors to your web site and extract descriptive meta-data that will be used in reporting." :-) :-) maybe i just need to wait for OWA to crawl the referers.. oh my you guys.. so good!!

**Comment by padams** [comment]
Sadly no. OWA will not update the referrer in the DB if it's already there. I'm working on a way to control this behavior but it's a little ways out. You could delete the offending row in owa_referer but then joins will fails in reporting. 

Hold tight and I'll see if I can put the feature out that will allow you tell OWA to update old referers on some interval.

**Comment by znrR** [comment]
okidoki will hang tight for interval updates, thanks!!

**Comment by Maaiins** [comment]
> Sadly no. OWA will not update the referrer in the DB if it's already there. I'm working on a way to control this behavior but it's a little ways out. You could delete the offending row in owa_referer but then joins will fails in reporting.
> 
> Hold tight and I'll see if I can put the feature out that will allow you tell OWA to update old referers on some interval.

We could make an update routine which simply crawls all referer and update the doc titles. Shouldn't be that complicated, the logic is already there. So just get all results out of the database and put each one into the crawling logic.

**Comment by padams** [comment]
This might be a good CLI command. Maybe also add the ability to just crawl a single referrer too.

**Comment by znrR** [comment]
I would be happy with a CLI cmnd and I think others too (please also include a short advice on how to execute it). The bug should have not affected to many installs, at least i have not found other reports here regarding the issue. Do you want me to open a separate issue for that or are you fine with the comments on that closed issue? thanks for the support guys!

**Comment by padams** [comment]
Let’s create new tickets. I have the CLI command outlined in #497.

**Comment by Maaiins** [comment]
> Let’s create new tickets. I have the CLI command outlined in #497.

I think thats the wrong issue.
@znrR you can keep track here #502

**Comment by znrR** [comment]
i think that tick can be close, both issues reflected in different tickets now.
