### ISSUE TITLE
Integration with Node App.

### ISSUE THREAD

**Issue by praveen5959** [Open-Web-Analytics/Open-Web-Analytics#445]
Instead of send the log data to say localhost/owa/ is there a way to send it to my node app. So that I can modify the data before storing it to some other DB.

**Comment by Maaiins** [comment]
It sounds like you want to use the tracker javascript for your own analytics platform?

When you just want to copy data to another place e.g. an data mining system. Build a separated db connector for the mysql database. Than you can pull and modify the data by your own
