### ISSUE TITLE
Support for "SameSite" origin changes coming to Chrome 80

### ISSUE THREAD

**Issue by criterion9** [Open-Web-Analytics/Open-Web-Analytics#449]
The cookies dropped by OWA need to set the SameSite attribute to None as well as setting the Secure flag in order to be supported by the imminent version of Chrome that will be released to the greater stable channel. Currently those attributes are not being set on the cookie which will start to fail for those who upgrade to the most current stable Chrome version within a few days.

**Comment by criterion9** [comment]
Some more details... The behavior of open third-party cookies is changing by default in Chrome first but other browsers are following the same path. It may be worth a revisit to how the cookie data is shared with the tracking javascript that is embeded into the pages that will be tracked. Perhaps such as by dropping a cookie in the current domain context and resolving cross domain attributes by connecting the data server-side instead.

To support the "current" releases of browsers where the cookies are expected to be used in a third party context the advice is to use sameSite:none;secure when setting those cookies. This will not work for some older browsers that incorrectly block the cookie from being sent with the request. This adds some complexity that would be required to adjust whether or not to use the updated sameSite:none;secure attributes or not based on the browser client.

https://blog.chromium.org/2019/10/developers-get-ready-for-new.html
https://www.chromium.org/updates/same-site/incompatible-clients
https://github.com/GoogleChromeLabs/samesite-examples/blob/master/javascript.md

**Comment by padams** [comment]
I don't think so... OWA uses first party cookies.

"With Chrome 80 in February, Chrome will treat cookies that have no declared SameSite value as SameSite=Lax cookies."

Am I missing something?

**Comment by criterion9** [comment]
When I use a seperate domain for hosting OWA and embed the javascript tracker I get warnings in developer tools about the cross-origin cookie usage:

![image](https://user-images.githubusercontent.com/23464351/73599446-84067e00-4511-11ea-9dfd-a4b93a62056a.png)

**Comment by padams** [comment]
The javascript file can be loaded from third party site but the tracking cookies are first party. There are also some login cookies for the admin interface where ever you run that. 

Look to see which OWA cookies are not being set under the domain being tracked.

**Comment by criterion9** [comment]
Gotcha! I have not dove into the cookies in OWA as of yet so I wasn't sure. The warnings I'm seeing are really from the admin cookies not having a SameSite attribute set currently as opposed to something that will break with the browser change. 
We can close this issue unless you would want a PR created to add a samesite attribute to those cookies to remove the warning messages. I'm assuming others may start looking at those warnings while they are testing other integrations (like I was) for possible breakages when the change is put in place.

**Comment by padams** [comment]
Let's leave it open for now. thanks!

**Comment by Maaiins** [comment]
See #505 fixed in master. Feel free to reopen if there is still any problem
