### ISSUE TITLE
mediawiki error

### ISSUE THREAD

**Issue by Rik44444** [Open-Web-Analytics/Open-Web-Analytics#460]
hi, is this install guide still actual for Mediawiki? 
https://github.com/padams/Open-Web-Analytics/wiki/Installation#mediawiki-installation
i've just tried installing it following these instructions, but i get a blank page for my whole wiki-repo now.

**Comment by padams** [comment]
Dupe with #455

**Comment by Maaiins** [comment]
I dove into this erros.

there are some easy fixes, but they refactored the complete extension architecture. So the plugin should also refactored.

In my opinion the plugin should moved to another repo and then the files should be added. Adding these json (Required now in mediawiki) files the owa root directory is not really nice.

See: https://www.mediawiki.org/wiki/Manual:Developing_extensions

**Comment by Maaiins** [comment]
Will close this issue, due the plugin will move to: https://github.com/Open-Web-Analytics/owa-mediawiki-extension
