### ISSUE TITLE
Changing password in database

### ISSUE THREAD

**Issue by MaAntonia** [Open-Web-Analytics/Open-Web-Analytics#47]
Hi,

I've created a new user but OWA has not sent the password to the user.
The new user has tried to reset the password but OWA has not sent the password to him by email.

So, I want to try changing the password directly in database.

In "owa_user" table:
1. What FUNCTION I should use in PASSWORD? I've tried MD5 but it has not worked.
2. Should I change TEMP_PASSKEY value? Which FUNCTION and VALUE?
3. Should I change API_KEY value? Which FUNCTION and VALUE?

Thank you for your support.

M.A.

**Comment by orangecoloured** [comment]
I'm having the same issue.

**Comment by padams** [comment]
This really needs to be a CLI command. marking for enhancement.

**Comment by websoul67** [comment]
I am having the same problem , Any resolution yet?

**Comment by adriantan08** [comment]
Is there a way to somehow change the SMTP server? I'm getting the same issue. OWA doesn't seem to be able to send any form of email.

**Comment by PiratesWin** [comment]
Just checking, has this issue been resolved yet?  Still having issues with resetting passwords on version 1.5.7.

**Comment by padams** [comment]
What exactly is the issue? Is your server not configured to send mail?

**Comment by PiratesWin** [comment]
No, the server is not configured to send email.  We have had turnover within out project and the Admin password needs changed.  Is it a requirement to have send mail installed on the server to change the Admin password?

**Comment by CapacitorSet** [comment]
I also had this issue.

At the time of writing, the password hash is calculated as `md5(strtolower($password).strlen($password));` ([reference](https://github.com/padams/Open-Web-Analytics/blob/e69998c5b36539d9d2cbc0f9bfb0ca436c28573f/owa_lib.php#L1003)). This is very insecure, I'll open an issue about that so it might change in the future.

**Comment by richpeck** [comment]
Same issue - no SMTP setup.

**Comment by fangorn9** [comment]
changed /includes/PHPMailer_5.2.0/class.phpmailer.php - set values for
public $From
public $FromName
public $Sender 
public $Subject
public $Port (is not standard 25 for our server)
public $SMTPSecure (set tls for our server)
public $SMTPAuth (set true as our server requests auth)
public $Username
public $Password
...and yes, we know, it´s not safe/updatesafe, but now we get mails...

**Comment by padams** [comment]
The changes to mailer have landed in master but I'm going to keep the open as a reminder that we need a CLI command to change passwords. 

Anyone want to take a crack at this? Just look at one of the cli class like `owa_buildController` for an example.

**Comment by Maaiins** [comment]
@padams issue can be closed, fix is contained in master and 1.6.6 release

**Comment by BloodyIron** [comment]
> I also had this issue.
> 
> At the time of writing, the password hash is calculated as `md5(strtolower($password).strlen($password));` ([reference](https://github.com/padams/Open-Web-Analytics/blob/e69998c5b36539d9d2cbc0f9bfb0ca436c28573f/owa_lib.php#L1003)). This is very insecure, I'll open an issue about that so it might change in the future.

THANK YOU, with this one function alone I was able to somewhat reset the password for a user. I know I'm on an old version (1.6.4, I think) but having to send an E-Mail to reset a password for a user as the only option was really shortsighted.

Anyways thanks for this detail, I'll work towards updating my OWA and hopefully the recovery of passwords will be better in that.
