### ISSUE TITLE
Update UA-parser to latest version

### ISSUE THREAD

**Issue by padams** [Open-Web-Analytics/Open-Web-Analytics#477]
Need to update UA Parser (https://github.com/ua-parser/uap-php) to the latest version. 

Here's the To-do list:

- package up latest version (strip test, docs etc).
- re-integrate into `owa_browscap` wrapper class
- create new CLI method that can update the regex.yaml file. see: https://github.com/ua-parser/uap-php

**Comment by Maaiins** [comment]
Funny that´s what I thought too yesterday. You have to require a lot of files at the moment. Maybe adding composer to the project and require all dependencies via autoload would be a better solution.

**Comment by padams** [comment]
I haven't used composer. Few questions: 

- would it replace owa_env.php? Seems complex to have both.
- doesn't it require the use of namespaces? if so we likely need to start that refactoring too.
- Do you package the autoload.php file with the release?
- How would it work with custom modules that want to include dependancies?

At a minimum, we should probably create another issue to refactor things to use namespaces.

**Comment by Maaiins** [comment]
- As I saw `owa_env.php` only defines constant to require dependencies. Yes it will be replaced.
- I mean it does not require namespaces, but yes this should be refactored too. In my opinion it can be done afterwards.
- Yes, but your git pushes will exclude the vendor directory (There are all dependencies) and include `composer.json` / `composer.lock`. The json will define all dependencies, the lock will include the specific versions. This is necessary when someone is checking out the branch he has to have the same versions as you. After checking out you have to run `composer install`. When you want to update the packages run `composer update` and push the `composer.lock` to update the versions. To publish a release you have to checkout the branch and run `composer install` and `composer dump-autoload --optimize`, afterwards zip the whole directory. Sounds complex but when you know how it works it´s more structured. See: https://getcomposer.org/doc/01-basic-usage.md
- The custom modules are required in the `owa_coreAPI.php` at the moment. Just leaf it as it is or add a custom autoloader, should be no Problem.

That´s correct, when refactoring to use namespaces there are major changes. You have to separate some classes which are now in the same file, the Filename should be the class name and so on (https://github.com/php-fig/fig-standards/tree/master/accepted). As you can see this is quite heavy. I think we should focus now on a well working platform, this means fixing the bugs, updating some dependencies. Your opinion?

**Comment by padams** [comment]
Agreed. Let’s save this for another day. Maybe a v2.0 release.

**Comment by padams** [comment]
OK. i kind of have this working. The big change will be that the master branch is no longer going to be usable without composer installed. I suppose that's the price to pay for progress but it will definitely require some documentation.

I'm going to start using release-x.x.x branches to stage releases. In those release branches we can run `composer install --no-dev --optimize-autoloader --prefer-dist --no-interaction`  and then commit the entire vendor directory. That way we can still use Github releases to package the branch up into a distribution file. (ie. tar/zip).

How's that sounds?

**Comment by Maaiins** [comment]
>  I suppose that's the price to pay for progress but it will definitely require some documentation.
In my opinion nowadays every dev has to know how to install composer. So you only have document the dependencies install command.

You don´t have to push the dependencies, I would do that the following way:
- Making a branch for my release, no pushed dependencies
- Making an Zip file of my local project (Fully working with dependencies)
- Adding an release to github
- Adding the zip as "binary" in the release wizard

**Comment by Maaiins** [comment]
Do you moved all dependencies to composer or only UA-Parser?

**Comment by padams** [comment]
Only UA Parser right now. 

What's the down side of committing the vendor dir to the release branch? 

The upside is that a lot of people use git to checkout code into production. If we didn't run composer.install and commit the vendor dir to the release branch then those release workflows would fail.

**Comment by Maaiins** [comment]
Should we add the other dependencies too and make a 1.6.6 release?

Well it takes much longer to push everything and it´s not best practice, that´s all.

That's a point

**Comment by padams** [comment]
Ok. I'm coming around to your position on it. I just pushed my changes that add Composer support and an updated ua-parser. 

If you want to open some issue tickets for moving other dependencies to composer go ahead. 

I'm going to work on a release script that will package everything up.

**Comment by padams** [comment]
Just went out in 1.6.6. Closing.
