### ISSUE TITLE
Using Github api for news

### ISSUE THREAD

**Issue by Maaiins** [Open-Web-Analytics/Open-Web-Analytics#478]
Instead of using an manually maintained rss feed for the OWA news, use the github api

![image](https://user-images.githubusercontent.com/7676540/76200666-55578380-61f2-11ea-8a5a-a4a5333b744c.png)

You can make a new release in github and it´s automatically updated on the pages.

Example: https://api.github.com/repos/padams/Open-Web-Analytics/releases

There is all you need

**Comment by padams** [comment]
Agreed. that RSS feed and code is crazy old.

**Comment by Maaiins** [comment]
Since the ownership change of the repository api request wont work anymore. I will investigate this further.
