### ISSUE TITLE
track member Open-Web-Analytics

### ISSUE THREAD

**Issue by kom94** [Open-Web-Analytics/Open-Web-Analytics#489]
Hi,

I just install Open-Web-Analytics and shaw it shows when you visit the site with your username (admin) i was hopig i could put in the forum member name to count unique hits based on the login detail. But i can't found anything in the wiki. is there a way to count unique hits based other than ip and can i set some parammeters??

**Comment by Maaiins** [comment]
Yes it´s possible to track members by username or something. You have to set the username. Are you using Javascript or PHP for tracking?

**Comment by kom94** [comment]
I use PHP. After lot of digging i found out you can set the username using the following command:
$owa->setProperty('user_name', $pun_user["username"]);
or
$owa->setProperty('user name', $pun_user["username"]);
i don't know which one is working ;)
i can't found any documentation about setting property's.

**Comment by Maaiins** [comment]
You could just use:` $owa->setUserName($pun_user["username"])`

**Comment by padams** [comment]
Closing. re-open if needed.
