### ISSUE TITLE
Issue in Open Web Analytics version 1.6.6

### ISSUE THREAD

**Issue by GaneshKandu** [Open-Web-Analytics/Open-Web-Analytics#492]
Hi,

1-

I am getting error in Open Web Analytics version 1.6.6 on PHP 5.3.
```
Parse error: syntax error, unexpected '[' in owa_base.php on line 89
```
On this particular line of the code is
```php
"function getMsg($code, $substitutions = []) {".
```
This syntax is supported since PHP 5.4 and is causing error on PHP 5.3.

2-

I tried manual installation of Open Web Analytics version 1.6.6 on PHP 5.4. then i face another issue on PHP 5.5, 5.6.
```
Parse error: syntax error, unexpected 'isSet' (T_ISSET), expecting identifier (T_STRING) in owa_template.php on line 1041
```
Its working on php 7.0

Requirement mentioned here is PHP 5.3  [Technical Requirements](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Technical-Requirements#php) 

Is requirement of Open Web Analytics changed to 7.0 ?

**Comment by padams** [comment]
@Maaiins I think this is from one of your patches. Can you patch using `array()` syntax instead?

**Comment by GaneshKandu** [comment]
What about 2

```
Parse error: syntax error, unexpected 'isSet' (T_ISSET), expecting identifier (T_STRING) in owa_template.php on line 1041
```

**Comment by padams** [comment]
That one is a little trickier... The issue is that  `isSet`  is a reserved name in PHP 5.x but not in PHP 7+. So we need to change that method name to something like `isValueSet` and then modify code wherever it's used.

**Comment by padams** [comment]
I just pushed a commit for the second issue but sadly i attached it ot the wrong issue number!

Here it is https://github.com/Open-Web-Analytics/Open-Web-Analytics/commit/d97b73fbc3dd49e348378082c2f7f140c5720c5e

**Comment by padams** [comment]
Will let @Maaiins patch his code :)

**Comment by Maaiins** [comment]
@padams the shorthand PHP Array Syntax was introduced I think in PHP 5.5 or 5.4.
As you can see here: https://www.php.net/supported-versions.php PHP 5.3 is already out of support.
In my opinion it´s not the correct way to support already end of life versions. This is also an security issue by using old PHP Versions, but if you want to do this I will change it.

Any thoughts? Maybe we should update the technical specs?

**Comment by padams** [comment]
Agreed. Let’s patch this and push out a new release. Then I’ll bump the required php version to 5.6

**Comment by VeeRHunter** [comment]
Oh, I can go to next step, but I am getting this screen.
http://prntscr.com/rncsiv
I didn't have admin account at this moment, what is next step please?

**Comment by Maaiins** [comment]
I will do it tomorow

**Comment by padams** [comment]
Thanks. that convention is also used a lot in the new messages.php.

**Comment by Maaiins** [comment]
I found some problem, the updated dependencies eg. PHPMailer also using the new convention.
I think it´s much easier to bump the needed PHP Version, there shouldn't be that much PHP 5.3 installations out there. As you can see it´s end of life for more than three years now.

Any thoughts?

**Comment by padams** [comment]
Yeah you are right this is a can of worms.
