### ISSUE TITLE
Issue in Open Web Analytics 1.6.2 and 1.6.6

### ISSUE THREAD

**Issue by VeeRHunter** [Open-Web-Analytics/Open-Web-Analytics#494]
I can't set Configuration Settings after tap "Getting Start" button.
In 1.6.2, it always say "Database password is required" even I input database password.
In 1.6.6, it always say "The form that you completed had some errors:".

I am not sure what is error and what is wrong.
Please let me know

**Comment by padams** [comment]
You need to turn on development logging in the config file and then look on OWAs errors log to see what’s happening. Post the relevant debug info here and we can see if it’s a bug.

**Comment by VeeRHunter** [comment]
2020/03/26 16:11:39 [error] 6917#6917: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: page_title in /var/www/html/owa/modules/base/templates/wrapper_default.tpl on line 6" while reading response header from upstream, client: ..., server: example.com, request: "GET /index.php?owa_action=base.updates& HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "...", referrer: "http://.../install.php?owa_action=base.installCheckEnv"

This is error log. Please check and let me know what is wrong :)

**Comment by padams** [comment]
There should be a lot more in owa-data/logs/errors_xxxxxxxxx

**Comment by VeeRHunter** [comment]
20:03:00 2020-03-25 18663 [debug_log] Starting installation of module: base 
20:03:00 2020-03-25 18663 [debug_log] owa_request Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_session Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_document Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_feed_request Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_click Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_ua Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_referer Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_site Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_visitor Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_host Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_exit Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_os Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_impression Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_configuration Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_user Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_domstream Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_action_fact Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_search_term_dim Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_ad_dim Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_source_dim Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_campaign_dim Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_location_dim Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_commerce_transaction_fact Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_commerce_line_item_fact Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_queue_item Table Created. 
20:03:00 2020-03-25 18663 [debug_log] owa_site_user Table Created. 
20:03:00 2020-03-25 18663 [debug_log] Post install proceadure was a success. 
20:03:00 2020-03-25 18663 [debug_log] Module base activated 
20:03:00 2020-03-25 18663 [debug_log] Installation complete. 
20:04:08 2020-03-25 17684 [debug_log] Starting installation of module: base 
20:04:08 2020-03-25 17684 [debug_log] owa_request Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_session Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_document Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_feed_request Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_click Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_ua Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_referer Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_site Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_visitor Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_host Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_exit Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_os Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_impression Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_configuration Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_user Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_domstream Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_action_fact Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_search_term_dim Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_ad_dim Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_source_dim Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_campaign_dim Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_location_dim Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_commerce_transaction_fact Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_commerce_line_item_fact Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_queue_item Table Created. 
20:04:08 2020-03-25 17684 [debug_log] owa_site_user Table Created. 
20:04:08 2020-03-25 17684 [debug_log] Post install proceadure was a success. 
20:04:08 2020-03-25 17684 [debug_log] Module base activated 
20:04:08 2020-03-25 17684 [debug_log] Installation complete. 
20:04:08 2020-03-25 30267 [debug_log] Starting installation of module: base 
20:04:08 2020-03-25 30267 [debug_log] owa_request Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_session Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_document Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_feed_request Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_click Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_ua Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_referer Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_site Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_visitor Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_host Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_exit Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_os Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_impression Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_configuration Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_user Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_domstream Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_action_fact Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_search_term_dim Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_ad_dim Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_source_dim Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_campaign_dim Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_location_dim Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_commerce_transaction_fact Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_commerce_line_item_fact Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_queue_item Table Created. 
20:04:08 2020-03-25 30267 [debug_log] owa_site_user Table Created. 
20:04:08 2020-03-25 30267 [debug_log] Post install proceadure was a success. 
20:04:08 2020-03-25 30267 [debug_log] Module base activated 
20:04:08 2020-03-25 30267 [debug_log] Installation complete. 
20:04:11 2020-03-25 18663 [debug_log] Starting installation of module: base 
20:04:11 2020-03-25 18663 [debug_log] owa_request Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_session Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_document Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_feed_request Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_click Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_ua Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_referer Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_site Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_visitor Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_host Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_exit Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_os Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_impression Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_configuration Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_user Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_domstream Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_action_fact Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_search_term_dim Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_ad_dim Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_source_dim Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_campaign_dim Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_location_dim Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_commerce_transaction_fact Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_commerce_line_item_fact Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_queue_item Table Created. 
20:04:11 2020-03-25 18663 [debug_log] owa_site_user Table Created. 
20:04:11 2020-03-25 18663 [debug_log] Post install proceadure was a success. 
20:04:11 2020-03-25 18663 [debug_log] Module base activated 
20:04:11 2020-03-25 18663 [debug_log] Installation complete. 
20:04:45 2020-03-25 30267 [debug_log] Starting installation of module: base 
20:04:45 2020-03-25 30267 [debug_log] owa_request Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_session Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_document Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_feed_request Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_click Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_ua Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_referer Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_site Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_visitor Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_host Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_exit Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_os Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_impression Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_configuration Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_user Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_domstream Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_action_fact Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_search_term_dim Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_ad_dim Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_source_dim Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_campaign_dim Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_location_dim Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_commerce_transaction_fact Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_commerce_line_item_fact Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_queue_item Table Created. 
20:04:45 2020-03-25 30267 [debug_log] owa_site_user Table Created. 
20:04:45 2020-03-25 30267 [debug_log] Post install proceadure was a success. 
20:04:45 2020-03-25 30267 [debug_log] Module base activated 
20:04:45 2020-03-25 30267 [debug_log] Installation complete. 
20:04:45 2020-03-25 30267 [debug_log] Checking for existence of default site. 
20:04:45 2020-03-25 30267 [debug_log] Created default site. 
20:04:45 2020-03-25 30267 [debug_log] Install Complete Flag added to configuration 
20:16:11 2020-03-25 30267 [debug_log] Starting installation of module: base 
20:16:11 2020-03-25 30267 [debug_log] owa_request Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_session Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_document Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_feed_request Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_click Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_ua Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_referer Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_site Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_visitor Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_host Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_exit Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_os Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_impression Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_configuration Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_user Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_domstream Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_action_fact Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_search_term_dim Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_ad_dim Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_source_dim Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_campaign_dim Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_location_dim Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_commerce_transaction_fact Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_commerce_line_item_fact Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_queue_item Table Created. 
20:16:11 2020-03-25 30267 [debug_log] owa_site_user Table Created. 
20:16:11 2020-03-25 30267 [debug_log] Post install proceadure was a success. 
20:16:11 2020-03-25 30267 [debug_log] Module base activated 
20:16:11 2020-03-25 30267 [debug_log] Installation complete. 
20:16:11 2020-03-25 30267 [debug_log] Checking for existence of default site. 
20:16:11 2020-03-25 30267 [debug_log] Created default site. 
20:16:11 2020-03-25 30267 [debug_log] Install Complete Flag added to configuration

**Comment by VeeRHunter** [comment]
https://prnt.sc/rnavxi
I am getting this screen after tap Continue button even I input correct database password.

**Comment by padams** [comment]
Weird. Do you have an owa-config.php file in your base OWA directory?

**Comment by VeeRHunter** [comment]
No, I have only owa-config-dist.php file at this moment

**Comment by VeeRHunter** [comment]
I already tried to change this owa-config-dist.php to owa-config.php.
Of course I changed owa-config.php file with correct config and test again.
But failed. In this case, I can create new admin user, but I can't login

**Comment by padams** [comment]
If OWA can’t create the owa-config.php file then its likely a permissions issue  in the OWA directory. 

Also what version of OS and PHP are you running?

**Comment by VeeRHunter** [comment]
I already give permissions for OWA directory.
And then I am using Ubuntu 18.04 and PHP 7.2

**Comment by padams** [comment]
You would need to remove the current config file from the mix and then walk through the installer again with debug turned on to get the info we need in the log file. Can you drop your tables and start over again in debug mode?

**Comment by padams** [comment]
Sorry one thing. Add the development handler line from the config file into install.php.

**Comment by VeeRHunter** [comment]
How can I do that?

**Comment by padams** [comment]
Just copy and paste that line from OWA-config.php into the install.php file below the opening `<?php`

**Comment by VeeRHunter** [comment]
Oh, I can go to next step, but I am getting this screen.
http://prntscr.com/rncsiv
I didn't have admin account at this moment, what is next step please?

**Comment by VeeRHunter** [comment]
There?

**Comment by VeeRHunter** [comment]
I am getting this. please check and let me know.
11:33:08 2020-03-26 17684 [debug_log] EHS: Event was handled successfully by all handlers. 
11:33:08 2020-03-26 17684 [debug_log] Handling request with params: Array
(
    [do] => base.installConfig
    [public_url] => http://.../
    [db_type] => mysql
    [db_host] => localhost
    [db_name] => owadb
    [db_user] => owauser
    [db_password] => 
    [nonce] => 145cdf6355
    [save_button] => Continue...
)
 
11:33:08 2020-03-26 17684 [debug_log] About to perform action: base.installConfig 
11:33:08 2020-03-26 17684 [debug_log] Performing Action: owa_installConfigController 
11:33:08 2020-03-26 17684 [debug_log] passed nonce: 145cdf6355 | matching nonce: 145cdf6355 
11:33:08 2020-03-26 17684 [debug_log] Assembling view: owa_installView 
11:33:08 2020-03-26 17684 [debug_log] Total session time: 0.015387058258057 
11:33:08 2020-03-26 17684 [debug_log] goodbye from OWA 
11:33:10 2020-03-26 17684 [debug_log] check for http host 
11:33:10 2020-03-26 17684 [debug_log] Setting cookie domain to .... 
11:33:10 2020-03-26 17684 [debug_log] *** Starting Open Web Analytics v1.6.6. Running under PHP v7.2.28-3+ubuntu18.04.1+deb.sury.org+1 (Linux) *** 
11:33:10 2020-03-26 17684 [debug_log] Request URL: /install.php 
11:33:10 2020-03-26 17684 [debug_log] User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36 
11:33:10 2020-03-26 17684 [debug_log] Host: ...
11:33:10 2020-03-26 17684 [debug_log] Caller configuration overrides applied. 
11:33:10 2020-03-26 17684 [debug_log] Filtering register_build_package 
11:33:10 2020-03-26 17684 [debug_log] Filtering register_build_package 
11:33:10 2020-03-26 17684 [debug_log] Filtering register_build_package 
11:33:10 2020-03-26 17684 [debug_log] base Schema version is 1 
11:33:10 2020-03-26 17684 [debug_log] base Required Schema version is 9 
11:33:10 2020-03-26 17684 [debug_log] Getting state - store: u key:  
11:33:10 2020-03-26 17684 [debug_log] Notifying listeners of init 
11:33:10 2020-03-26 17684 [debug_log] no listeners registered for this event type. 
11:33:10 2020-03-26 17684 [debug_log] EHS: Responses - Array
(
)
 
11:33:10 2020-03-26 17684 [debug_log] EHS: Event was handled successfully by all handlers. 
11:33:10 2020-03-26 17684 [debug_log] Handling request with params: Array
(
    [do] => base.installStart
)
 
11:33:10 2020-03-26 17684 [debug_log] About to perform action: base.installStart 
11:33:10 2020-03-26 17684 [debug_log] Performing Action: owa_installStartController 
11:33:10 2020-03-26 17684 [debug_log] Assembling view: owa_installView 
11:33:10 2020-03-26 17684 [debug_log] Total session time: 0.0075869560241699 
11:33:10 2020-03-26 17684 [debug_log] goodbye from OWA

**Comment by Maaiins** [comment]
> https://prnt.sc/rnavxi
> I am getting this screen after tap Continue button even I input correct database password.

Check your database for access permission, is owauser allowed to access from localhost?

**Comment by VeeRHunter** [comment]
Okay, let me check

**Comment by VeeRHunter** [comment]
Please check this.
http://prntscr.com/rne9u7

**Comment by Maaiins** [comment]
Hmm looks fine. Are you using any special chars in the password? Maybe some encoding trouble, try an easier password.

**Comment by VeeRHunter** [comment]
For database?

**Comment by VeeRHunter** [comment]
I am using the strongest password at this moment for security

**Comment by Maaiins** [comment]
> For database?

Yes, maybe there is some problem

**Comment by VeeRHunter** [comment]
Okay, let me try

**Comment by VeeRHunter** [comment]
I can't go any more from this login screen.
http://prntscr.com/rneirf

**Comment by VeeRHunter** [comment]
Detail is here.

 
12:40:35 2020-03-26 30267 [debug_log] EHS: Event was handled successfully by all handlers. 
12:40:35 2020-03-26 30267 [debug_log] Handling request with params: Array
(
    [site_id] => 
    [do] => base.installBase
    [protocol] => http://
    [domain] => 178.128.204.206/
    [user_id] => admin
    [email_address] => veerhunter127@gmail.com
    [password] => password1234
    [nonce] => 69cfe868bc
    [save_button] => Continue...
)
 
12:40:35 2020-03-26 30267 [debug_log] About to perform action: base.installBase 
12:40:35 2020-03-26 30267 [debug_log] <errorentry>
	<datetime>2020-03-26 12:40:35 (PDT)</datetime>
	<errornum>8</errornum>
	<errormsg>Undefined index: headline</errormsg>
	<scriptname>/var/www/html/owa/owa_base.php</scriptname>
	<scriptlinenum>104</scriptlinenum>
</errorentry>

 
12:40:35 2020-03-26 30267 [debug_log] <errorentry>
	<datetime>2020-03-26 12:40:35 (PDT)</datetime>
	<errornum>8</errornum>
	<errormsg>Undefined index: message</errormsg>
	<scriptname>/var/www/html/owa/owa_base.php</scriptname>
	<scriptlinenum>108</scriptlinenum>
</errorentry>

 
12:40:35 2020-03-26 30267 [debug_log] <errorentry>
	<datetime>2020-03-26 12:40:35 (PDT)</datetime>
	<errornum>8</errornum>
	<errormsg>Undefined index: headline</errormsg>
	<scriptname>/var/www/html/owa/owa_base.php</scriptname>
	<scriptlinenum>104</scriptlinenum>
</errorentry>

 
12:40:35 2020-03-26 30267 [debug_log] <errorentry>
	<datetime>2020-03-26 12:40:35 (PDT)</datetime>
	<errornum>8</errornum>
	<errormsg>Undefined index: message</errormsg>
	<scriptname>/var/www/html/owa/owa_base.php</scriptname>
	<scriptlinenum>108</scriptlinenum>
</errorentry>

 
12:40:35 2020-03-26 30267 [debug_log] <errorentry>
	<datetime>2020-03-26 12:40:35 (PDT)</datetime>
	<errornum>8</errornum>
	<errormsg>Undefined index: headline</errormsg>
	<scriptname>/var/www/html/owa/owa_base.php</scriptname>
	<scriptlinenum>104</scriptlinenum>
</errorentry>

 
12:40:35 2020-03-26 30267 [debug_log] <errorentry>
	<datetime>2020-03-26 12:40:35 (PDT)</datetime>
	<errornum>8</errornum>
	<errormsg>Undefined index: message</errormsg>
	<scriptname>/var/www/html/owa/owa_base.php</scriptname>
	<scriptlinenum>108</scriptlinenum>
</errorentry>

 
12:40:35 2020-03-26 30267 [debug_log] <errorentry>
	<datetime>2020-03-26 12:40:35 (PDT)</datetime>
	<errornum>8</errornum>
	<errormsg>Undefined index: headline</errormsg>
	<scriptname>/var/www/html/owa/owa_base.php</scriptname>
	<scriptlinenum>104</scriptlinenum>
</errorentry>

 
12:40:35 2020-03-26 30267 [debug_log] <errorentry>
	<datetime>2020-03-26 12:40:35 (PDT)</datetime>
	<errornum>8</errornum>
	<errormsg>Undefined index: message</errormsg>
	<scriptname>/var/www/html/owa/owa_base.php</scriptname>
	<scriptlinenum>108</scriptlinenum>
</errorentry>

 
12:40:35 2020-03-26 30267 [debug_log] <errorentry>
	<datetime>2020-03-26 12:40:35 (PDT)</datetime>
	<errornum>8</errornum>
	<errormsg>Undefined index: headline</errormsg>
	<scriptname>/var/www/html/owa/owa_base.php</scriptname>
	<scriptlinenum>104</scriptlinenum>
</errorentry>

 
12:40:35 2020-03-26 30267 [debug_log] <errorentry>
	<datetime>2020-03-26 12:40:35 (PDT)</datetime>
	<errornum>8</errornum>
	<errormsg>Undefined index: message</errormsg>
	<scriptname>/var/www/html/owa/owa_base.php</scriptname>
	<scriptlinenum>108</scriptlinenum>
</errorentry>

**Comment by Maaiins** [comment]
Ah could be a result of the dev mode @padams can say more about it. Can you test it with an regular installation?

**Comment by Maaiins** [comment]
Can you Login? Be careful the users are casesenstive

**Comment by VeeRHunter** [comment]
How can I do that?

**Comment by VeeRHunter** [comment]
I have just try again.
But after login, I can go back to the previous screen.
http://prntscr.com/rnel1s

**Comment by VeeRHunter** [comment]
Is this correct step?

**Comment by Maaiins** [comment]
Maybe i can reproduce this szenario. Please give me some time.

**Comment by Maaiins** [comment]
Can you tell me the special chars you are using in your previous password?

**Comment by padams** [comment]
Are you running OWA under a fully qualified domain name? ie. http://some.domain.com? or are you accessing via an IP address?

**Comment by VeeRHunter** [comment]
I am using this under ip address, is this problem?

**Comment by padams** [comment]
Yes. Cookies cannot be set without a fully qualified domain.

**Comment by VeeRHunter** [comment]
Okay, let me test under domain name, not ip address

**Comment by Maaiins** [comment]
I think i can close this one as you opened #515
