### ISSUE TITLE
Is not displayed "Browser Types" and "Operating Systems" and other issues...

### ISSUE THREAD

**Issue by L1TWIN** [Open-Web-Analytics/Open-Web-Analytics#495]
Hello!
Forgive me in advance for my English, I'm from Russia) Today I installed OWA. This is a very cool product, for which thanks to the creator! But, there are several problems. I would be grateful if you could help me.

1. In section **Browser Types**, I don't see browsers from which there were clicks:
![image](https://user-images.githubusercontent.com/16645444/77665686-d0b28680-6fa1-11ea-8ae6-f368114f583c.png)
Although in the database, they are:
![image](https://user-images.githubusercontent.com/16645444/77665788-f049af00-6fa1-11ea-90eb-0e18ec1cd65f.png)

2. Also in section **Operating Systems**:
![image](https://user-images.githubusercontent.com/16645444/77665961-2c7d0f80-6fa2-11ea-8afc-9bef5f9f6b59.png)
![image](https://user-images.githubusercontent.com/16645444/77665980-330b8700-6fa2-11ea-8d56-e54b68eafe6a.png)
More than 30 minutes passed, but the data did not appear...

3. Sections **Entry Pagesand** and **Exit Pages** also do not show page lists. Should there be lists at all?)
![image](https://user-images.githubusercontent.com/16645444/77667948-a4e4d000-6fa4-11ea-8b92-a6bccbf0055b.png)

4. The resolution of my screen is 1440x900. Apparently due to too long links, part of the screen moved to my right. Where can I set the block width manually?
![image](https://user-images.githubusercontent.com/16645444/77666771-2dfb0780-6fa3-11ea-8bab-fd15c7faafad.png)

5. In section **Referral Link Text**, I get this code, instead of text:
![image](https://user-images.githubusercontent.com/16645444/77667338-df01a200-6fa3-11ea-9e31-d94fb9687b53.png)

6. On the dashboard, in section **Latest Visits**, I have "_(not set)   ((not set))_". What data should be displayed here?
![image](https://user-images.githubusercontent.com/16645444/77668213-f1301000-6fa4-11ea-9984-9797279a76b9.png)

Thanks in advance!

**Comment by L1TWIN** [comment]
I forgot to write about my server:
OS: **Debian 9 Latest**
PHP: **7.0.33-0+deb9u7**
MySQL: **5.5.9999**
Mode: **FastCGI (Nginx + PHP-FPM)**

**Comment by padams** [comment]
Which version of OWA did you install?

**Comment by L1TWIN** [comment]
> Which version of OWA did you install?

Open Web Analytics 1.6.6

**Comment by padams** [comment]
Also you will need to turn on development logging on the OWA config file, attempt a tracking request and then look in OWA error log to see what might be happening here. The file is located at owa-data/logs/errors_****

**Comment by L1TWIN** [comment]
> Also you will need to turn on development logging on the OWA config file, attempt a tracking request and then look in OWA error log to see what might be happening here. The file is located at owa-data/logs/errors_****

I have already included the logs. I checked, there were no errors, then deleted the file. So far, a new file with errors has not been created ...

**Comment by padams** [comment]
I don’t see where you included the logs. They don’t seem to be attached to the ticket. 

The log file will be filled with chatter from OWA about each step In the tracking process. It will show you exactly what OWA is seeing and doing to each piece of data. 

These are not generalized bugs that can be reproduced so it’s likely something about your setup. 

Maybe post the portion of your error log that logs a full tracking request that you initiate.

**Comment by L1TWIN** [comment]
> I don’t see where you included the logs. They don’t seem to be attached to the ticket.
> 
> The log file will be filled with chatter from OWA about each step In the tracking process. It will show you exactly what OWA is seeing and doing to each piece of data.
> 
> These are not generalized bugs that can be reproduced so it’s likely something about your setup.
> 
> Maybe post the portion of your error log that logs a full tracking request that you initiate.

![image](https://user-images.githubusercontent.com/16645444/77672714-0e67dd00-6fab-11ea-807f-53de86e8126d.png)
Do you mean this? Yes, there were records that module **Maxmind GeoIP** was turned on, that it was activated, etc. But there were no errors there, so I deleted the file in order to start monitoring again and find the error.

**Comment by L1TWIN** [comment]
I can throw you the settings file from the database
![image](https://user-images.githubusercontent.com/16645444/77673101-8d5d1580-6fab-11ea-8225-fcce2139fd4b.png)

**Comment by L1TWIN** [comment]
Maybe in the settings, what's wrong ...

**Comment by padams** [comment]
> > I don’t see where you included the logs. They don’t seem to be attached to the ticket.
> 
> > 
> 
> > The log file will be filled with chatter from OWA about each step In the tracking process. It will show you exactly what OWA is seeing and doing to each piece of data.
> 
> > 
> 
> > These are not generalized bugs that can be reproduced so it’s likely something about your setup.
> 
> > 
> 
> > Maybe post the portion of your error log that logs a full tracking request that you initiate.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/16645444/77672714-0e67dd00-6fab-11ea-807f-53de86e8126d.png)
> 
> Do you mean this? Yes, there were records that module **Maxmind GeoIP** was turned on, that it was activated, etc. But there were no errors there, so I deleted the file in order to start monitoring again and find the error.

Yes. Uncomment that line to turn on development tracking. It will fill up the log file with useful info.

**Comment by L1TWIN** [comment]
Sorry, I didn't see that it was commented out))) I'll turn it on now!

**Comment by L1TWIN** [comment]
[logs.zip](https://github.com/Open-Web-Analytics/Open-Web-Analytics/files/4388609/logs.zip)

**Comment by padams** [comment]
That log shows that all the requests are from robots.

Also you seem to be using the PHP tracker instead of the JavaScript tracker.

The PHP tracker isn’t going to set the page title for you. See the wiki on how to properly configure the php tracker.

**Comment by L1TWIN** [comment]
Yes, PHP tracker
![image](https://user-images.githubusercontent.com/16645444/77677183-280c2300-6fb1-11ea-86e7-6e4b807d49d5.png)

**Comment by padams** [comment]
I would look into how you are setting the `$title` variable. Then try to isolate an actual tracking request from a human in your log file :)

**Comment by L1TWIN** [comment]
**$title** stores the title of the site. It is generated on all pages automatically))
![image](https://user-images.githubusercontent.com/16645444/77680298-93f08a80-6fb5-11ea-84a3-f99c4ceec0fe.png)

**Comment by padams** [comment]
Can you isolate a tracking request in your logs from an actual human browner (ie. not a robot)? If so pos that here so we can see what's happening.

**Comment by L1TWIN** [comment]
Good morning!
Do you mean to isolate this code from robots?
![image](https://user-images.githubusercontent.com/16645444/77713839-4dbd1a80-6ff9-11ea-8785-10f631ae460e.png)

**Comment by L1TWIN** [comment]
By the way, tell me please, is there a solution for quick cleaning of all statistics? Or do you need to manually delete everything through the database?))

**Comment by padams** [comment]
No. In your log file. Locate a page review request from a real browser. Not a robot.

**Comment by L1TWIN** [comment]
I found my visit from the phone. Here is the piece of code. Unless of course I understand you correctly))
[log.txt](https://github.com/Open-Web-Analytics/Open-Web-Analytics/files/4391088/log.txt)

**Comment by L1TWIN** [comment]
In general, logging visits of bots is disabled in the settings:
![image](https://user-images.githubusercontent.com/16645444/77714522-0899e800-6ffb-11ea-8eeb-bcca25924936.png)

**Comment by padams** [comment]
That's it? There should be a lot more lines of debug.

**Comment by L1TWIN** [comment]
This was only part of the code. Although I turned off **Log Requests From Known Robots**, there are still bots in the logs 😐
Bro, now I went from a mobile phone and from a computer to a monitored site and then to statistics. Here are the logs:
[logs.zip](https://github.com/Open-Web-Analytics/Open-Web-Analytics/files/4391171/logs.zip)

**Comment by L1TWIN** [comment]
By the way, the database has already increased the number of operating systems and browsers, but there are still no lists:
![image](https://user-images.githubusercontent.com/16645444/77716016-fae66180-6ffe-11ea-921f-fe155aaaf7a6.png)
![image](https://user-images.githubusercontent.com/16645444/77716073-181b3000-6fff-11ea-9a68-200574c4732e.png)

**Comment by padams** [comment]
It's not completing the tracking requests for some reason. I'd need to see an updated log file to tell where it might be stopping.

**Comment by L1TWIN** [comment]
here)
[logs2.zip](https://github.com/Open-Web-Analytics/Open-Web-Analytics/files/4391322/logs2.zip)

**Comment by padams** [comment]
I think what's happening is that you are tracking the actions before tracking the page views.

Try reversing this order instead.

$owa->trackpageView();
$owa->trackAction(...

**Comment by L1TWIN** [comment]
Oooo))

**Comment by L1TWIN** [comment]
I updated and the list appeared immediately:
![image](https://user-images.githubusercontent.com/16645444/77721752-8cf56680-700d-11ea-8bdd-f369def347eb.png)

**Comment by L1TWIN** [comment]
Thank you very much 👍👍👍

**Comment by padams** [comment]
Also are you sure you need to track an action on every request? Typically there is logic hat triggers an action....(ie. a video play, etc.

**Comment by L1TWIN** [comment]
I will have 6 groups and in it 1-2 types of pages. Thus, I want to monitor page type statistics. Does this give a heavy load?)

**Comment by padams** [comment]
Page type is fine. I'm taking about `$owa->trackAction(...`. Action tracking is a second tracking event that should be used for tracking events that happen on the web page. It's almost never used  in PHP tracker.

**Comment by L1TWIN** [comment]
I also wanted to ask. Do you have the opportunity to implement "Statistics retention period". So that in the control panel, you can specify for what period to store statistics. For example, 3 months, all that was earlier than this period, so that it is automatically deleted.

**Comment by L1TWIN** [comment]
And it would be cool to add a button to the control panel so that you can completely clear the statistics for all projects, or for some specific ones)

**Comment by L1TWIN** [comment]
I thought that after deleting the site, statistics will also be deleted along with it, but when you add it again, all statistics are displayed)

**Comment by L1TWIN** [comment]
And so in general, this is really a very cool project. I will have a lot of sites and I have been looking for a suitable solution for myself, preferably without using JS. And your solution is perfect for me. Thank you again for this !!! From the first profit, donat from me)))

**Comment by padams** [comment]
great.  I'll close this issue.

Please consider sponsoring the project (button at top of page).
