### ISSUE TITLE
Different line endings in repository

### ISSUE THREAD

**Issue by Maaiins** [Open-Web-Analytics/Open-Web-Analytics#504]
Some files are commit with CRLF (Windows Style) line endings and some with LF (Unix). This is why git marks some files as changed completely, when I committed them.

I will normalize them to LF (Recommended) and create a pull request. But first all other Pull requests needs to be merged. Because the merge will fail when I renormalize files that are changed by a pull requests.

**Comment by padams** [comment]
interesting. i hadn't seen that.

**Comment by Maaiins** [comment]
@padams fixed in master can be closed

**Comment by Maaiins** [comment]
Fixed in master will be closed
