### ISSUE TITLE
Plugin for Mantisbt 2.x

### ISSUE THREAD

**Issue by CasN** [Open-Web-Analytics/Open-Web-Analytics#508]
[owa10.zip](https://github.com/Open-Web-Analytics/Open-Web-Analytics/files/4414876/owa10.zip)
Attached a simple plugin to add OWA to your mantis installation.
For question, you can mail me @ cas-at-nuy.info

**Comment by Maaiins** [comment]
@padams i would recommend we make an area where we can add user plugins and so on. So everyone who need´s this can download the plugin from the developer directly.

Another thought we can move wordpress and mediawiki integration to separate repositories.

Any thoughts?

**Comment by padams** [comment]
Agreed. Perhaps a wiki page with links to the developer?

As for the WordPresss plugin, yes, the goal is to move it to the official WordPress plugin repo. The only issues that it's currently part of the OWA bistro and if that file was removed it would break a lot of people's installs. 

I'm working on a way to handle this in #446

**Comment by Maaiins** [comment]
> Perhaps a wiki page with links to the developer?

Would be a nice idea to add some Third Party Plugins/Integration Page

**Comment by padams** [comment]
in the wiki, or in the app itself?

**Comment by Maaiins** [comment]
Wiki. I made a wiki page, hopefully ok.

Take a look at: https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Third-Party-Modules---Integrations

@CasN Please upload your plugin to your own repository

**Comment by CasN** [comment]
My plugin can be found here:
https://github.com/CasN/Open-Web-Analytics-Mantis

**Comment by Maaiins** [comment]
Added your integration to: https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Third-Party-Modules-or-Integrations

Closing this issue
