### ISSUE TITLE
Refactor Controller Inheritance

### ISSUE THREAD

**Issue by padams** [Open-Web-Analytics/Open-Web-Analytics#510]
There is currently a lot of code duplication among actions that need to be performed via the web app, the CLI, and the REST API. Also the validation system defined n web app controller isn't put to use in CLI or REST requests. 

To fix this we need to refactor how controllers can be inherited. To do:

1. make it possible to do this:
-- siteAddController extends adminController
--- siteAddCliController extends siteAddController
--- siteAddRestController extends siteAddController

2. Refactor owa_controller to allow for more modular overriding of methods:
- move validations to a new `validate` method
- move view setting out of action method and into a new `success` method. 
- add a `mode` param to controllers so that OWA knowns what kind of controller is running. Values would be `web_app|cli|rest_api`
 
3. Refactor the CLI view to output validation errors

**Comment by padams** [comment]
Might want to review this one @Maaiins

**Comment by Maaiins** [comment]
I will do this. In future it would be better to make a separate pull request. This will make reviews much easier ;-)

**Comment by padams** [comment]
yes. sorry!

**Comment by Maaiins** [comment]
No Problems ;-)

I found several files which can also refactored

- owa_changeUserPasswordCliController
- owa_installBaseController
- owa_installConfigController
- owa_loginController
- owa_optionsGoalEditController
- owa_passwordResetRequestController
- owa_sitesEditController
- owa_sitesEditSettingsController
- owa_usersAddController
- owa_usersChangePasswordController
- owa_usersEditController

**Comment by padams** [comment]
Yes. I'm wanting to prioritize controllers that should also be accessible via CLI and REST APIs. 

- listing sites
- adding a new site
- adding a new user
- changing user password

I need to work on refactoring how the REST API works next as right now it doesn't use the controller model in the same way that the CLI and Web app do. REST API is basically one controller with plugin logic methods....

**Comment by Maaiins** [comment]
My idea makes this refactor very quickly, so I will refactor this controllers tomorrow.

It would be nice when you add me to access the repository would be easier to create pull request.

**Comment by padams** [comment]
Done. I meant to do this last week :)

**Comment by Maaiins** [comment]
Thanks. Everything fine ;-)
