### ISSUE TITLE
Is it possible to do this on Subdomain?

### ISSUE THREAD

**Issue by VeeRHunter** [Open-Web-Analytics/Open-Web-Analytics#515]
I want to do this on Subdomain, not dedicated domain.
Please help me

**Comment by Maaiins** [comment]
This depends on the possibilities of your hoster and your Installation.

Are you using javascript tracking only?
Are you using PHP Tracking?
Are you using OpenWebAnalytics as standalone or as wordpress integration?

**Comment by VeeRHunter** [comment]
I am using PHP, Exactly want to use Symfony project

**Comment by Maaiins** [comment]
I think you have to do the following steps

- Add OpenWebAnayltics to the root of your symfony project (The folder with the web directory)
- Add a subdomain and point the root directory to the OpenWebAnalytics directory
- Add Tracking to Symfony (Don´t forget to call `$owa->trackPageView()`)
- Build a wrapper and require OpenWebAnalytics (`owa_php.php`)

Should work

**Comment by VeeRHunter** [comment]
I can get this result after install OWA on subdomain.
What is my next step?
http://prntscr.com/ryj0g6

**Comment by Maaiins** [comment]
Call the tracking from within your symfony code (controller) or implement the javascript tracking via twig

Read this first: https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki#tracking-web-sites--applications

**Comment by padams** [comment]
And this:


https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting

**Comment by VeeRHunter** [comment]
Okay, thanks.
Let me check

**Comment by VeeRHunter** [comment]
Is it possible to use this code inside twig?
http://prntscr.com/ryjrji

**Comment by Maaiins** [comment]
> Call the tracking from within your symfony code (controller) or implement the javascript tracking via twig

As I already said earlier yes. But to implement this in the twig template you have to follow their guidelines to implementing javascript code. Which we can´t and don´t support.

**Comment by VeeRHunter** [comment]
How can I set this?
http://prntscr.com/ryt2tj

Also how can I disable this?
http://prntscr.com/ryt357
This is not page, just get data from api, but page view number is including this too.

Please let me know

**Comment by Maaiins** [comment]
> How can I set this?
> http://prntscr.com/ryt2tj

These are the visitor id and the geolocation of the visitor. Enable geolocation lookup under administration and follow these steps: https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Maxmind-GeoIP-Module. To add the visitor id manually add `owa_cmds.push(['setUserName', 'xxxx']);` to your javascript tracking.

> Also how can I disable this?
> http://prntscr.com/ryt357
> This is not page, just get data from api, but page view number is including this too.

It´s quite hard to undestand what you mean by this. Am I right you want to disable clickstreams? Remove `owa_cmds.push(['trackClicks']);` from your javascript tracking.

**Comment by VeeRHunter** [comment]
I am setting it on php code

**Comment by Maaiins** [comment]
> Is it possible to use this code inside twig?
> http://prntscr.com/ryjrji

You asked there to use the javascript code. Are u using this code in Twig? Then it´s javascript

**Comment by VeeRHunter** [comment]
Yes, I was tried to use javascript inside twig, but failed

**Comment by VeeRHunter** [comment]
So I used this owa on php file.
So I can get some result on it.

**Comment by Maaiins** [comment]
Use `$owa->setUserName('<name or id>')`

**Comment by Maaiins** [comment]
Will close this issue due inactivity, feel free to reopen
