### ISSUE TITLE
Bug: Referral html content shown in Referral

### ISSUE THREAD

**Issue by Maaiins** [Open-Web-Analytics/Open-Web-Analytics#518]
it also did not update all of the titles, for facebook it even included their html in OWA, see screenshot.. its not critical to me, but maybe you want to check whats going wrong there... 
<img width="715" alt="Screenshot 2020-03-30 at 15 18 01" src="https://user-images.githubusercontent.com/59607366/77916914-1de07200-729a-11ea-832c-e74b55ed04f1.png">

_Originally posted by @znrR in https://github.com/Open-Web-Analytics/Open-Web-Analytics/pull/502#issuecomment-605995100_

**Comment by znrR** [comment]
hey guys @padams @Maaiins , not sure if this fix made it into 1.6.8 (where could i see that on GH?) however, if the fix made it in there its not working on WP, just discovered fresh referrers which were not in the DB yet that have html included.
![Screenshot 2020-04-16 at 21 43 31](https://user-images.githubusercontent.com/59607366/79500033-1ce66900-802c-11ea-9f4f-c9dcc36d4583.png)

thats the post on redit if you want to test on your end: https://www.reddit.com/r/berlin/comments/g29d7d/wheres_a_good_place_to_get_a_bike_these_days/

**Comment by Maaiins** [comment]
I think I found it, will look into it.

You can see the changelog here: https://github.com/Open-Web-Analytics/Open-Web-Analytics/releases
