### ISSUE TITLE
Bug: Pagination not working

### ISSUE THREAD

**Issue by Maaiins** [Open-Web-Analytics/Open-Web-Analytics#520]
There are two different problems:

- When I click on a page of the pagination this will redirect me to the sites roster every time.
- After adding the get parameter `owa_page` this will never go away. So every time a paginated list occurs this will automatically open page two for example, which shouldn't happen.

**Comment by padams** [comment]
Can you share URL in admin where this is happening?
I don't see it happening with the pagination for  any of the in-page reporting elements..

**Comment by Maaiins** [comment]
Just uncomment `$this->makePaginationFromResultSet($visits)` this line in `report_latest_visits.tpl` and try to click the latest visit pagination in Dashboard

**Comment by padams** [comment]
This isn't happening on: /index.php?owa_siteId=foo&owa_period=last_seven_days&owa_do=base.reportVisitors

**Comment by Maaiins** [comment]
First of all uncomment the line described above then open:
/index.php?owa_siteId=<SITE_ID>&owa_period=last_seven_days&owa_do=base.reportDashboard

Scroll down and klick the second page
![image](https://user-images.githubusercontent.com/7676540/78819828-2130d780-79d7-11ea-9c13-139fae2fbff6.png)

This will redirect to: /index.php?owa_siteId=<SITE_ID>&owa_period=last_seven_days&owa_page=2

And not to the dashboard again

**Comment by padams** [comment]
I think it's just a malformed use of the pagination method.

See the usage on `report_visitors.tpl` and the method in the `owa_template` class.

` <?php echo $this->makePaginationFromResultSet($visits, array('do' => 'base.reportVisitors'), true);?>`

**Comment by Maaiins** [comment]
True looks like a malformed usage..

**Comment by Maaiins** [comment]
Will close this one
