### ISSUE TITLE
Feature Request: Assign user to domain(s)

### ISSUE THREAD

**Issue by macrobber** [Open-Web-Analytics/Open-Web-Analytics#522]
Would be amazing to be able to create a new user and ONLY allow them to view / admin specific domains being tracked by OWA.

In this scenario, OWA is tracking multiple sites.  as far as I can tell, admin has access to view ALL the sites.  It would be awesome to be able to assign a domain / domains to an individual user.  So while the system may track 10 sites, a given user only has access to one.

**Comment by padams** [comment]
You can control user access on the Site Settings page for each tracked domain. IS that what you are looking for?

**Comment by macrobber** [comment]
Yeah, that's perfect.  Is it possible to use the php-cli command to assign the domain at creation time? I'm thinking about the 'flow' of creating a new user and new domain without having to manually go into each domain and modify the user list.

**Comment by padams** [comment]
here are the CLI commands:

https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Command-Line-Interface-(CLI)

There is not an add-user command yet, but we are working on some more cli and REST API commands now.

**Comment by macrobber** [comment]
Excellent @padams - really loving the platform so far.  In thinking about future applications and on-boarding new sites, I'd love to see an add-user cli command as well as the ability to assign that user to a default domain.  That would be slick.

**Comment by padams** [comment]
Yeah. We will add that CLI soon for sure. thanks.
