### ISSUE TITLE
Hello Word Module Error on new install

### ISSUE THREAD

**Issue by macrobber** [Open-Web-Analytics/Open-Web-Analytics#526]
Was interested in exploring building a new module.  When I enable the Hello World module on a fresh install, I get a 500 error.  
Apache Logs show the following:

`PHP Fatal error:  Uncaught Exception: Class File /var/www/html/Open-Web-Analytics/modules/hello/owa_reportSearchtermsController.php not existend! in /var/www/html/Open-Web-Analytics/owa_lib.php:505\nStack trace:\n#0 /var/www/html/Open-Web-Analytics/owa_coreAPI.php(366): owa_lib::factory('/var/www/html/O...', '', 'owa_reportSearc...', Array)\n#1 /var/www/html/Open-Web-Analytics/owa_coreAPI.php(780): owa_coreAPI::moduleFactory('hello.reportSea...', 'Controller', Array)\n#2 /var/www/html/Open-Web-Analytics/owa_coreAPI.php(1219): owa_coreAPI::performAction('hello.reportSea...', Array)\n#3 /var/www/html/Open-Web-Analytics/owa_caller.php(222): owa_coreAPI::handleRequest(NULL, 'hello.reportSea...')\n#4 /var/www/html/Open-Web-Analytics/owa_caller.php(164): owa_caller->handleRequest()\n#5 /var/www/html/Open-Web-Analytics/index.php(46): owa_caller->handleRequestFromUrl()\n#6 {main}\n  thrown in /var/www/html/Open-Web-Analytics/owa_lib.php on line 505, referer: http://localhost/Open-Web-Analytics/index.php?owa_do=base.reportDashboard&owa_siteId=86a9106ae65537651a8e456835b316ab`

**Comment by padams** [comment]
I'm not seeing that on a fresh install. It looks like you are calling an action like `hello.reportSearchterms` or something and OWA can't find the controller for it in the hello module - which is right because it's not supposed to be there.

If you wanton create new actions you need create new controller files that map to the action and then put them in the right place.

**Comment by macrobber** [comment]
I haven't changed any of the code in the module - and just re-looked at your source.  The code I think you are referencing is in the included module.php file - line 67:

`    public function registerNavigation() {
        $this->addNavigationSubGroup('Hello World', 'hello.reportDashboard', 'Hello Dashboard');
        $this->addNavigationLinkInSubGroup('Hello World','hello.reportSearchterms','also to the dashboard',1);

    }
`

**Comment by padams** [comment]
ah you re right. Sorry it's been a while since I've been in that code. Those are just examples of how  to register links in the admin interface. if you click on them they will throw that error because the necessary controller doesn't exist.

**Comment by macrobber** [comment]
No worries man - I totally understand.  So, if I wanted to link to the example_setting page (that is included in the module), would I just call $this->addNavigationSubGroup('Hello World', 'hello.example_setting', 'Hello Dashboard');  ?

To get this page to display: https://github.com/Open-Web-Analytics/Open-Web-Analytics/blob/master/modules/hello/templates/example_settings.php

**Comment by padams** [comment]
`$this->addNavigationSubGroup('Hello World', 'hello.example_setting', 'Hello Dashboard'); `

will add a top level link to navigation to a controller than needs to be called owa_example_settingController and located at the base of the hello module's directory in a file called example_setting.php .

`$this->addNavigationLinkInSubGroup('Hello World','hello.reportSearchterms','also to the dashboard',1);`

This adds a sub link in the navigation to a controller class than needs to be called owa_reportSearchtermsController than need ot be located in a file called reportSearchterms.php in the base of the hello module directory.

`hello.reportSearchterms` is the action name in module.action format. If you created an action in another module you would call it via `yourmodule.youraction` and put the controller/view classes called `owa_youractionController` and `owa_youractionView` in a file called `youraction.php` in the base of the `yourmodule` module directory.

See the mapping convention?

**Comment by macrobber** [comment]
Excellent man.  Thanks for taking the time.  I will dive in and see if I can get it working.  I have a few ideas for an additional module and want to get a basic template up and running before starting on it.  Always responsive, thanks again!
