### ISSUE TITLE
Version not updated in 1.6.8

### ISSUE THREAD

**Issue by GaneshKandu** [Open-Web-Analytics/Open-Web-Analytics#529]
HI,

Version not updated in 1.6.8 i am still getting 1.6.7 version
[owa_1.6.8_packaged.tar](
https://github.com/Open-Web-Analytics/Open-Web-Analytics/releases/download/1.6.8/owa_1.6.8_packaged.tar)

Exact version doesn't mentioned in  owa_env.php of 1.6.8 package
[Source code (zip)](https://github.com/Open-Web-Analytics/Open-Web-Analytics/archive/1.6.8.zip) and [Source code (tar.gz)](https://github.com/Open-Web-Analytics/Open-Web-Analytics/archive/1.6.8.tar.gz)

**Comment by Maaiins** [comment]
Updated Version in Branch
