### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by manirahnama** [Open-Web-Analytics/Open-Web-Analytics#531]
I install it and evrything looks good but I get this error message
ERR_TOO_MANY_REDIRECTS

subdomain track.mydomain.com

**Comment by Maaiins** [comment]
Please tell us the following

**Affected Version(s)**: x.y.z

**PHP Version**: 7.x FPM

**Webserver**: Apache/Nginx

**Browser**: Chrome 80.x.x

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [ ] Standalone

**Description**  
 A clear and concise description of the problem.
What is not accessible, owa or your site?

I think there's something wrong with your .htaccess please check these first

**Comment by manirahnama** [comment]
OWA not accessible 
ERR_TOO_MANY_REDIRECTS
I install OWA on sub domain  and I checked it With Chrome 80.x.x I get this error message
Chrome 80.x.x

**Comment by Maaiins** [comment]
I cant reproduce this error on a fresh installation. 

Take a look into `owa-config.php` i think you have enforced https and the public url is set to http.

**Comment by Maaiins** [comment]
Will close this issue due inactivity, feel free to reopen
