### ISSUE TITLE
OWA WP Dashboard Layout collides with Dolly Plugin (which installed & on default onWP) 

### ISSUE THREAD

**Issue by znrR** [Open-Web-Analytics/Open-Web-Analytics#537]
**Affected Version(s)**: All Versions, incl 1.6.8

**Browser**: All Mac OS

**Installation Type**

- [X] Wordpress 5.4

**Description**  
Hi Peter, just a minor thing which took me ages to realise whats wrong and which gives the WP version a bad first impression. WP comes with the Dolly plugin default installed and turned active. the plugin displays a little text in the upper right corner and this text messes up the scaling OWA dashbaord layout. Its not a big deal, but gives a bad first impression ;-)  Its only happening at the dashboard...

**How to reproduce**  

**Possible Solution**  
Maybe its just a Z-Index Issue.

**Additional context**  
![Screenshot 2020-04-15 at 22 02 40](https://user-images.githubusercontent.com/59607366/79383311-47b9ba00-7f65-11ea-868e-71995b8492fa.png)

**Comment by padams** [comment]
I don’t think the Hello Dolly plug-in comes activated. I know it’s pre-installed, but I don’t see it activated in any of my installs.

**Comment by znrR** [comment]
ah ok, maybe i activated by accident... deleted now and love the scaling layout!!

**Comment by padams** [comment]
ok closing.
