### ISSUE TITLE
WP: Plugin Version not displayed correctly

### ISSUE THREAD

**Issue by znrR** [Open-Web-Analytics/Open-Web-Analytics#539]
In the Plugin overview of WP the OWA version gets not displayed, it tells "Version Master". Expected would be the actual OWA Version.
![Screenshot 2020-04-15 at 22 10 10](https://user-images.githubusercontent.com/59607366/79383797-17265000-7f66-11ea-8d42-540acc2d7405.png)

**Comment by emanueleg** [comment]
I see ( #439 ) this enhancement has been scheduled for 2.0 but I agree it would be useful to show the actual OWA version also in 1.6 releases

**Comment by padams** [comment]
I'll fix the build script in the next release.

**Comment by padams** [comment]
Closing as this is fixed in the build script now.
