### ISSUE TITLE
heatmap - not working in any mac browser

### ISSUE THREAD

**Issue by znrR** [Open-Web-Analytics/Open-Web-Analytics#540]
**Affected Version(s)**: All Versions, incl 1.6.8

**Browser**: All Mac OS

**Installation Type**

- [X] Wordpress 5.4

**Description**  
Never could get the heatmap working... Sounds like a great feature and would be great to see...

**Comment by Maaiins** [comment]
Please check your browser console for errors, when you open the domstream link

**Comment by znrR** [comment]
i thought it might be the same as with https://github.com/Open-Web-Analytics/Open-Web-Analytics/issues/541 but console both FX and chrome look super unsispicous (in regards to OWA)

(the one with the OWA play/stop interface is FX actually)

![Screenshot 2020-04-16 at 22 00 53](https://user-images.githubusercontent.com/59607366/79501388-3d172780-802e-11ea-937e-ff684eb3248a.png)
![Screenshot 2020-04-16 at 22 00 44](https://user-images.githubusercontent.com/59607366/79501394-3e485480-802e-11ea-8b98-1806de96af76.png)

**Comment by padams** [comment]
I have heat maps working fine...running under WordPress too!

**Comment by znrR** [comment]
i guess its a heatmap of where people click?

**Comment by padams** [comment]
Yes. OWA plots the clicks on top of the webpage and colors change from purple to red to indicate quantity of clicks.

**Comment by rob42** [comment]
Also having problems. Initial problem was due to uBlock and ghostery, bth blocked the CORS sites, especially the one that owa was on.

**Comment by rob42** [comment]
Second problem is a js error in firefox 69.0.1 Ubuntu 18.04. This could be a problem with avada theme in wordpress, not familiar with that at all:

Error: Syntax error, unrecognized expression: #owa_overlay.eyJzaXRlSWQiOiJhNTUxYzZiMTg3MTU3YWNhMThlZjUxMjVjMjBmY2RiNiIsInBlcmlvZCI6Imxhc3Rfc2V2ZW5fZGF5cyIsImFjdGlvbiI6ImxvYWRIZWF0bWFwIiwiYXBpX3VybCI6Imh0dHBzOlwvXC9jcC5jYXBpdGFscHJlZmVyZW5jZXMuY29tOjQwMDBcL2FwaS5waHAiLCJkb2N1bWVudF9pZCI6IjI2OTUwMTQ4MzYifQ==

jQuery 10
        error
        tokenize
        select
        ea
        find
        find
        find
        init
        init
        n
    init_sticky_header https://www.trueprofile.com/wp-content/themes/avada/js/main.js?ver=3.7.4:183
    trigger https://www.trueprofile.com/wp-content/themes/avada/js/main.js?ver=3.7.4:3446
    doScroll https://www.trueprofile.com/wp-content/themes/avada/js/main.js?ver=3.7.4:3332
    each jQuery
    doScroll https://www.trueprofile.com/wp-content/themes/avada/js/main.js?ver=3.7.4:3330
    each jQuery
    doScroll https://www.trueprofile.com/wp-content/themes/avada/js/main.js?ver=3.7.4:3309
    scrollHandler https://www.trueprofile.com/wp-content/themes/avada/js/main.js?ver=3.7.4:3268

​
