### ISSUE TITLE
dom stream - not working in any browser

### ISSUE THREAD

**Issue by znrR** [Open-Web-Analytics/Open-Web-Analytics#541]
**Before you open an issue:**

dom stream - not working in any browser
**Description**  

**How to reproduce**  

Dom recording worked in a preview version, but stopped working at some version. Tried in all Chrome, FX, Safari... 

Great feature that would be great to get working!

**Comment by Maaiins** [comment]
Please check your browser console for errors when you open the domstream link

**Comment by padams** [comment]
Make sure the downstream module is activated in OWA.

**Comment by znrR** [comment]
Is activated! Also logged in into admin...

when openening jscript console in Opera is see hell unfolding ;-) duh! comparative FX console also attached. Looks like Jquery is going crazy when calling the OWA dom link...

![FX Console_domlink](https://user-images.githubusercontent.com/59607366/79387540-2c9e7880-7f6c-11ea-8865-8c3c9439423b.png)
![Screenshot 2020-04-15 at 22 52 47](https://user-images.githubusercontent.com/59607366/79387547-2e683c00-7f6c-11ea-9eca-186a8deb8b44.png)
![Screenshot 2020-04-15 at 22 51 59](https://user-images.githubusercontent.com/59607366/79387549-2f00d280-7f6c-11ea-91ab-93d172d4468f.png)

**Comment by padams** [comment]
This might be a conflict between the version of jQuery WP is running and the one that works with OWA...

**Comment by padams** [comment]
It looks like your WP is loading jQuery 1.12.4.

**Comment by znrR** [comment]
ok turned off a few things... less red console warnings, found this OWA specific one. I believe various plugins load & use different versions of jquery in parallel.

owa.player.js:65 Uncaught TypeError: Cannot read property 'length' of undefined
    at OWA.player.load (owa.player.js:65)
    at Object.success (owa.player.js:87)
    at Object.resolveWith (VM282 jquery-1.6.4.min.js:2)
    at w (VM282 jquery-1.6.4.min.js:4)
    at XMLHttpRequest.d (VM282 jquery-1.6.4.min.js:4)

**Comment by znrR** [comment]
i had a look on another page. as far as i understand the console, theres no other Jquery loaded here and it also prints the error above.
![Screenshot 2020-04-16 at 00 06 09](https://user-images.githubusercontent.com/59607366/79393711-3331ed80-7f76-11ea-879b-e12682f797a2.png)

**Comment by znrR** [comment]
i had a look on another page and i see which plugin it is that loads a local version of jquery. i need that plugin, is there any chance of making it possible that their version of jquery and the OWA one do not conflict?

**Comment by padams** [comment]
Another reason to move this out of WP. :) Will look into it.

**Comment by Maaiins** [comment]
> Another reason to move this out of WP. :) Will look into it.

Our jquery isn´t using no conflict mode.

See: https://www.tutorialspoint.com/How-to-use-multiple-versions-of-jQuery-on-the-same-page

**Comment by znrR** [comment]
re: moving out of WP, not sure if that would help since the site is using jquery ;-) and yes considered moving the site out of WP but it was so much effort to build, guess we gotta stick with WP for. next project maybe I'll use gohugo or such...

putting OW jquery to no conflict should fix it?

**Comment by padams** [comment]
@Maaiins is working on some downstream changes so let’s wait for himto finish that up before triaging this.

**Comment by padams** [comment]
try the code in master now to see if this is fixed.

**Comment by BarCohen1** [comment]
Hello dear owa team, 
reproduced the issue as well, "owa.player.js:65 Uncaught TypeError: Cannot read property 'length' of undefined".
Noticed some changes in owa.player.js that might fix the issue - is that the case?
It's a great feature to have! thanks

**Comment by padams** [comment]
@BarCohen1 which version are you running? Is it a standalone install or are you using the WordPress plugin?

**Comment by BarCohen1** [comment]
Standalone install. I should note that taking the 'lastest' available fixed the issue (used version 1.6.8 previously), perhaps I could suggest releasing a version with the changes?
Thank you @padams !

**Comment by padams** [comment]
it's coming out soon. thanks.
