### ISSUE TITLE
dom clicks - how to configure

### ISSUE THREAD

**Issue by znrR** [Open-Web-Analytics/Open-Web-Analytics#542]
Hi Peter, is there a way of how i can setup my html that dom clicks displays something meaningful? 

![Screenshot 2020-04-15 at 22 16 37](https://user-images.githubusercontent.com/59607366/79384261-ce22cb80-7f66-11ea-9788-6f8434a1118e.png)

**Comment by padams** [comment]
Do you decorate your dom elements with meaningful IDs or names?

**Comment by padams** [comment]
Closing but feel free to re-open if need be.
