### ISSUE TITLE
URL Parameter to ignore - how to, when taking effect?

### ISSUE THREAD

**Issue by znrR** [Open-Web-Analytics/Open-Web-Analytics#543]
**Description**  
I entered parameters that i discovered in URL which lead to multiple referer entries from the same domain. but somehow it has no effect... will the only be ignored for new requests and not be applied retrospectively? 

**Example**  
![Screenshot 2020-04-15 at 22 22 24](https://user-images.githubusercontent.com/59607366/79384665-9bc59e00-7f67-11ea-85ba-345eed77fadd.png)
![Screenshot 2020-04-15 at 22 20 41](https://user-images.githubusercontent.com/59607366/79384667-9c5e3480-7f67-11ea-88be-1fbf173e4aa5.png)

**Comment by Maaiins** [comment]
They are only affected when the url is recorded newly, not when the url is already recorded.

**Comment by padams** [comment]
I’m not sure that url param filtering gets applied to referral urls...

**Comment by Maaiins** [comment]
Maybe we can group them based on the domain?

You´ve got some referral view where all referred domains are listed. When you click on an domain you see the specific details. I think i´ts needed to catch the complete query to track where exactly the traffic comes from.

**Comment by znrR** [comment]
that would be great to have per default!

**Comment by padams** [comment]
@Maaiins agreed. As long as you can drill down to the actual referral url that could work. Not sure we are storing the referral domain in the database as it’s own column...

**Comment by padams** [comment]
@Maaiins do you want to create an enhancement issue for this and close this one out?
