### ISSUE TITLE
Calculation of Visit Length

### ISSUE THREAD

**Issue by znrR** [Open-Web-Analytics/Open-Web-Analytics#544]
**Description**  
When people just visit one page (which is often the case at ours because the page is mainly a "one pager") the user visit length is always 0.  Can dom info or tracker php requests be used to calculate visit length. this way we would better see how long a user spends on the site even when not visiting another page..

**Comment by Maaiins** [comment]
@padams The only opinion is see is to add these to the javascript tracker separately and merge this in owa.

**Comment by padams** [comment]
Two ways some people solve this...

1. fire a second trackPageView event when the user is "leaving" the webpage. To do this you wold have to listen for the proper DOM event (onunload, onbeforeunload, etc) and then trigger the tracker cmd. Of course you would have to create a fake URL and suffer with inflated page view counts.

2. Create a timer in javascript and then use Action tracking to record the time on page as the action label. You'd still have to trigger this by listening for the proper DOM event.

**Comment by padams** [comment]
@Maaiins is right. There is no way to do this gracefully. It's an age old problem in the web analytics world and all the tools suffer from it.

One feature that we could build to help a bit would be "scroll depth". We can track how far down the page a user scrolls and then send it to OWA as a Tracked Action....

**Comment by znrR** [comment]
ok will ask an jscript expert for help, thx!

**Comment by padams** [comment]
great. closing.
