### ISSUE TITLE
Make WP menu Items expandable when menu collapsed

### ISSUE THREAD

**Issue by znrR** [Open-Web-Analytics/Open-Web-Analytics#547]
**Description**  
Tiny usability issue: Since OWA needs space i collapse the WP sidebar menu, but then i can't access the submenu of other items. Somehow OWA is the only plugin admin UI that i have installed which prohibits the collapsed sidebar menu items to expand.

Also collapse and uncollapse at the bootom of the WP sidebar menu does not work with OWA.

**Comment by padams** [comment]
That is weird.

**Comment by padams** [comment]
I'm not sure it makes sense to fix as I'm planning on removing the analytics/dashboard from within the Wordpress interface itself. 

Instead there will be a link to open a separate window with OWA running in standalone mode.

It's too much work to build custom interfaces inside WP as there have been a thousand issues like this one.

**Comment by znrR** [comment]
can imagine that this is no fun at all ;-)

**Comment by znrR** [comment]
when you move it to stand alone, maybe move the OWA settings then as a submenu of the WP settings menu and bring back the OWA dashboard link to dashboard submenu..

**Comment by padams** [comment]
People couldn't find it there.... :(

**Comment by padams** [comment]
Closing this.
