### ISSUE TITLE
Improved OWA Dashbaord Layout

### ISSUE THREAD

**Issue by znrR** [Open-Web-Analytics/Open-Web-Analytics#548]
Hey @padams and @Maaiins 

Really a great development OWA for WP took with the recent releases. Love how well it integrates now with WP :-) hopefuly soon it will be available also in the "WP plugin-store". Expect a 5 star rating and rave-review there from me :-)

I have a bunch of (simple) ideas on how to improve the OWA dashboard. Do you want a layout proposal? Its not much but maybe helps... Let me know! Best and thanks for the work!!

**Comment by Maaiins** [comment]
Im not using the Wordpress integration and I  don´t have the possibility to test it. So you have to discuss this with peter ;-)

**Comment by padams** [comment]
Thanks, will be moving to the WP plug-in repo soon...

**Comment by padams** [comment]
Sure maybe make a new ticket for it and attach a proposed layout change there. Thanks!

**Comment by znrR** [comment]
put a few in, this tick can be closed.
