### ISSUE TITLE
Rest API changes broke some details pages

### ISSUE THREAD

**Issue by Maaiins** [Open-Web-Analytics/Open-Web-Analytics#556]
**Affected Version(s)**: master

**PHP Version**: 7.2 FPM

**Webserver**: Apache

**Browser**: Chrome 80

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [x] Standalone

**Description**  
I think your rest api changes broke some details pages links. Seems the replace of the specific detail parameter were not made.

**How to reproduce**  
Try to open: `/index.php?owa_siteId=XXX&owa_period=last_seven_days&owa_do=base.reportPages`
Click on a page path e.g. `/index.php?owa_siteId=XXX&owa_period=last_seven_days&owa_do=base.reportDocument&owa_pageUrl=%25s`

As you can see parameter pageUrl isn´t replaced correctly.

Could also confirm this for:

- base.reportContent
- base.reportGeolocation
- base.reportPageTypes
- base.reportHosts

Stopped testing after that seems to be a general issue

**Comment by padams** [comment]
weird. this isn't happening for me...

**Comment by Maaiins** [comment]
True there is some trouble with my branch, will check this
