### ISSUE TITLE
login panel

### ISSUE THREAD

**Issue by chipwiegand** [Open-Web-Analytics/Open-Web-Analytics#559]
**Description**  
I have built a website and an admin system and am now looking at installing OWA. If I install it I will then have two login screens, I don't want two login screens of course. Can I put my CRUD pages behind your login screen and add a link on my admin page to OWA? And have all of it behind your login panel?

**Example**

**Comment by Maaiins** [comment]
You can write your own integration. See https://github.com/Open-Web-Analytics/Open-Web-Analytics/blob/master/wp_plugin.php

**Comment by Maaiins** [comment]
Or you can write a module for that. See: https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Creating-A-New-Module

Example: https://github.com/Open-Web-Analytics/Open-Web-Analytics/tree/master/modules/hello
