### ISSUE TITLE
Switching domains does not change stats

### ISSUE THREAD

**Issue by macrobber** [Open-Web-Analytics/Open-Web-Analytics#564]
Just pulled master in.  I have several domains I am tracking.  Now, when I switch domains, the dashboard statistics do not update.  In fact, now the domains show ALL data for ALL domains, not the specific domain.  I updated the tables (via the web-page suggesting I update).  I hate to lose the analytics I have currently gathered, but it is no longer filtering by domain.  Any thoughts?

**Comment by macrobber** [comment]
Specifically - the domain stats, top pages, and referrals all point to ALL domains.  It looks like visits is the only thing that is correctly pulling site-specific stats.

**Comment by macrobber** [comment]
Yeah - it's now showing ALL stats for ALL domains regardless of switching to a specific domain.  Including showing OTHER domains stats (page views, visits, even ecom) on all sites.

**Comment by macrobber** [comment]
Tried updating the database (in case the web version didn't work).  Received the following:

`./cli.php cmd=update
./cli.php: line 1: ?php: No such file or directory
./cli.php: line 3: //: Is a directory
./cli.php: line 4: //: Is a directory
./cli.php: line 5: //: Is a directory
./cli.php: line 6: //: Is a directory
./cli.php: line 7: //: Is a directory
./cli.php: line 8: //: Is a directory
./cli.php: line 9: //: Is a directory
./cli.php: line 10: //: Is a directory
./cli.php: line 11: //: Is a directory
./cli.php: line 12: //: Is a directory
./cli.php: line 13: //: Is a directory
./cli.php: line 14: //: Is a directory
./cli.php: line 15: //: Is a directory
./cli.php: line 16: //: Is a directory
./cli.php: line 17: //: Is a directory
./cli.php: line 19: syntax error near unexpected token `'owa_env.php''
./cli.php: line 19: `require_once('owa_env.php');'
`

**Comment by padams** [comment]
When you pulled master in did you run composer?

**Comment by macrobber** [comment]
I just ran composer with the following result:

`composer install
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
`

Sites are still showing all data for all sites.

**Comment by macrobber** [comment]
So, I just ran a completely new install - new database - new folders, completely clean install with nothing to do with the old sites.  It set up with the new sites; however, even on a clean build - if I have more than one site being tracked, the main landing (dashboard) shows individual stats - but when I click on site specific stats (of tracked site) it still shows ALL stats for ALL sites.

**Comment by padams** [comment]
Ok thanks. I’m investigating.

**Comment by macrobber** [comment]
If it helps, it looks like the primary sql statement on the dashboard is working fine.  And the database table for owa_session is showing the correct siteID's being mapped to the right sessions.  I think there may just be an sql issue on sub-sites.  I'm investigating as well and can report here if I find anything as this has rendered my analytics null and void.

**Comment by padams** [comment]
The issue stems from the move to the new REST api. for some reason siteId isn't getting added to the constraint for the getResultSet method. I'm debugging it.

**Comment by padams** [comment]
got it. if you pull master again it should be fixed.

**Comment by macrobber** [comment]
@padams wanted to close the loop here.  Excellent work man.  It's now working as expected.  You rock!

**Comment by macrobber** [comment]
@padams wanted to close the loop here.  Excellent work man.  It's now working as expected.  You rock!

**Comment by padams** [comment]
Excellent. Thanks for catching that.
