### ISSUE TITLE
I cant deal with the API

### ISSUE THREAD

**Issue by L1TWIN** [Open-Web-Analytics/Open-Web-Analytics#565]
I want to make adding sites by API. Wrote a function to add sites. But when I receive a call, I get no answer. Empty results are simply given. Please tell me what I'm doing wrong?

```
function apiOWA($method, $data, $request = 'POST')
{
  $url  = 'http://site.ru/api/base/v1/'.$method.'?owa_apiKey=api_key';

        $ch = curl_init();

        if($request == 'GET')
        {
            curl_setopt($ch, CURLOPT_URL, $url.'&'.urldecode(http_build_query($data)));
        }
        else
        {
            curl_setopt($ch, CURLOPT_URL, $url);

            if($data)
            {
                curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
            }
        }
        curl_setopt($ch, CURLOPT_HEADER, false);   
        curl_setopt($ch, CURLOPT_TIMEOUT, 60);
        #curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        #curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        #curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $request);      
 
        $response    = json_decode(curl_exec($ch), true);
        curl_close($ch);

    return $response;
}

$data = array('domain' => 'test.pro', 'name' => 'test');
print_r(apiOWA('sites', $data));
```

**Comment by L1TWIN** [comment]
It seems all inclusive:
![Screenshot_2](https://user-images.githubusercontent.com/16645444/80334007-58253b00-8869-11ea-809f-7e3bc93cd70b.png)

**Comment by L1TWIN** [comment]
Or maybe someone has a working example of adding a site via curl, please post the code)

**Comment by Maaiins** [comment]
Can you please turn on logging and send us the trace for this specific request?

**Comment by L1TWIN** [comment]
Here's another point. Now replaced 
`$response    = json_decode(curl_exec($ch), true);` 
with
`$response = curl_exec($ch);`

Now the result is displayed, but the entire site is displayed:
![image](https://user-images.githubusercontent.com/16645444/80345154-22408080-8882-11ea-8673-1a5a6421e79a.png)
I tried adding `owa_format=json`

But still does not help. For some reason, the result does not come in json format, CURL gives all the source code of the site

**Comment by L1TWIN** [comment]
In short did. Who needs it, use it)

```
function addSiteOWA($site, $name)
{
    $owa_url = 'https://site.ru'; # owa site
    $api_key = '4d1cd94be3b984eb8fb37513b09aa3fa'; # api key
    
    $url = $owa_url.'/api/?owa_version=v1&owa_do=siteProfile&owa_domain='.$site.'&owa_name='.$name.'&owa_apiKey='.$api_key;

    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_HEADER, false);   
    curl_setopt($ch, CURLOPT_TIMEOUT, 60);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');

    $response    = json_decode(curl_exec($ch), true);
    curl_close($ch);

    return $response;
}
```

**Comment by padams** [comment]
That last curl statement is missing the `owa_module` param. You need a `owa_module=base` in there.

Also the rest api only returns json so no need for a format param.

I’ll look into why you are getting HTML. Likely have to do with the malformed request.

**Comment by padams** [comment]
If you are running code from master the method is `sites` not siteProfile

**Comment by padams** [comment]
Closing. Feel free to re-open if needed.
