### ISSUE TITLE
PHP default timezone gets changed by date_default_timezone_set() function call

### ISSUE THREAD

**Issue by znrR** [Open-Web-Analytics/Open-Web-Analytics#566]
**Affected Version(s)**: 1.6.8

**PHP Version**: 7.3

**Webserver**: Apache

**Browser**: any

- [X] Wordpress 5.4
- [ ] Mediawiki x.y.z
- [ ] Standalone

**Description**  

WP Site health tells me that OW plugin changes timiezone after WordPress loaded by a date_default_timezone_set() function call...

**How to reproduce**  

activate / reactivate plugin and then go to tools > site health

**Possible Solution**  
not setting the timezone but take the one set in WP :)

<img width="821" alt="Screenshot 2020-04-28 at 01 40 22" src="https://user-images.githubusercontent.com/59607366/80431439-bd247380-88f1-11ea-91f5-2a17321abb6b.png">

**Comment by znrR** [comment]
the funny thing is that the time in OWA is correct, so it seems to set it to something correct (but messes up something in WP, since Pub dates of articles are then UTC... wicked!

**Comment by Maaiins** [comment]
A quick fix would be to change the timezone in owa administration to wordpress default.

![image](https://user-images.githubusercontent.com/7676540/80460853-b0753f00-8934-11ea-9dac-65879bc4dabe.png)

**Comment by padams** [comment]
This won’t be a problem after the next release.

**Comment by ctag** [comment]
Hi,

I'm still seeing this error in OWA 1.7.1 on Wordpress 5.8. The quick fix above does not help with a conflict between OWA and The Events Calendar plugin, in which event times are displayed incorrectly while OWA is enabled.
