### ISSUE TITLE
CAN T LOGGIN IN MY LOCAL WEBSITE http://127.0.0.1/

### ISSUE THREAD

**Issue by sed7** [Open-Web-Analytics/Open-Web-Analytics#568]
Hello

the installation is done correctly and create all the tables but unable to connect with the username and password created
it s block in the first page there isn t error

**Comment by Maaiins** [comment]
As you can see in https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting#installation-issues

> OWA uses cookies for tracking and for logging not the the admin interface. Therefor you must run OWA under a fully qualified domain (FQD) such as my.domain.com. Accessing and running OWA under http://localhost or an IP address will create errors.

Add an entry to your hostfile, edit the config and try again please

**Comment by padams** [comment]
Closing feel free to reopen if necessary.

**Comment by nvinayvarma189** [comment]
Hey, I'm facing exactly the same issue. Then I came to know that I can't set up OWA on localhsot with url: 'http://localhost/OWA/'. but I don't own any domain right now and I just want to test all the features. Is there a way to do it? I have Apache, mysql and php setup on my laptop. Does providing the hostname work?
