### ISSUE TITLE
Live web site visitors

### ISSUE THREAD

**Issue by boka003** [Open-Web-Analytics/Open-Web-Analytics#569]
Hello,

We are looking for google analytics alternative.
From time to time, Google Analytics does not display real-time visits correctly. Also, we would love to have another source of visit information, which we can later compare to google analytics.

It is very important for us that the load on the server does not increase.
We use a wordpress platform, and there are a couple of plugins that can help us track visits, but these plugins drastically increase server load.

For this reason, we are looking for a solution that will work the same as google analytics.Which can process data on its server.

Does your platform meet this requirements?
Can you provide real time visitors count?

We have about 2 000 000 page views in a month

Best regards
Boris

**Comment by boka003** [comment]
Sorry, this is quetion for users that allredy use OWA

**Comment by padams** [comment]
OWA is self hosted software. meaning you have to run it on your server which will certainly increase load. You can run it on a separate server but it is not a SaaS service and requires server resources of your own.

**Comment by boka003** [comment]
Thank you for answer.
We will try to run it on separate server.
Do you offer live visitor stats? I am not able to see it on demo?

Is OWA light wait for server resources? We can use it on some VPS?
We have high traffic

**Comment by boka003** [comment]
Hello,

**Comment by padams** [comment]
Just follow the standalone install instructions and then add the javascript tracker code to your webpages.

**Comment by boka003** [comment]
Thank you!

I have install OWA, and it is look perfect.

Is it possible to show visitors in real time with OWA?
- I was try this option at your demo dashboard: http://prntscr.com/s9lz7n but if i click on, nothing happend.
Is more configuration needed to track online visitors?


Is it possible to make OWA more light wait?
I dont need to track visitors clicks, can i remove this line from tracking code> owa_cmds.push(['trackClicks']);  ?


Thank you

**Comment by Maaiins** [comment]
> Is it possible to show visitors in real time with OWA?

As i know there is no such a feature at the moment, you can just view the visitors in dashboard. This shows the most recent.

> Is it possible to make OWA more light wait?

Don´t know how you want to achieve this?

> I dont need to track visitors clicks, can i remove this line from tracking code> owa_cmds.push(['trackClicks']); ?

If you don´t need it just remove it. I use hybrid tracking for my projects, all actions are tracked in PHP only domstream an clicks are track via js. So I just use the parts I need.

**Comment by padams** [comment]
There is no real-time mode per se but If you flip that “live” switch OWA should poll for updates to the dashboard automatically. Just kore that that will add more load to the server...

**Comment by padams** [comment]
Closing. Feel free to re-open if needed.
