### ISSUE TITLE
Heatmap feature is broken: No value passed.

### ISSUE THREAD

**Issue by schmatzler** [Open-Web-Analytics/Open-Web-Analytics#571]
**Before you open an issue:**

- [x ] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x ] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: master
**PHP Version**: 7.4 FPM
**Webserver**: Apache
**Browser**: Chrome 81.0

**Installation Type**
- [x ] Wordpress master

**Description**  
The heatmap function of OWA cannot be used when installed as a WordPress plugin.

When accessing the heatmap, this error gets thrown:

```
Fatal error: Uncaught Exception: No value passed. in /wp-content/plugins/owa/owa_entity.php:422
Stack trace:
#0 /wp-content/plugins/owa/owa_entity.php(405): owa_entity->getByColumn()
#1 /wp-content/plugins/owa/modules/base/overlayLauncher.php(41): owa_entity->load()
#2 /wp-content/plugins/owa/owa_controller.php(280): owa_overlayLauncherController->action()
#3 /wp-content/plugins/owa/owa_coreAPI.php(817): owa_controller->doAction()
#4 /wp-content/plugins/owa/owa_coreAPI.php(804): owa_coreAPI::runController()
#5 /wp-content/plugins/owa/owa_coreAPI.php(1278): owa_coreAPI::performAction()
#6 /wp-content/plugins/owa/owa_caller.php(218): owa_coreAPI::handleRequest()
```

**How to reproduce**  
1. Go to Content -> Entry pages
2. Open up one of the pages and go to Heatmap Overlay
3. The error gets thrown

**Additional context** 
I was not able to test this on the latest stable (1.6.8) because some parts of the software do not load in WordPress (judging from the developer console 1.6.8 tries to access jQuery functions directly which is not working in WordPress).

On the latest master the content sections do load but the error occurs.

**Comment by padams** [comment]
I’m have a fix for this one. Will push it soon.
