### ISSUE TITLE
How can I track only clicks, and avoid all browser/user data?

### ISSUE THREAD

**Issue by rob42** [Open-Web-Analytics/Open-Web-Analytics#572]
**Description**  
I have a use case where I want to track clicks and actions within my webcomponent, which is embedded in a customers web app. This will give myself and the customer a better understanding of the user.

Part of the commercial arrangement specifies that no GDPR or personalized data is to reach my SaaS service. The webcomponent is hosted on their site, and communicates with my SaaS service via a proxy on the customers website, so I see no browser/user/IP data in XHR calls, just a UUID identifier. 

I can embed owa tracker in my webcomponent and make it send to my SaaS service via another proxy on the customers website, but it sends a lot of page/browser/IP/user data, which violates the commercial agreements, and I dont want, as it causes data privacy problems.

How can I configure or modify the owa tracker to send ONLY the click data, avoiding or stripping out all the browser data?

**Comment by Maaiins** [comment]
You cant configure the data sent, but you could modify the tracker.js for your needs an recompile the min version via `/path/to/php cli.php cmd=build`.

**Comment by rob42** [comment]
thx

**Comment by padams** [comment]
I recently added a set of hooks to the tracker so that you can filter event properties before sending. See the Tracker page on the wiki.
