### ISSUE TITLE
I can't see the map

### ISSUE THREAD

**Issue by beepollen** [Open-Web-Analytics/Open-Web-Analytics#574]
**Description**  

Hi!

I've installed OWA v. 1.6.7, as you can see in my blog:

http://www.leituras.casa/blog/stats/

The module "Maxmind GeoIP" is activated, but the geo-location is not working: the stats doesn't show the map and the countries...

Please, is there something I can do?

Thank you,
Alexandre

**Comment by Maaiins** [comment]
Actually there is no map in the owa core. Take a look at my module: https://github.com/Maaiins/Open-Web-Analytics-VisitorMap

Be aware to activate Geolocation lookup in Administration Panel
![image](https://user-images.githubusercontent.com/7676540/80681923-e562cc80-8ac1-11ea-98d0-f018ed3e7e05.png)

Already generated geolocations are not updated, so there will be no updates after activating.

**Comment by beepollen** [comment]
Thank you for your help!

I just installed your module. The map is already showing, but empty ...

Before the installation, I realized that OWA was not showing the location of the visitors, since all of them, in the "country" tab, are written: "not set". But the Geolocation lookup is activated...

Sorry for my English, I'm using Google Translator to answer you ...

Alexandre.

**Comment by Maaiins** [comment]
Yeah when your geolocations are "(not set)" there will be no result on the map. Only the complete geolocations are displayed

**Comment by padams** [comment]
You need ot follow the instructions on the wiki to download the Maxmind database.

https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Maxmind-GeoIP-Module

Without the database there will be no geo-location.

**Comment by padams** [comment]
Closing. Re-open if necessary.
