### ISSUE TITLE
On the page detail page, clicking on Heatmaps generates an internal 500 error. 

### ISSUE THREAD

**Issue by macrobber** [Open-Web-Analytics/Open-Web-Analytics#575]
In looking at the apache logs - it looks like there may be a variable missing.  

` [php7:error] [pid 15018] [client 192.168.1.1:48134] PHP Fatal error:  Uncaught Exception: No value passed. in /var/www/html/pnf/dashboard/owa_entity.php:422\nStack trace:\n#0 /var/www/html/pnf/dashboard/owa_entity.php(405): owa_entity->getByColumn('id', NULL)\n#1 /var/www/html/pnf/dashboard/modules/base/overlayLauncher.php(41): owa_entity->load(NULL)\n#2 /var/www/html/pnf/dashboard/owa_controller.php(280): owa_overlayLauncherController->action()\n#3 /var/www/html/pnf/dashboard/owa_coreAPI.php(817): owa_controller->doAction()\n#4 /var/www/html/pnf/dashboard/owa_coreAPI.php(804): owa_coreAPI::runController(Object(owa_overlayLauncherController))\n#5 /var/www/html/pnf/dashboard/owa_coreAPI.php(1278): owa_coreAPI::performAction('base.overlayLau...', Array)\n#6 /var/www/html/pnf/dashboard/owa_caller.php(218): owa_coreAPI::handleRequest(NULL, 'base.overlayLau...')\n#7 /var/www/html/pnf/dashboard/owa_caller.php(160): owa_caller->handleRequest()\n#8 /var/www/html/ in /var/www/html/pnf/dashboard/owa_entity.php on line 422, referer: http://pnf.com/dashboard/index.php?owa_siteId=98fb47a4edb2ea9d29337450090c2a2b&owa_period=last_seven_days&owa_do=base.reportDocument&owa_pageUrl=https%3A%2F%2Fwww.primenumberfarms.com%2Fabout-us%2F%3FagisPrime%3DagisPrime%26promo%3DjasonChat`

**Comment by macrobber** [comment]
Actually - I only looked in Open tickets - I just found where you are working on a patch.  Feel free to close this.

**Comment by padams** [comment]
ok thanks.
