### ISSUE TITLE
On the page detail page, clicking on Domstream Recordings generates a No API Method error.

### ISSUE THREAD

**Issue by macrobber** [Open-Web-Analytics/Open-Web-Analytics#576]
On the page detail page, clicking on Domstream Recordings generates a No API Method error.  It can be hard to see, but this error is showing up right above the header for the page.   Not seeing any errors in apache, but the engine itself generates this message in the header.

**Comment by macrobber** [comment]
Actually - I only looked in Open tickets - I just found where you are working on a patch.  Feel free to close this.

**Comment by padams** [comment]
ok thanks.
