### ISSUE TITLE
Nudge on API requests.

### ISSUE THREAD

**Issue by macrobber** [Open-Web-Analytics/Open-Web-Analytics#581]
Hey there - sorry for what is likely a stupid question.  I am trying to get the REST API to work with my install.  I am up-to-date on Master.  I've changed the
urls here for security reasons, but maybe you can nudge me in the right direction.

To get a list of users I would hit the following:
http://xxx.com/api/base/v1/users?owa_apiKey=admin-user-api-key

I've also tried:
http://xxx.com/api/?module=base&version=v1&do=sites&owa_apiKey=admin-user-api-key

But get no response and no error logs.

**Comment by padams** [comment]
The first url will only work if you are using Apache as the web server. 

The second use needs “owa_” added to ALL params (ie `owa_version`).

**Comment by macrobber** [comment]
Yeah, I'm using Apache. [Server version: Apache/2.4.29 (Ubuntu)] - So to get all users, I would hit:

http://xxx.com/api/?owa_apiKey=admin-user-api-key&owa_base&owa_version=v1&owa_do=sites

My apache .htaccess file is:

`AddHandler application/x-httpd-php .tpl

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule api/(.*)$ api/index.php?owa_rest_params=$1 [QSA,NC,L]
</IfModule>

`

**Comment by macrobber** [comment]
Or rather:
http://xxx.com/dashboard/api/?owa_apiKey=admin-user-api-key&owa_module=owa_base&owa_version=v1&owa_do=sites

**Comment by macrobber** [comment]
Got it - sorry for the numbscull question.   As always, thanks brother.

**Comment by padams** [comment]
No worries.
