### ISSUE TITLE
server strain / db size

### ISSUE THREAD

**Issue by starchild** [Open-Web-Analytics/Open-Web-Analytics#583]
We're considering making the move away from GA and self hosting OWA.

We're concerned about stress on the server with all the extra db connections, and the ensuing db size and ramifications for backup, storage etc...

Can anyone provide some tips  / thoughts / words of encouragement in this area?

Thank you.

**Comment by Maaiins** [comment]
Some of your points are mentioned in #569.

I made some quick view on my productive 

**About:**
Domstream recordings enabled, takes much space
Running on the same hosting, but separated database
Database size is about 120 MB

13.500 Domstream recordings
6.200 Klicks
8.500 Requests

Before and after usage im made some performance benchmarks, but I cant clearly say owa made it slower. The benchmarks where in the normal fluctuation of server performance.

**Comment by starchild** [comment]
Thanks a lot. I'm setting up a seperate VPS just to host OWA so no mysql performance issues occur on our site.  Fingers crossed this will work.

In terms of design - the whole thing looks pretty ancient.  Are there any plans to reinvigorate the  system to look modern? 

I'm planning to give it an overhaul with some custom css, but would be god to know if this is part of the road map ahead.

Thank you for your time and reply Maalins.

**Comment by padams** [comment]
The code in master contains a decent UI refresh. Will be in the next tagged release along with a lot of other stuff.

**Comment by starchild** [comment]
is there an eta on the next tagged release?

**Comment by padams** [comment]
Likely next two weeks as things look pretty stable right now.
