### ISSUE TITLE
Move more php dependancies into composer

### ISSUE THREAD

**Issue by padams** [Open-Web-Analytics/Open-Web-Analytics#587]
**Description**  

Migration to composer began with PHPMailer. Now let's move the rest of the packages in the /includes/ folder.

This would include:

- [x] PHPMailer
- [x] PEAR/log --> monolog
- [x] httpclient and snoopy -->  guzzle.
- [x] pqp should be removed as there are way better profiling tools available and we dont need this as part of the code base.
- [x] all the daemon and cron parser classes should be removed as well.

**Comment by Maaiins** [comment]
I've got some suggestion: Replace PEAR/Log by https://github.com/Seldaek/monolog it´s widely known in the community

**Comment by padams** [comment]
Going to start work on monolog migration.

**Comment by padams** [comment]
ok. i'm leaving jasmine for now as i think a better approach would be ot work on moving OWA's homegrown asset compilation pipeline to use npm/webpack. I'm going to open a separate ticket of that and close this one.
