### ISSUE TITLE
Can I consider www. and non-www. versions as one?

### ISSUE THREAD

**Issue by 345k** [Open-Web-Analytics/Open-Web-Analytics#590]
**Description**  
On my test installation, it seems to count www.domain.com and domain.com pages separately. Can I merge them together, or make it consider them as same through a setting?

**Example**  
My test page is showing twice on report. One for when I access it through `www.` and one when without `www.`:

![owa-01](https://user-images.githubusercontent.com/57763703/81146171-91605800-8f99-11ea-8c5a-57fe3ba24128.png)

**Comment by Maaiins** [comment]
Actually www and non www domains are considered as separate domains. Technically they are separated domains.

You can read several best practice guides, where it´s recommended to enforce one type.

Even Google Analytics will recognize them as separate domains
