### ISSUE TITLE
Unable to login to admin account after successful installation.  

### ISSUE THREAD

**Issue by nvinayvarma189** [Open-Web-Analytics/Open-Web-Analytics#591]
**Before you open an issue:**

- [ Yes] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [ Yes] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting)

**Affected Version(s)**: 1.6.8

**PHP Version**: 7.2.3 FPM

**Webserver**: Apache

**Browser**: Chrome 81.0

**MYSQL Version**:  8.0

**Installation Type**

I downloaded the packaged version and placed it in my apache server where I can access the files from the link: `http://my-domain.com/owa/`

- [ x] Wordpress x.y.z
- [ x] Mediawiki x.y.z
- [ Yes] Standalone

**Description**  
I'm unable to log in after entering my admin account details (username and password) in `http://my-domain.com/owa/index.php`. It says validation has failed in the logs. I verified that I'm entering the correct password. Also, I can see my admin account user name in owa_user table on mysql.

I get this error: `The form that you completed had some errors`. 

**Below are the steps I performed:**

- Initially, I started with PHP 7.4.6RC1 version and I was getting this error: `Trying to access array offset on value of type bool`

- So I thought this issue was specific to PHP 7.4.6RC1 and I downgraded to PHP 7.2.3. Then I was getting another error, which is: `mysqli_connect(): (HY000/2054): The server requested authentication method unknown to the client`. I solved this after executing [this command](https://github.com/laradock/laradock/issues/1390#issuecomment-419562297)

- After that, I filled up the configuration form (access at: `http://my-domain.com/owa/install.php`) which created a `owa-config.php`.

- Then I entered my website to be tracked and entered a user name and password to create admin account. Following this, all the tables were created and showed up in mysql. Till the previous step the log files were. But after the creation of all tables, I got the below error showing up in the log file:

```
06:51:51 2020-05-07 3928 [debug_log] EHS: Event was handled successfully by all handlers. 
06:51:51 2020-05-07 3928 [debug_log] Assembling view: owa_installView 
06:51:51 2020-05-07 3928 [debug_log] <errorentry>
	<datetime>2020-05-07 06:51:51 (PDT)</datetime>
	<errornum>2</errornum>
	<errormsg>array_key_exists() expects parameter 2 to be array, null given</errormsg>
	<scriptname>C:\Apache24\htdocs\OWA\owa_base.php</scriptname>
	<scriptlinenum>99</scriptlinenum>
</errorentry>
```

but regardless of this error, It took me to the next page saying that **Success! That's It. Installation is Complete.** Along with this, my user name and password were also displayed.

- Now when I went to `http://my-domain.com/owa/index.php` to login to my admin account, I'm getting the `The form that you completed had some errors` message. I see the following error;

```
06:54:47 2020-05-07 3928 [debug_log] About to perform action: base.login 
06:54:47 2020-05-07 3928 [debug_log] Performing Action: owa_loginController 
06:54:47 2020-05-07 3928 [debug_log] Validating user_id with owa_userNameValidation 
06:54:47 2020-05-07 3928 [debug_log] Validation failed. 
06:54:47 2020-05-07 3928 [debug_log] <errorentry>
	<datetime>2020-05-07 06:54:47 (PDT)</datetime>
	<errornum>8</errornum>
	<errormsg>Undefined variable: go</errormsg>
	<scriptname>C:\Apache24\htdocs\OWA\modules\base\login.php</scriptname>
	<scriptlinenum>68</scriptlinenum>
</errorentry>
```

I'm a complete noob in PHP so I'm not sure where to start debugging the code to see why the validation is failing. Can you please help me? Also, please let me know in case I can provide you with anymore details. Thanks.

**Additional context**  
[Logfile](https://pastebin.com/07WiX3eS)

**Comment by padams** [comment]
Are you running under localhost?

**Comment by nvinayvarma189** [comment]
Yes, I initially setup OWA at `htttp://locahost/OWA` but then I came to know that FQDN is required. So I'm using a corporate domain network of the form [Host name].[Domain].[TLD].[Root]. But yeah it is still running under localhost only.

**Comment by padams** [comment]
It might be getting confused about your cookies then. I take it you don’t have any owa_u or owa_p cookies.

Does localhost show as the domain in the browser?

**Comment by nvinayvarma189** [comment]
Regarding the cookies, I don't have any showing up in my chrome. I had to delete some cookies while I was working on some other task. Is that the problem?

yes, both `http://localhost/` and `[Host name].[Domain].[TLD].[Root]` takes me to the apache server.

**Comment by padams** [comment]
Right, but which are you using to access/submit the login form? Localhost?

**Comment by nvinayvarma189** [comment]
No, not the localhost. I'm using the domain while to access/submit the login form.

**Comment by padams** [comment]
Looks like you have spaces in your user name which is illegal. I'll look into why you were allowed to enter that in the first place but if you want ot work around this, I suggest starting a fresh install and this time do not use  " ", ";", "'", "\"", "|", ")", "(" in the user name.
