### ISSUE TITLE
OWA doesn't seem to track even after removing strict mode for mysql

### ISSUE THREAD

**Issue by nvinayvarma189** [Open-Web-Analytics/Open-Web-Analytics#597]
**Description**  
I'm able to successfully install OWA and I pasted the generated tracking code (js) on my homepage on my website. But I see all 0s on my dashboard. I also see that most of the tables in MySQL are empty. They are not getting filled. 

I can't seem to find anything wrong in the log files and I'm not sure where to start debugging this.

[Log file](https://pastebin.com/FG6a0yfj)

**Comment by padams** [comment]
Take a look at the JS Tracker section here:


https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting

If OWA is not recording data you need to first rule out that the tracker is not setup correctly.

**Comment by nvinayvarma189** [comment]
Thanks.

I went through the troubleshooting guide. 

- I can access the `http://domain.com/owa/modules/base/js/owa.tracker-combined-min.js` page from my browser.
- I'm using the correct siteID in the tracking code.
- I see no JS errors related to the tracking code on the console of my webpage.
- The script tag is properly inserted. I can see the script tag at the top of my body tag on my webpage. This is exactly what is being inserted:
```
<script type="text/javascript" async src="http://domain.com/owa/modules/base/js/owa.tracker-combined-min.js"></script>
```
- I also made sure that `send doNotTrack properties` from my chrome browser is turned off.
- Yet I do not see any requests to `log.php` on my OWA server from the network tab of my webpage. 

anything I'm missing?

**Comment by padams** [comment]
Open up the web inspector of your browser and see if the javascript is making any network requests to log.php. Note the http status code and params of the request.

**Comment by nvinayvarma189** [comment]
Yes, I saw the network tab after reloading my webpage and I don't see any requests to `log.php`.

**Comment by padams** [comment]
Then there may be JavaScript errors in the console tab. If the tracker code is added properly it will makes request to log.php. Unless you are using an ad blocker or such.

**Comment by nvinayvarma189** [comment]
There are no errors on my console tabs as well. That is what is confusing me. I was trying to look more into the log file but there is so much in it. 

I see a warning in my console tab though. It says:
```
A cookie associated with a resource at http://my.domain.com/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.
```

Does that indicate any problem with cookies or cache?

**Comment by padams** [comment]
No that’s just a warning. Are you sure you included the javascript properly (ie inside a script tag)?

Which browser are you using? Did you try another browser?

**Comment by padams** [comment]
That’s the issue. You cannot run OWA on localhost. OWA requires cookies to be set and that can only happen under a fully qualified domain name.

Please read the troubleshooting  instructions. It’s point #2:

https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting

**Comment by nvinayvarma189** [comment]
Yeah, but even though I'm running OWA on localhost I'm accessing it via FQDN. So there shouldn't be a cookies issue, right? Also, I can see the owa cookies in my inspector tab of both the OWA server and my webpage as well.

**Comment by padams** [comment]
What is the public url of your tag and what is the url of the page you are tracking in the browser?

**Comment by nvinayvarma189** [comment]
I'm not sure if I can put them here as these pages are public. So I created a paste that expires within 1 day. Thanks.

[Paste Link](https://pastebin.com/sauJjB2J)

**Comment by padams** [comment]
what does your tracking tag look like?

**Comment by nvinayvarma189** [comment]
```
<!-- Start Open Web Analytics Tracker -->
                <script type="text/javascript">
                    //<![CDATA[
                    var owa_baseUrl = 'http://yy192338.code1.emi.company.com/owa/';
                    var owa_cmds = owa_cmds || [];
                    owa_cmds.push(['setDebug', true]);
                    owa_cmds.push(['setSiteId', '6e6e0dfd2b41459f1bb31fdd0733f5fe']);
                    owa_cmds.push(['trackPageView']);
                    owa_cmds.push(['trackClicks']);
                    
                    (function() {
                        var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
                        owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
                        _owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';
                        var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
                    }());
                    //]]>
                    </script>
                    <!-- End Open Web Analytics Code -->
```

**Comment by padams** [comment]
And no console messages at all? strange. which browsers are you using?

**Comment by nvinayvarma189** [comment]
Yeah there are no errors in my console page. I'm using chrome Version 81.0.4044.138

**Comment by padams** [comment]
What about debug msgs or any msgs at all? Is that script block even executing? Is the browser even fetching the owa.tracker.combined.min.js?

**Comment by nvinayvarma189** [comment]
Regarding debug messages, I'm attaching the log file that is created when I refresh the dashboard on OWA server. 

[log file](https://pastebin.com/CAR3pCYU)

The tracking code is definitely executing. I verified by putting console.log() statements and the script tag pointing to `owa.tracker.combined.min.js` with async true is also getting inserted into the top of the body tag of my webpage. 

How to tell if my browser is fetching the `owa.tracker.combined.min.js`?

**Comment by padams** [comment]
You will see s request for it in the network inspector tab...

**Comment by nvinayvarma189** [comment]
This is the script tag that is getting inserted into my body tag:

```
<script type="text/javascript" async src="http://domain.com/owa/modules/base/js/owa.tracker-combined-min.js"></script>
```

yeah right. I dont see any requests going to `owa.tracker.combined.min.js` file in my network tab. I'm not sure what can be the cause of this.

**Comment by padams** [comment]
Literally Domain.com? Or did you redact the actual domain. 

also, do any of the requests in your network tab have 40x or 50x http response codes?

**Comment by nvinayvarma189** [comment]
no, it is not domain.com literally 😅 . I edited the actual domain. All the requests going from my webpage (to different endpoints within my website) return 200. I don't see any 40x or 50x.

**Comment by padams** [comment]
If there are no requests to the owa.tracker.combined.min.js then the issue is with your browser or HTML somewhere. DId you try another browser to see if that works?

**Comment by nvinayvarma189** [comment]
You are right. There seems to be a problem with my chrome. I have to find out what it is. `owa.tracker.combined.min.js` is getting fetched when I open my website in edge browser. Thank you so much.

but I still don't see the data showing up on my dashboard.

- I can see a request to log.php and it is returning 200
- I inserted the correct tracking code
- I removed the cookies and reloaded my webpage. But still can't see the data going into MySQL database and as a result not showing up in my dashboard.

I can see a lot of log statements in the console of my edge browser. I'm attaching it here, I guess that will be helpful.

[console debug](https://pastebin.com/crLEFjMY)

**Comment by nvinayvarma189** [comment]
I see that if I change `owa_baseUrl` from `http"//domain.com/owa/modules/base/js/owa.tracker-combined-min.js` to `http"//local/owa/modules/base/js/owa.tracker-combined-min.js`,  chrome seems to fetch the `owa.tracker-combined-min.js` and I see almost the same debug info as I see in edge browser.

but still, I see 0s in my dashboard

**Comment by padams** [comment]
The base url need to be the url of the OWA instance. Not the tracker.

Make sure you are setting a siteID

**Comment by nvinayvarma189** [comment]
Ohh yes yes. I'm sorry. I meant I changed the `owa_baseUrl` from `http://domain.com/owa/` to `http://local/owa/` and chrome started fetching the `owa.tracker-combined-min.js`. And yes I'm using the correct side ID.

**Comment by padams** [comment]
Were you able to get things working?
