### ISSUE TITLE
can not add sites with REST API

### ISSUE THREAD

**Issue by renkeoO** [Open-Web-Analytics/Open-Web-Analytics#598]
I am using REST API to add sites to track, but failed all the time. And the response JSON is the list of tracked websites.

request url is like this: `http://XXXXXX/api/?owa_apiKey=XXXXXXXX&owa_do=sites&owa_module=base&owa_domain=http://www.foo.com&owa_name=Foo&owa_version=v1`

response json is the list of tracked websites. `{
    "requestId": "1589265484857816323",
    "httpResponse": {
        "status_code": 200
    },
    "error": [],
    "data": {
        "6bb1e54682d331e9908d5779c2fdfca2": {
            "name": "base.site",
            "properties": {
                "id": {
                    "name": null,
                    "value": "87923322",
                    "data_type": "BIGINT",
                    "foreign_key": null,
                    "is_primary_key": true,
                    "auto_increment": false,
                    "is_unique": false,
                    "is_not_null": false,
                    "label": null,
                    "index": null,
                    "default_value": null
                },
                "site_id": {
                    "name": null,
                    "value": "6bb1e54682d331e9908d5779c2fdfca2",
                    "data_type": "VARCHAR(255)",
                    "foreign_key": null,
                    "is_primary_key": false,
                    "auto_increment": false,
                    "is_unique": false,
                    "is_not_null": false,
                    "label": null,
                    "index": null,
                    "default_value": null
                },
                "domain": {
                    "name": null,
                    "value": "http://stats.dynadot.com",
                    "data_type": "VARCHAR(255)",
                    "foreign_key": null,
                    "is_primary_key": false,
                    "auto_increment": false,
                    "is_unique": false,
                    "is_not_null": false,
                    "label": null,
                    "index": null,
                    "default_value": null
                },
                "name": {
                    "name": null,
                    "value": "http://XXXX.com",
                    "data_type": "VARCHAR(255)",
                    "foreign_key": null,
                    "is_primary_key": false,
                    "auto_increment": false,
                    "is_unique": false,
                    "is_not_null": false,
                    "label": null,
                    "index": null,
                    "default_value": null
                },
                "description": {
                    "name": null,
                    "value": "",
                    "data_type": "MEDIUMTEXT",
                    "foreign_key": null,
                    "is_primary_key": false,
                    "auto_increment": false,
                    "is_unique": false,
                    "is_not_null": false,
                    "label": null,
                    "index": null,
                    "default_value": null
                },
                "site_family": {
                    "name": null,
                    "value": "",
                    "data_type": "VARCHAR(255)",
                    "foreign_key": null,
                    "is_primary_key": false,
                    "auto_increment": false,
                    "is_unique": false,
                    "is_not_null": false,
                    "label": null,
                    "index": null,
                    "default_value": null
                },
                "settings": {
                    "name": null,
                    "value": "",
                    "data_type": "BLOB",
                    "foreign_key": null,
                    "is_primary_key": false,
                    "auto_increment": false,
                    "is_unique": false,
                    "is_not_null": false,
                    "label": null,
                    "index": null,
                    "default_value": null
                }
            },
            "_tableProperties": {
                "alias": "site",
                "name": "owa_site",
                "cacheable": true,
                "cache_expiration_period": 604800
            },
            "wasPersisted": true,
            "cache": null
        }
}`

**Comment by renkeoO** [comment]
By the way, the DELETE API is also confusing me.

**Comment by padams** [comment]
Http request method matters. To add sites you need to use a POST request not a GET. To delete a site you need to use a DELETE request.

**Comment by renkeoO** [comment]
Got it. Thank you very much!
