### ISSUE TITLE
DB Type is hard coded into the config entry page template

### ISSUE THREAD

**Issue by padams** [Open-Web-Analytics/Open-Web-Analytics#599]
**Description**  

The `db_type` is hard coded into the config entry page template making it impossible to add another db plugin (i.e. Postgresql in #596 )

**Possible Solution**  

- Allow modules to register db implementation classes.
- Modify config entry page template to loop those values.

**Comment by bernd-wechner** [comment]
Good plan. Postgresql implementation will hinge on it.

**Comment by padams** [comment]
This has now landed in master. To ad a new DB type to the drop down on the install screen just add a name view pair to the `db_supported_types` setting in your config file like so:

```php
$db_types = $this->get('base', 'db_supported_types');
$db_types['postresql'] = 'PostgreSQL' 
$this->set('base', 'db_supported_types', $db_types);
```

Then make sure your db plugin class and file are named properly to correspond with the key added.

**Comment by bernd-wechner** [comment]
Awesome. If you have a spare moment to indulge, provide a quick primer on what get base and set base are doing and why? I'll work it out in studying the code no worries, but I may not get back to it real soon (so many jobs running at once) and if I have a primer in hand it'll help me along.

**Comment by padams** [comment]
`this` is the OWA configuration object. `base` is the module name.

When you get or set a config setting in OWA you must specify the module name of the specific setting that you want to get/set from.

**Comment by padams** [comment]
Actually one more thing....

If you have an existing config file then add this code to that.

If you are starting an install from scratch then add this code to owa-config-dist.php

This won’t be necessary once we merge the postgresql support.
