### ISSUE TITLE
Queue Processing Error

### ISSUE THREAD

**Issue by fearworksmedia** [Open-Web-Analytics/Open-Web-Analytics#6]
I keep getting an error when I process the queue, leaving events unprocessed and the whole system in a bit of a mess:

Fatal error: Call to a member function wasReceived() on a non-object in D:\websites\my-website\owa\modules\base\classes\fileEventQueue.php on line 218

A small number of events seem to be tracked but the vast majority are remaining unprocessed.

I have tried clearing out the "unprocessed" folder, which seems to clear the problem and allow the queue to be processed once again but within a day or two there is a backlog of unprocessed events and once again I start to get the error message above.

**Comment by padams** [comment]
Check to see if OWA has permissions to read the event files. The error you are getting implies that it might now.
