### ISSUE TITLE
Email Tracking

### ISSUE THREAD

**Issue by Sepremex** [Open-Web-Analytics/Open-Web-Analytics#604]
**Description**  
I have download the zipped version, installation, no problem, it even worked on a VirtualHost, I'm using Debian 10...
Can this system be implemented to track email messages? sort of mailchimp analytics?... 
Is there a way to install or implement this system on a Laravel Framework with "composer"?

**Comment by padams** [comment]
Not really and no. The tracker client requires Javascript. You could use the PHP SDK to code up your own tracking code for emails I suppose but that use case isn't something that works out of the box.

Currently OWA can only be installed via git or tarball.

**Comment by Maaiins** [comment]
You could use composers repository feature to accomplish this.
https://getcomposer.org/doc/05-repositories.md

A possible solutions is: Add a campaign link to your mail as you can see here https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Campaign-Tracking

**Comment by padams** [comment]
That’s actually a great idea @Maaiins !!

**Comment by Sepremex** [comment]
@padams, I agree, @Maaiins idea might just do what I want, it does require a bit of work but what doesn't... thank you @Maaiins ...

**Comment by Maaiins** [comment]
As I know mailchimp does it the same way, but the usage is out of the box.

Some smart dev made a way to add tracking automatically. I think you can do it the same way, just parse (https://www.php.net/manual/en/class.domdocument.php) the mail body before sending it. Then automatically append the campaign parameters for your mailshot
