### ISSUE TITLE
Issue with registration of new user.

### ISSUE THREAD

**Issue by StonedAstronaut** [Open-Web-Analytics/Open-Web-Analytics#606]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: 1.6.9

**PHP Version**: 7.3.18 FPM

**Webserver**: nginx/1.18.0

**Browser**:  Firefox 76.0.1

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [x] Standalone

**Description**  

When I add new user nginx error_log got this error, but user was added.

`2020/05/20 13:58:35 [error] 4023#4023: *19776495 FastCGI sent in stderr: "PHP message: PHP Notice:  Array to string conversion in /var/www/owa/owa_lib.php on line 728" while reading response header from upstream, client: MY_CLIENT_IP, server: owa.example.com, request: "POST /index.php?owa_do=base.usersProfile HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "owa.example.com", referrer: "https://owa.example.com/index.php?owa_do=base.usersProfile"`

But new user doesn't receive email with further registration insctructions. When I try  use "Change password for this user" I recieve this error in nginx error_log:

`2020/05/20 14:00:00 [error] 4023#4023: *19776495 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: headline in /var/www/owa/owa_base.php on line 105" while reading response header from upstream, client: MY_CLIENT_IP, server: owa.example.com, request: "POST /index.php?owa_do=base.passwordResetForm HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "owa.example.com", referrer:  "https://owa.example.com/index.php?owa_do=base.passwordResetForm"`

**Comment by padams** [comment]
Fixed in master will go out in the next release. thanks.
