### ISSUE TITLE
owa_session location_id does not appear to be updating

### ISSUE THREAD

**Issue by macrobber** [Open-Web-Analytics/Open-Web-Analytics#608]
Using the latest version from the Master branch, I discovered today that no matter where I hit the tracked site from, I seem to only get a location_id of the same ID.  I had a friend hit the site from the other side of the country, and no new location_id is created.  

This is causing ALL hits to appear to come from the same location.  I have Maxmind GeoIP activated and have the Visitor Map activated.  Looking at the database, I can see all 'hits' being logged to the same location_id in the owa_session table.

**Comment by macrobber** [comment]
Interesting side note - not sure if it's related, but I run several installations and the session_id for these installs is always '259604063'

**Comment by padams** [comment]
Are you saying that for every visit the session id and location are always the same?

**Comment by macrobber** [comment]
Exactly. Both session if and location are always the same. And this is on two different servers in two different locations.

**Comment by padams** [comment]
always the same or you or always the same for all visitors?

**Comment by padams** [comment]
No changes to the maxmind module have been made AFAIK. Did your hosting provider make some changes and put you behind a proxy? Did you start running a cache of some kind to speed up pages?

**Comment by macrobber** [comment]
Same for all visitors. I will see if there is a hidden proxy. But my friend got the tracked site and it showed the same location as well. Very odd.

**Comment by macrobber** [comment]
Also. One collection server is local. One is remote. Just weird that both installs site the same id.

**Comment by padams** [comment]
That’s suggests a proxy of some kind. Maybe a load balancer, etc.

**Comment by padams** [comment]
Closing this as I can’t replicate.
