### ISSUE TITLE
How to integrate OWA with Single Page Applications like ReactJS

### ISSUE THREAD

**Issue by maheshvadada** [Open-Web-Analytics/Open-Web-Analytics#613]
I am using Open-Web-Analytics V1.6.2. Only the first request in my Reactjs Web Application was logged. For every click, it is invoking log.php GET request with `"owa_event_type":"dom.click"` and not tracked in the OWA Dashboard. When I changed the GET request with `"owa_event_type":"base.page_request"`, then it is tracking my request.

Can anyone help me that how can I integrate the Open Web Analytics with my ReactJs Single Page Application???

**Comment by Maaiins** [comment]
Integrate the tracker.js to your application: https://github.com/Open-Web-Analytics/Open-Web-Analytics/blob/master/modules/base/js/owa.tracker-combined-min.js

Then integrate the tracking code to your application and invoke tracking: https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Tracker

**Comment by tagiltsev** [comment]
https://github.com/Open-Web-Analytics/Open-Web-Analytics/issues/318

**Comment by Maaiins** [comment]
I will close this, feel free to reopen
