### ISSUE TITLE
Missing /vendor/autoload.php file?

### ISSUE THREAD

**Issue by fpiraneo** [Open-Web-Analytics/Open-Web-Analytics#614]
**Description**  
After a clean installation of OWA, when accessing the tracked website, server log this error:

`[Tue May 26 17:24:08.953806 2020] [php7:warn] [pid 19860] [client 192.168.20.106:35344] PHP Warning:  require_once(/var/www/Open-Web-Analytics/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/Open-Web-Analytics/modules/base/classes/browscap.php on line 20, referer: https://www.anonicloud.ch/it/
[Tue May 26 17:24:08.953826 2020] [php7:error] [pid 19860] [client 192.168.20.106:35344] PHP Fatal error:  require_once(): Failed opening required '/var/www/Open-Web-Analytics/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/Open-Web-Analytics/modules/base/classes/browscap.php on line 20, referer: https://www.anonicloud.ch/it/`

Obviously nothing is logged on database; on browser `log.php` is correctly accessed by the browser (a 1x1 black dot is downloaded...)

**Comment by padams** [comment]
You need to run `composer install` or install using the “-packaged” tarball.
