### ISSUE TITLE
Is it possible to disable cookies, whilst still logging some stats?

### ISSUE THREAD

**Issue by sumade123** [Open-Web-Analytics/Open-Web-Analytics#615]
Is it possible to disable cookies whilst still logging information on:

- The number of overall visits to the webpage
- The number of times each outbound link was clicked (and the date/time)
- Country of visitors (potentially) 
- Referring domains (potentially)

The top two are most important to me. I am not in this particular case interested in the granularity of visits by individual users.

**Comment by Maaiins** [comment]
As mentioned in #472 you can add `$this->set('base', 'cookie_persistence', false);` to your `owa-config.php`. So PHP tracking will only set session cookies, javascript will not respect this at the moment

**Comment by Maaiins** [comment]
Will close this, feel free to reopen if necessary
