### ISSUE TITLE
mysqli_set_charset() expects parameter 1 to be mysqli, bool given in owa_db_mysql.php

### ISSUE THREAD

**Issue by improvethings** [Open-Web-Analytics/Open-Web-Analytics#617]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: 1.6.9

**PHP Version**:  /etc/php/7.3/apache2

**Webserver**: Apache2

**Browser**: Firefox 68.8

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [x ] Standalone

**Description**  

**How to reproduce**  

During install on https://example.com/owa/install.php?owa_action=base.installCheckEnv
I enter the MariaDB  10.3 auth details, which work on the command line. The apache2 logs flood with this: 

[Fri May 29 15:26:35.463643 2020] [php7:warn] [pid 26555] [client my.ip:50602] PHP Warning:  mysqli_set_charset() expects parameter 1 to be mysqli, bool given in /var/www/owa/plugins/db/owa_db_mysql.php on line 124, referer: https://example.com/owa/install.php?owa_action=base.installCheckEnv
[Fri May 29 15:26:35.464177 2020] [php7:warn] [pid 26555] [client my.ip:50602] PHP Warning:  mysqli_connect(): (HY000/1045): Access denied for user 'owa_user '@'localhost' (using password: YES) in /var/www/owa/plugins/db/owa_db_mysql.php on line 118, referer: https://example.com/owa/install.php?owa_action=base.installCheckEnv

**Possible Solution**  

**Additional context**

**Comment by Maaiins** [comment]
Your user isn't allowed to logon: Access denied for user 'owa_user '@'localhost'
