### ISSUE TITLE
User management & roles > not seeing sites in list for analyst, viewer, everyone...

### ISSUE THREAD

**Issue by maxxo** [Open-Web-Analytics/Open-Web-Analytics#619]
Successful installation via Softalicous and tracking sites traffic. As admin I can add new sites and view all sites traffic stats in the list of sites. However, I created a new user and tried giving analyst, viewer and everyone. For all 3 of these other user roles, the list of sites I created as admin was not showing up. So what is the purpose of these other roles? Is it a bug. It seems so.

**Comment by Maaiins** [comment]
Have you assigned the user to the project? Click on Reporting in the Navigation bar, then on edit profile, scroll down to "Allowed Users" select the specific users and save the settings
