### ISSUE TITLE
Error in login error text

### ISSUE THREAD

**Issue by angerangel** [Open-Web-Analytics/Open-Web-Analytics#621]
Hello,
if you type the wrong user and password appears:

`<B>Login Failed</B>. Your user name or password did not match.`

As you see the tags are not intepreted as showed as plain text

**Comment by Maaiins** [comment]
Which owa version are you using?

**Comment by padams** [comment]
Not happening for me...

**Comment by angerangel** [comment]
Version 1.6.4,  here a screenshot:
[![owabug.png](https://i.postimg.cc/ZRrqcvjJ/owabug.png)](https://postimg.cc/ftRZWL6P)
