### ISSUE TITLE
API Cors

### ISSUE THREAD

**Issue by macrobber** [Open-Web-Analytics/Open-Web-Analytics#622]
Hey guys, just checking in to see if there was any intention to add cors to the RESTApi interface - I see that some work has been done on it - but I'm not sure where it is at in the development cycle.  Cross-platform functionality would be huge for a project I'm working on - but I also understand higher-priority issues you may be facing.

**Comment by Maaiins** [comment]
Actually there's a pr at the moment, but not implemented yet
