### ISSUE TITLE
after install i got error , all files not found

### ISSUE THREAD

**Issue by juraganfilmmovie** [Open-Web-Analytics/Open-Web-Analytics#623]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting)

**Affected Version(s)**: 1.6.9

**PHP Version**: 7.4 FPM

**Webserver**: Nginx

**Browser**: 83.0.4103.61

**Installation Type**

- [ ] Standalone 1.6.9

i installed OWA on my server , after add js tracking there is nothing on my panel , generated error_log  and got this error :

2020/06/10 19:24:53 [error] 5859#5859: *8374 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(/home/u.mystats.host/htdocs/owa/vendor/autoload.php): failed to open stream: No such file or directory in /home/u.mystats.host/htdocs/owa/modules/base/classes/browscap.php on line 20PHP message: PHP Fatal error:  require_once(): Failed opening required '/home/u.mystats.host/htdocs/owa/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/u.mystats.host/htdocs/owa/modules/base/classes/browscap.php on line 20" while reading upstream, client: 110.159.143.24, server: u.mystats.host, 

please help all files not found
**Additional context**

**Comment by padams** [comment]
Closing as this is not happening in recent releases.
