### ISSUE TITLE
Can't find any option to remove older statistics

### ISSUE THREAD

**Issue by Dubova** [Open-Web-Analytics/Open-Web-Analytics#624]
Hi,  I have used the OWA for some time  and like it very much. Recently I noticed that the database is already quite large (about 300Mb), I'd like to know how the older statistics can be removed to lessen the size of the database?

Thank you

**Comment by Maaiins** [comment]
At the moment there is no implementation for this. I think @padams did this for the demo, maybe he can share a solution

**Comment by padams** [comment]
Is your size issue driven by the owa_domstream table? There's no CLI right now to drop old data. But there is a ticket to add MySQL partitioning to the fact tables #497 . That would make dropping ranges of data trivial.

**Comment by Dubova** [comment]
Thank you very much for your replies!

**Comment by padams** [comment]
Ok. We will address this with partitions in the other ticket..
