### ISSUE TITLE
Cannot log in to wp-admin after installation

### ISSUE THREAD

**Issue by ohadmanor** [Open-Web-Analytics/Open-Web-Analytics#625]
**Before you open an issue:**

- [Yes] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [Yes ] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting)

**Affected Version(s)**: 1.6.9

**PHP Version**: 7.x FPM

**Webserver**: Apache2

**Browser**: Chrome 80.x.x

**Installation Type** WordPress

- [Yes] Wordpress 5.4.2
- [ ] Mediawiki x.y.z
- [No ] Standalone

**Description**  
After installation I can not log in to the WP-Admin any more.
if I go to the <Website>/wp-content/plugins/owa I can see that the plugin works and monitor, it is possibale to see the site and it works fine.

other users can log in to the wp-admin (not admin users)

I clean the cache, cockies and site setting still - I can't log in.

Thanks

**Additional context**

**Comment by padams** [comment]
Is this an update from an earlier version of OWA by any chance?

**Comment by ohadmanor** [comment]
No, it is clean one.

does the user in the OWA need to be identical to the one in the wordpress?

thanks
Ohad

**Comment by padams** [comment]
Yes. However there is a patch to fix that in master. It will go out in the next release.

**Comment by ohadmanor** [comment]
Ok,

that was the problem

thnaks

Ohad
