### ISSUE TITLE
files and folders permissions

### ISSUE THREAD

**Issue by carlostkd** [Open-Web-Analytics/Open-Web-Analytics#629]
Hi
on the installation guidelines the link for check files and folders permissions is broken.
someone can make the link up again, or share the correct permissions for folders and files? there is a lot of files accessible from Web browser, would be great too if we can hide the dashboard login page since the don't have proper configuration against brute force.
thanks
cheers

**Comment by Maaiins** [comment]
For the permission take a look at: https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Required-permissions

This is currently an open issue, i will close this one and will add a new feature request
