### ISSUE TITLE
Newbie questions

### ISSUE THREAD

**Issue by eniorankedbrain** [Open-Web-Analytics/Open-Web-Analytics#630]
Hello!

I'm kinda new in this website development/analytics world as i used to work with infrastructure/admin only, and I have some doubts.

I have read the framework overview, but I'm not 100% sure of how it works :)

Right now I have OWA installed and working really fine for an internal site, but my questions are:

1) Is it possible to track a site that's currently not being hosted under my word press?

2) Does the PHP $owa->placeHelperPageTags(); provides the same result as Javascript owa_cmds.push(['trackDomStream']); ?

3) Seems like it works just fine if I add the PHP tracking code in just one of the pages (like index.php). But how does it works with the java tracker? Can I add it to a PHP site?

4) Is there any way to "hide" the tracker lines from a page?

Thanks!

**Comment by padams** [comment]
Yes. You can add the javascript tacker to any website. 

`$owa->placeHelperPageTags(); ` is deprecated. so avoid using that but it basically outputs the tracking tag which you can grab from the site's Profile page in the admin interface.

Just add the javascript tracker to the source of your web page. There is no way to hide the javascript tracker as it's in the source code of your webpage as opposed to the PHP tracker which is only shown in server-side php code.
