### ISSUE TITLE
Protect OWA files against direct access

### ISSUE THREAD

**Issue by Maaiins** [Open-Web-Analytics/Open-Web-Analytics#631]
**Description**  
There is a lot of files accessible from Web browser, would be great too if we can hide the dashboard login page since the don't have proper configuration against brute force. Ref: #629 

@carlostkd if you like you can support the development by adding an pull request to the repository

**Comment by padams** [comment]
There’s a feature for this already. 😉

Just add the endpoint you want to restrict to the `disabledEndpoints'` setting array.

Or you can set the `disableAllEndpoints` setting to true.

**Comment by Maaiins** [comment]
Ok will close this
