### ISSUE TITLE
PHP Mailer

### ISSUE THREAD

**Issue by nataprawira** [Open-Web-Analytics/Open-Web-Analytics#632]
need your help,sir ... 
my hosting company blocked sendmail / php mail to send out email from php scripts.
and, I saw the PHPMailer on OWA's folder, but, where to set the SMTP configuration info? 

appreciated your answer. thank you.

**Comment by padams** [comment]
You can configure OWA to use PHPMailer's SMTP capabilities. Here are the config values that need to set in your owa-config.php file:

```
$this->set( 'base', 'mailer-host', 'your host');   
$this->set( 'base', 'mailer-port', 'your port');   
$this->set( 'base', 'mailer-use-smtp', true);   
$this->set( 'base', 'mailer-smtpAuth', true);   
$this->set( 'base', 'mailer-username', 'your user name');   
$this->set( 'base', 'mailer-password', 'your password');   
```
