### ISSUE TITLE
Does OWA features like heatmap, domstream work on chrome? 

### ISSUE THREAD

**Issue by saivamshi** [Open-Web-Analytics/Open-Web-Analytics#635]
**Description**  
They are working for me on firefox but looks like chrome is not tracking these events. Please let me know if there is any specific configuration for chrome that I need to do. Also, I could not see any logs for domstream and heatmap on chrome.

**Comment by Maaiins** [comment]
In my opinion heatmap and domstream tracking is working in working fine. Are there any errors in the javascript console?

**Comment by padams** [comment]
Closing.
