### ISSUE TITLE
OWA cookie rejected by browser since it's not secure

### ISSUE THREAD

**Issue by sinchinpark** [Open-Web-Analytics/Open-Web-Analytics#636]
**Description**  

CONTEXT: track multiple websites with different domains and different servers with a single instance of OWA

Since OWA set SameSite attribute to None, (most) modern browsers would reject OWA's cookie for lack of the 'Secure' attribute.
[Reject insecure SameSite cookies](https://www.chromestatus.com/feature/5633521622188032)

Of-course this situation only happened if you host OWA on A domain, and want to a website with B domain.

**Example**  

I installed OWA on this domain (standalone - PHP 7.3.1 - HTTPS):
[sinch.ir](https://sinch.ir/tryst/owa)

and want to track [my podcast website](https://melomaniac.ir)
but nothing logged. 

Chrome console warning indicates:
A cookie associated with a resource at http://sinch.ir/ was set with `SameSite=None` but without `Secure`. A future release of Chrome will only deliver cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.

How could I set 'Secure' attribute for OWA's cookie?

**Comment by padams** [comment]
Chrome is not rejecting those cookie yet as far as I can tell. 

You are correct about the warning but there is another ticket to to fix that.

You may have another issue going on. 

If you are seeing any owa_ cookies being set? Does tracking work in another browser like Firefox?

**Comment by padams** [comment]
Closing. Fel fre to reopen if need be.

**Comment by Vivida1** [comment]
Since [Chromium has reverted back to align their plans with Firefox to enforce SameSite Cookie policy](https://blog.chromium.org/2020/05/resuming-samesite-cookie-changes-in-july.html), this issue should be tackled.
This issue can easily and quickly [be fixed and tested in Firefox](https://hacks.mozilla.org/2020/08/changes-to-samesite-cookie-behavior/) before this policy enforcement goes live.

**Comment by jcubic** [comment]
@padams where is this issue? I can't find it. It wound be nice to link related issues with hash tag.
