### ISSUE TITLE
OWA doesnt work

### ISSUE THREAD

**Issue by saivamshi** [Open-Web-Analytics/Open-Web-Analytics#638]
**Description**  

I have configured owa on xampp, I could see when I open my website which is tracked, I could see http get and post logs on xampp apache server, but nothing is written into mysql db, I made sure that strict mode is disabled.

Is there any other configuration I am missing? Please help.

I am seeing following logs in debug mode:
13:17:48 2020-06-30 7104 [debug_log] User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0 
13:17:48 2020-06-30 7104 [debug_log] <errorentry>
	<datetime>2020-06-30 13:17:48 (PDT)</datetime>
	<errornum>2</errornum>
	<errormsg>require_once(C:\xampp\htdocs\OWA/vendor/autoload.php): failed to open stream: No such file or directory</errormsg>
	<scriptname>C:\xampp\htdocs\OWA\modules\base\classes\browscap.php</scriptname>
	<scriptlinenum>20</scriptlinenum>
</errorentry>

**Comment by Maaiins** [comment]
It looks like you checked out the project without using composer install.

Please use the packaged release (owa_1.6.9_packaged.tar) https://github.com/Open-Web-Analytics/Open-Web-Analytics/releases/tag/1.6.9 

Or follow these steps: https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installing-from-Github

**Comment by saivamshi** [comment]
Thanks I got it fixed.

I am facing a new issue, tracking works but UI is completely messed up. I could see following msg in logs:
![image](https://user-images.githubusercontent.com/11319208/87055305-6379d880-c1c1-11ea-8b79-5d45f6146f48.png)


2020/07/09 14:45:44 [error] 14#14: *471 FastCGI sent in stderr: "PHP message: PHP Notice:  Use of undefined constant OWA_ERROR_HANDLER - assumed 'OWA_ERROR_HANDLER' in /var/www/html/modules/base/templates/config_dom.tpl on line 15" while reading response header from upstream, client: 192.168.25.252, server: _, request: "GET /index.php?owa_do=base.sites HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "<domain name>"

Can Anyone help me

**Comment by padams** [comment]
Please read the troubleshooting guide if you want help. you cannot run OWA on localhost.
