### ISSUE TITLE
http site not detected in Open Web analytic

### ISSUE THREAD

**Issue by yeshwanthmn** [Open-Web-Analytics/Open-Web-Analytics#641]
When we add a new site with http no site not detected but over https site is detected why

**Comment by Maaiins** [comment]
Please view the browser console for any errors

**Comment by yeshwanthmn** [comment]
![owa](https://user-images.githubusercontent.com/32923471/86894187-5d7feb00-c120-11ea-838d-59b748aecb94.png)

i attached my issue while adding a site in owa  in the screen shoot i am getting 403

**Comment by yeshwanthmn** [comment]
![owa](https://user-images.githubusercontent.com/32923471/86894384-9ddf6900-c120-11ea-9cd0-358d1d8b2222.png)

i am getting 403 while adding a new site in owa admin panel. i dont find any errors in browser console.help me out with this issue

**Comment by Maaiins** [comment]
Please read the troubleshoot guide https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting#installation-issues

You can not run owa under localhost, will close this issue
