### ISSUE TITLE
Maxmind DB file could is not present

### ISSUE THREAD

**Issue by ForkInSpace** [Open-Web-Analytics/Open-Web-Analytics#643]
- I read the troubleshooting guide in the wiki and the generated error log is writing out those lines after what appears to be a successful installation: 
```02:39:46 2020-07-03 22100 [debug_log] Module hello activated 
02:39:46 2020-07-03 22100 [debug_log] Installation complete. 
02:41:26 2020-07-03 22100 [debug_log] Configuration changes saved to database. 
13:07:00 2020-07-03 22100 [debug_log] Maxmind DB file could is not present at: C:\MAMP\htdocs\owa/owa-data/maxmind/ 
13:13:19 2020-07-03 22100 [debug_log] Maxmind DB file could is not present at: C:\MAMP\htdocs\owa/owa-data/maxmind/ 
13:30:31 2020-07-03 22100 [debug_log] Maxmind DB file could is not present at: C:\MAMP\htdocs\owa/owa-data/maxmind/ 
13:30:50 2020-07-03 22100 [debug_log] Maxmind DB file could is not present at: C:\MAMP\htdocs\owa/owa-data/maxmind/
```
**Affected Version(s)**: 1.6.9 (Latest)

**PHP Version**: 7.2.31

**Webserver**: Apache/Nginx

**Browser**: Chrome 83.0.4103.97

*Note:* I'm using MAMP on windows 10 to spin up the server, not a PHP/MYSQL savvy person but my project requires open source analytics and for better or the worse I opted for OWA. 
Now I'm not sure if the errors are specific to Maxmind (I've found that there is a package that needs to be downloaded and included in the owa-config.php if country info isn't set but i'm not sure that could fix the issues I'm having, see below), OWA, or MAMP. 

**Installation Type**

- Standalone

**Description**  
*Can't access heatmaps* - once I click on the link it redirects me to the localhost which is obviously empty, meaning there are no .php files, the owa folder is there.
*Routing tracking* - All pages views are under `/` and I'm guessing that's because of the SPA nature of the app. However, not sure how the tracker should be loaded in the routes so every route is tracked correctly and separately. (maybe someone has example of OWA implementation on Angular/React? )
Can't see the actual 'Visit Length for users' - amount of time a user spends on a certain page per session.
All visits to the app (which is me on my own local machine) are classified as new visits instead of 1 repeat visitor sessions (Maybe something wrong with the FE app setup of owa tracker? 

**Possible solution**
Maybe some of the issues I'm having could be avoided as long as I setup the OWA on an actual server instead of doing this on a localhost?

**Comment by ForkInSpace** [comment]
UPDATE: I've added the `C:\MAMP\htdocs\owa\owa-data\maxmind\GeoLite2-City.mmdb` file, haveupdated the owa-config.php file with the following `define( 'OWA_MAXMIND_DATA_DIR', 'http://localhost/owa/owa-data/maxmind/');` and have restarted the server.
The geo location doesn't seem to work.

**Comment by Maaiins** [comment]
You have to specify the local path of the file eg. `C:\MAMP\htdocs\owa/owa-data/maxmind/`

**Comment by padams** [comment]
You need a filesystem path. not a url.

**Comment by padams** [comment]
Closing. feel free to reopen if need be.

**Comment by ForkInSpace** [comment]
> You have to specify the local path of the file eg. `C:\MAMP\htdocs\owa/owa-data/maxmind/`

yeah, I've done that. I'm guessing the cause of the issue is also the fact that I've been running this locally not on a proper domain. 

Actually, I've been trying to setup owa on red hat's openShift that's using kubernetes. Turns out it's easier said than done. 
I reckon no one's tried that on openShift so far? 

Anyways, will have more time tmr to debug and try few things and will see how it goes. 

Thanks for the responses.

**Comment by vishaldhiman** [comment]
Hi,
   Did you figure out how to get Routing tracking  to work with React. Maybe an example? Should we add owa code script at the top of the page level (index.html) or should we add this script in react. Also since react has single page design, how can we force react page clicks to recognize as separate pages?

**Comment by itsbinay** [comment]
Hi, wanted to know if there are any updates on how to get the Routing tracking to work with React? Any example on how open web analytics could be integrated with Single Page Applications such as React?
