### ISSUE TITLE
geo location not displayed

### ISSUE THREAD

**Issue by sderrick** [Open-Web-Analytics/Open-Web-Analytics#644]
Centos7, apache 2.4, php 7.3.19

copied maxmind data base to /var/www/html/owa/owa-data/maxmind

-rwxr-xr-x 1 apache apache 63135716 Jul  6 10:25 GeoLite2-City.mmdb
-rwxr-xr-x 1 apache apache  3830286 Jul  6 10:25 GeoLite2-Country.mmdb

activated maxmand module in settings/modules

enabled logging 

the only entries that reference maxmind after I click on Geo-location 

grep -i maxmind *

    errors_5a02668d195def6a297d09eba51882e0.txt:10:50:14 2020-07-06 58010 [debug_log] maxmind_geoip Schema version is 1 
    errors_5a02668d195def6a297d09eba51882e0.txt:10:50:14 2020-07-06 58010 [debug_log] maxmind_geoip Required Schema version is 1 
    errors_5a02668d195def6a297d09eba51882e0.txt:10:50:14 2020-07-06 58010 [debug_log] Filter: owa_maxmind::getLocation. Value passed: Array
    errors_5a02668d195def6a297d09eba51882e0.txt:10:50:14 2020-07-06 58010 [debug_log] Filter: owa_maxmind::getLocation. Value returned: Array
    errors_5a02668d195def6a297d09eba51882e0.txt:10:50:14 2020-07-06 58010 [debug_log] geolocation filtered by owa_maxmind::getLocation. 
    errors_5a02668d195def6a297d09eba51882e0.txt:    [6] => maxmind_geoip
    errors_5a02668d195def6a297d09eba51882e0.txt:10:50:22 2020-07-06 57739 [debug_log] maxmind_geoip Schema version is 1 
    errors_5a02668d195def6a297d09eba51882e0.txt:10:50:22 2020-07-06 57739 [debug_log] maxmind_geoip Required Schema version is 1 
    errors_5a02668d195def6a297d09eba51882e0.txt:    [6] => maxmind_geoip
    errors_5a02668d195def6a297d09eba51882e0.txt:    [6] => maxmind_geoip
    errors_5a02668d195def6a297d09eba51882e0.txt:10:50:22 2020-07-06 58011 [debug_log] maxmind_geoip Schema version is 1 
    errors_5a02668d195def6a297d09eba51882e0.txt:10:50:22 2020-07-06 58011 [debug_log] maxmind_geoip Required Schema version is 1 
    errors_5a02668d195def6a297d09eba51882e0.txt:10:50:22 2020-07-06 57739 [debug_log] maxmind_geoip Schema version is 1 
    errors_5a02668d195def6a297d09eba51882e0.txt:10:50:22 2020-07-06 57739 [debug_log] maxmind_geoip Required Schema version is 1 
 
the Geo-location page looks like this

![geo](https://user-images.githubusercontent.com/729724/86607358-0205ff80-bf5e-11ea-80e8-1aca9708a027.png)

**Comment by padams** [comment]
Maxmind doesn’t catch every IP. Try from another IP address.

**Comment by sderrick** [comment]
there are 4 unique visitors????

**Comment by sderrick** [comment]
I used my phone over the data connection, loaded 3 different pages but don;t see any activity anywhere?

Its a Andriod phone, I tried firefox and chrome.

**Comment by padams** [comment]
Check your errors log file to see what happening.

**Comment by padams** [comment]
Assuming you figured this out. re-open if need be.
