### ISSUE TITLE
OWA_ERROR_HANDLER development not logging

### ISSUE THREAD

**Issue by jsundquist** [Open-Web-Analytics/Open-Web-Analytics#645]
**Description**  
I'm currently trying to debug why when I call `/logs.php` to log events they are not showing up within OWA. When I dive into debugging the issue I noticed that no files are showing up within `owa-data/logs`. I have verified that the logs directory is set to 755, I have also tried modifing `error_log_file` to be a static file. Did not seem to help.

**Example**

**Comment by Maaiins** [comment]
you have to uncomment the following in `owa-config.php`

```
define('OWA_ERROR_HANDLER', 'development');
define('OWA_LOG_PHP_ERRORS', true);
```

**Comment by padams** [comment]
Closing.
