### ISSUE TITLE
Can't view heatmaps on localhost

### ISSUE THREAD

**Issue by ForkInSpace** [Open-Web-Analytics/Open-Web-Analytics#646]
**Description**  
I'm running server thru MAMP, locally, and when I click on **Heatmap Overlay** it gives `Not found` error (see the pic below)
Is this behavior natural while running a local server ?
How could I view heatmaps locally ? 

**NOTE:** i'm running an angular 9 app locally at a default port 4200 and the server is using port 3307.

Any help would be much appreciated. 

P.S same goes for domstreams, I can view the recordings' list but when I try to click the `play` icon, it redirects me to a route which doesn't exist, giving the similar `Not found` error, 

**Example**  
![not-found](https://user-images.githubusercontent.com/11965778/86794125-cf025f80-c074-11ea-9631-4dbc418f1bc6.PNG)

**Comment by padams** [comment]
OWA requires a fully qualified domain name to set cookies properly.

**Comment by ForkInSpace** [comment]
Thanks @padams, will try to configure owa on a server today. Will update this issue with my findings

**Comment by padams** [comment]
Ok. please close this issue if you can.
