### ISSUE TITLE
owa tracker blocked by client 

### ISSUE THREAD

**Issue by yeshwanthmn** [Open-Web-Analytics/Open-Web-Analytics#647]
i am getting following error in browser console window. error blocked by client help me with this issue . i have attached image below 
![owaclientError](https://user-images.githubusercontent.com/32923471/87051232-f005b480-c21c-11ea-8a2d-e845b8053254.png)

**Comment by padams** [comment]
Looks like an ad blocker.

**Comment by yeshwanthmn** [comment]
Can you tell me how to solve it help me out

**Comment by padams** [comment]
Turn off you ad blocker or browser settings. This isn't an OWA as far as I can tell so I'm closing the issue.
