### ISSUE TITLE
API Access Issue

### ISSUE THREAD

**Issue by kumar-harshvardhan** [Open-Web-Analytics/Open-Web-Analytics#648]
I tried to refer the example of "https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Data-Access-API" for API access but it was not working,  then i have modified the code like

include_once("owa_env.php");
include_once(OWA_BASE_DIR."/owa_php.php");

$params = array('request_method' => "GET",
		'module'        => "base",
                'version'       => "v1",
                'do'            => "reports",
                'metrics'       => "visitDuration,bounces,repeatVisitors,newVisitors,visits,pageViews",
                'dimensions'    => "date,browserType",
		'constraints'   => "browserType=Firefox 3.5",
                'startDate'     => "20100312",
                'endDate'       => "20100331",
                'sort'          => "date-,browserType",
                'limit'         => 10,
                'siteId'        => "siteid");				
$result_set = owa_coreAPI::executeApiCommand($params);

it was giving blank page because of below line 

$result_set = owa_coreAPI::executeApiCommand($params); 
if i comment this line then it is able to print any test data like echo "test"; which is written below this line.

Can anyone help me to fix this issue?

Regards
Harsh

**Comment by padams** [comment]
Please read the troubleshooting guide and repost with the required info.

**Comment by Maaiins** [comment]
Closing this issue due inactivity
