### ISSUE TITLE
Two questions regarding excluding sub folders and what are page types?

### ISSUE THREAD

**Issue by sderrick** [Open-Web-Analytics/Open-Web-Analytics#650]
How do I exclude pages that are in sub folders.  We have multiple testing subfolders that I don't want to process

If my web site base folder is   /var/www/html

And I want to exclude  /var/www/html/test

Also what is a "page type"?  It is listed many columns and all of mine say "not set", can I exclude that column?

thanks

**Comment by sderrick** [comment]
Seems like a simple thing to exclude subfolders?  Have searched the Faq for naught!

**Comment by padams** [comment]
You control what is tracked. If you don't want to track a sub folder then do not call trackPageView or even initiate the tracker on those pages.

**Comment by padams** [comment]
Page Type is a dimension used to group or roll up page stats in reporting. Similar to the concept of a tag or category.

**Comment by sderrick** [comment]
Our website is not static, it is built by a service from xml files every day.   Content Editors also can build individual pages to test them, these pages are in specific subfolders. the editors don't have control over the js code that is  executed.  So the owa js code is going to be executed but the web page is in a specific subfolder that the public can;t get to easily, it is of course accessible as the editor needs to see it to verfiy all is well before the page is marked as publish, which will cause it to appear in the /html folder.
So I need a way to catch the call in owa to filter out specific subfolders?? 
makes sense?

**Comment by sderrick** [comment]
Disregard the above OK, I will filter from the client side...
