### ISSUE TITLE
Nothing is recorded?

### ISSUE THREAD

**Issue by Vindojeens** [Open-Web-Analytics/Open-Web-Analytics#651]
Hey there,
I have a question (maybe a stupid one).

The problem is, I just setup Open Web Analytics 1.6.9 and everything works fine.
All the tables are created, the interface works fine, all settings can be changed, saved and edited. I created a user, setup a site, got the code, put it where it belongs. No errors.

The only problem is, nothing is recorded.
The code snippet sits in the same place as google analytics (which is recording correctly).

What can be the problem?
Someone have an idea?

Thanks a lot.

The tables in mysql are created but empty, except for:

owa_site
owa_site_user
owa_user

Those do contain the date of my user account and the site projects i created.
All other tables are there, but empty.

This is what the error log looks like:

03:32:23 2020-07-12 31450 [debug_log] Starting installation of module: base 
03:32:23 2020-07-12 31450 [debug_log] owa_request Table Created. 
03:32:23 2020-07-12 31450 [debug_log] owa_session Table Created. 
03:32:23 2020-07-12 31450 [debug_log] owa_document Table Created. 
03:32:23 2020-07-12 31450 [debug_log] owa_feed_request Table Created. 
03:32:23 2020-07-12 31450 [debug_log] owa_click Table Created. 
03:32:23 2020-07-12 31450 [debug_log] owa_ua Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_referer Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_site Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_visitor Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_host Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_exit Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_os Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_impression Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_configuration Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_user Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_domstream Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_action_fact Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_search_term_dim Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_ad_dim Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_source_dim Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_campaign_dim Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_location_dim Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_commerce_transaction_fact Table Created. 
03:32:24 2020-07-12 31450 [debug_log] owa_commerce_line_item_fact Table Created. 
03:32:25 2020-07-12 31450 [debug_log] owa_queue_item Table Created. 
03:32:25 2020-07-12 31450 [debug_log] owa_site_user Table Created. 
03:32:25 2020-07-12 31450 [debug_log] Post install proceadure was a success. 
03:32:25 2020-07-12 31450 [debug_log] Module base activated 
03:32:25 2020-07-12 31450 [debug_log] Installation complete. 
03:32:25 2020-07-12 31450 [debug_log] Checking for existence of default site. 
03:32:25 2020-07-12 31450 [debug_log] Created default site. 
03:32:25 2020-07-12 31450 [debug_log] Install Complete Flag added to configuration 
03:34:32 2020-07-12 31341 [debug_log] Configuration changes saved to database. 
12:36:58 2020-07-12 31610 [debug_log] Configuration changes saved to database. 
12:42:11 2020-07-12 769 [debug_log] Cache Flushed 
12:42:16 2020-07-12 855 [debug_log] Configuration changes saved to database.

**Comment by Vindojeens** [comment]
I've enabled advanced error logging (like suggested in the troubleshooting guide)
and it seems every visitor generates this error:


12-Jul-2020 14:49:44 Europe/Berlin] PHP Fatal error:  require_once(): Failed opening required '/var/www/aspolo/aspolo.ua/stats/vendor/autoload.php' (include_path='./:/var/www/aspolo:/') in /var/www/aspolo/aspolo.ua/stats/modules/base/classes/browscap.php on line 20
14:49:45 2020-07-12 3129 [debug_log] check for http host 
14:49:45 2020-07-12 3129 [debug_log] Setting cookie domain to .aspolo.ua 
14:49:45 2020-07-12 3129 [debug_log] *** Starting Open Web Analytics v1.6.9. Running under PHP v7.0.33-29+0~20200514.36+debian8~1.gbp126f6f (Linux) *** 
14:49:45 2020-07-12 3129 [debug_log] Request URL:GET /stats/log.php?owa_timestamp=1594558177&owa_event_type=dom.click&owa_dom_element_name=%28not+set%29&owa_dom_element_value=%28not+set%29&owa_dom_element_id=cboxNext&owa_dom_element_class=%28not+set%29&owa_dom_element_tag=A&owa_page_url=https%3A%2F%2Faspolo.ua%2Fmuzhskie-krossovki-new-balance-1500-zelenye-s-chernym-i-krasnym-89115&owa_page_width=360&owa_page_height=579&owa_dom_element_text=next&owa_target_url=&owa_dom_element_x=261&owa_dom_element_y=580&owa_click_x=301&owa_click_y=619&owa_visitor_id=1594558097260389940&owa_fsts=1594558097&owa_dsfs=0&owa_last_req=1594558129&owa_session_id=1594558097536390234&owa_nps=0&owa_dsps=0&owa_medium=direct&owa_source=%28none%29&owa_search_terms=%28none%29&owa_session_referer=%28none%29&owa_site_id=e3e884f1d1260ee72a69cee5798839d3&owa_HTTP_REFERER=https%3A%2F%2Fwww.google.com%2F&owa_page_title=%D0%9A%D1%83%D0%BF%D0%B8%D1%82%D1%8C+%D0%BC%D1%83%D0%B6%D1%81%D0%BA%D0%B8%D0%B5+%D0%BA%D1%80%D0%BE%D1%81%D1%81%D0%BE%D0%B2%D0%BA%D0%B8+New+Balance+1500+%D0%B7%D0%B5%D0%BB%D0%B5%D0%BD%D1%8B%D0%B5+%D1%81+%D1%87%D0%B5%D1%80%D0%BD%D1%8B%D0%BC+%D0%B8+%D0%BA%D1%80%D0%B0%D1%81%D0%BD%D1%8B%D0%BC+%7C+ASPOLO& 
14:49:45 2020-07-12 3129 [debug_log] User Agent: Mozilla/5.0 (Linux; Android 9; MHA-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Mobile Safari/537.36 
14:49:45 2020-07-12 3129 [debug_log] Host: aspolo.ua 
14:49:45 2020-07-12 3129 [debug_log] check cache file: /var/www/aspolo/aspolo.ua/stats/owa-data/caches/1/owa_configuration/fafe1b60c24107ccd8f4562213e44849.php 
14:49:45 2020-07-12 3129 [debug_log] CACHE HIT (Cold) - Retrieved Object from Cache File - Collection: owa_configuration, id: fafe1b60c24107ccd8f4562213e44849 
14:49:45 2020-07-12 3129 [debug_log] Caller configuration overrides applied. 
14:49:45 2020-07-12 3129 [debug_log] request container says params are: 
14:49:45 2020-07-12 3129 [debug_log] Array

It seems it tries to open a "/vendor/autoload.php" file which is missing. I checked, there is no such directory or file in the archive I've downloaded.

**Comment by xiaoblack163** [comment]
How did you solve it

**Comment by xiaoblack163** [comment]
How did you solve it @Vindojeens
