### ISSUE TITLE
Can't view heatmaps on a qualified domain

### ISSUE THREAD

**Issue by ForkInSpace** [Open-Web-Analytics/Open-Web-Analytics#652]
**Description**  
So, this is basically a follow-up to the previous issue I created where I was struggling with viewing heatmaps on a local server. ( [issue #646](https://github.com/Open-Web-Analytics/Open-Web-Analytics/issues/646) )

So, i've finally managed to install and run this on openShift. Just as before I'm able to track the clicks and pageViews. 
I.e I can see requests go out to log.php... on every dom click. There are no errors in the console and I can view the tracking info in the OWA dashboard, so far so good.

Alternatively, I have Cash Control ON in the configuration which is by default is on and under the **Default page** i'm pointing to` http://staging.domain.se/index.html`

The only possible fix I can think of is setting a cookie domain because I'm guessing the `staging` is omited and cookies are stored at `domain.se` ? [Tracker wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Tracker)

Do you think this could be a possible fix or do you have a better idea of what I'm missing? @padams 

**Example**  
Clicking on Heatmap Overlay opens a new tab (Yes I've tried Firefox, gives me the same error)
`stage.domain.se/help#owa_overlay.eyJzaXRl..`

/help is a page on the website that I'm tracking but seems like the associated cookie isn't found.

**Error:**
![image](https://user-images.githubusercontent.com/11965778/87415599-f78adc00-c5d5-11ea-899a-9d32b22f3e0a.png)

**Comment by ForkInSpace** [comment]
UPDATE: was able to view heatmaps but only on the `/` route. 
For every trackPageView I've also been passing a redirect route so I could see in OWA which route the user is on. So atm it seems like I can either track users based on page routes or I can just have the aggregate page views under `/` and be able to see heatmaps.

**Comment by padams** [comment]
This doh did like it has to do with the way you have configured the tracker. Can you post your JavaScript tracker code?

**Comment by ForkInSpace** [comment]
had to get rid of the snippet from angular app that enables hash use in the url `{ useHash: true }`. Seems to work now better. However, there are times that you click on the heatmap overlay and it doesn't render at all even after waiting 10-30 seconds. 
Feels a bit unpredictable. 

How could I get click data through the API btw? Thinking to try out different tools for mapping the clicks but couldn't seem to find such API method? @padams

**Comment by padams** [comment]
https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/REST-API

**Comment by padams** [comment]
Hard to tell if you don't post the request url... 😉

**Comment by padams** [comment]
closing.
