### ISSUE TITLE
Rest api i am not getting any response but status code is 200

### ISSUE THREAD

**Issue by yeshwanthmn** [Open-Web-Analytics/Open-Web-Analytics#653]
![owa rest](https://user-images.githubusercontent.com/32923471/87654433-8897b980-c774-11ea-8fbd-cbed83bfb63a.png)

i tried for multiple rest api but getting response as 200 without no results

https://domain name here/owa/api/?owa_apiKey=apikey/api/base/v1/users (/api/?module=base&version=v1&do=sites)
 
i have also attached a image for following issue

**Comment by padams** [comment]
Your request url is wrong. You have copied the documentation literally.

Everything inside the parentheses is the alternate syntax in case you are not using Apache or URL rewriting. 

Just remove everything after /users.

**Comment by yeshwanthmn** [comment]
i tried it  but getting response as 200 without no results
https://doma
![owa rest](https://user-images.githubusercontent.com/32923471/87695716-77b76a00-c7ad-11ea-9809-7160c67dee16.png)
in name here/owa/api/?owa_apiKey=apikey/api/base/v1/users

**Comment by yeshwanthmn** [comment]
i tried for multiple rest api but getting response as 200 without no results

https://domain name here/owa/api/?owa_apiKey=apikey/api/base/v1/users

![owa rest](https://user-images.githubusercontent.com/32923471/87695831-9d447380-c7ad-11ea-9663-0a80b83ee777.png)

**Comment by padams** [comment]
I think your url is still wrong. Please see the document in again.
