### ISSUE TITLE
Add a one-click deploy button to the wiki

### ISSUE THREAD

**Issue by jakemalachowski** [Open-Web-Analytics/Open-Web-Analytics#654]
**Description**  
Hello. I'm an engineer at [Render](https://render.com/). We recently set up a one-click deployment button, as well as a guide, that allows your users to get up and running with an Open Web Analytics server and MySQL database in just a couple minutes. We are looking to make it as seamless as possible to use your software. I was hoping you would be willing to add us as an option for deploying in your docs.

**Example**  
Link to our docs: https://render.com/docs/deploy-open-web-analytics
Button that can be added to deploy in one click: 

[![Deploy to Render](https://render.com/images/deploy-to-render-button.svg)](https://render.com/deploy?repo=https://github.com/render-examples/open-web-analytics)

**Comment by padams** [comment]
thanks will add a mention to this in the wiki.
