### ISSUE TITLE
Custom Module Question

### ISSUE THREAD

**Issue by qqqcccjjj** [Open-Web-Analytics/Open-Web-Analytics#655]
**Description**  

I turned on click tracking and I am interested in making a custom report that displays the number of clicks each link receives (each link on the site has a unique id attribute). I read through the documentation, including the hello module code. After reading the documentation, it looks like making a module that generates the custom report is the proper solution. The documentation is a bit sparse as far as creating new reports, but the hello module provides a good starting point.

I have already ran some SQL queries to pull the data I need for the report out of the database, but I'm unsure how to convert this to a report within the OWA framework. In fact, I haven't seen any SQL in the report source code that I looked through.

**Question**
Can somebody point me in the right direction? Is there another other source with more in depth documentation?

**Comment by padams** [comment]
Use the REST API to pull the data. Also there is already a dom clicks report that breaks down clicks by dom id. It's linked off the page detail report for each url. its `do=base.reportDomClick` and `reportDomClicks.php` if you need an example of how to create a report.

**Comment by padams** [comment]
Closing.
