### ISSUE TITLE
My Dashboard doesn't work

### ISSUE THREAD

**Issue by valeriodistefano** [Open-Web-Analytics/Open-Web-Analytics#656]
It seems to be searching datas but no datas appears on the page and the system is going on searching and searching.
![Annotazione 2020-07-18 164532](https://user-images.githubusercontent.com/68471908/87855061-224a9c80-c916-11ea-8bca-3b5fcf00eaba.png)

**Comment by Maaiins** [comment]
Please open the browser console and take a look into the network tab, to get an idea what´s wrong

**Comment by valeriodistefano** [comment]
Thank you so much Maaiins! It works well and regulary with Mozilla Firefox. NOT with Google Chrome.

**Comment by Maaiins** [comment]
Please Open the Developer Tools and take a Look into the Network/Console tab, to verify the Problem

**Comment by alanjayg99** [comment]
I have a similar problem. OWA was working fine for a while, and then it suddenly had a problem display reporting. Latest visits displays fine in console, but everything else just shows a waiting gif. When I go to the network tab in the browser, I found a number of actions indicating CORS missing allow origin for OWA.reporting-combined-min.js:502 (xhr). I had a message under errors:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://webbusconnect.com/owa/modules/base/templates/filter_period.tpl. (Reason: CORS request did not succeed).
I understand what the problem is, but I don't know how to fix it. Can anyome help?
Alan Goldstein
AJG@WebBusConnect.com

**Comment by padams** [comment]
are you using a fully qualified domain name?

Is the public url in your config file the same at the URL of the server where OWA is installed and the same as the URL where you access OWA via the browser?

**Comment by alanjayg99** [comment]
Hi Peter,
 
Thank you for for responding.
 
We tried to put the following entry in .htaccess
Access-Control-Allow-Methods: *
Is there an owa config file where the url would go? I can't seem to find one. Is it possible it is missing?
 
OWA was working, and suddenly it stopped, so it might make sense that the config file got clobbered.
 
Alan

-----Original Message-----

**Comment by padams** [comment]
`owa-config.php` is the config file. should be in the directory that OWA was installed.

**Comment by alanjayg99** [comment]
Hi Peter,
 
I found owa-config.php, and it has your name in it, copyright 2006.
 
There doesn't seem to be anything about access methods. Can I just add an entry like this in the file:
 
Access-Control-Allow-Methods: http:www.webbusconnect.com
 
Thank you,
Alan 


-----Original Message-----

**Comment by padams** [comment]
Alan, I think you need to look at the installation instructions again.

Access-control statements are not needed to run OWA.

The config file should define a `public url` that needs to include the same domain and protocol as the one that you are using to access your server via the browser.

**Comment by alanjayg99** [comment]
Hi Peter,
 
I tried several variations of syntax in owa-config.php. The only ones that didn't throw an error were:
Access-Control-Allow-Methods *
Access-Control-Allow-Origin *
 
[I don't plan on keeping *, but it is the easiest for testing, and ensures that I am referencing the correct domain.
 
However, this didn't solve the problem. It's still unable to load the reporting data.
 
I know this should be something simple, but CORS is outside my area of expertise. I just want owa reporting to start working again.
 
Alan

-----Original Message-----

**Comment by alanjayg99** [comment]
Hi Peter,
 
I'm sorry to be such a pest, but I cannot get OWA to report. It was working fine, and one day it stopped working, without any apparent cause. When I go to Network in my browser, it shows a whole bunch of errors:
CORS Missing Allow Origin, mostly on api.php and one on filter_period.tpl
 
The config file has this declaration:
define('OWA_PUBLIC_URL', 'http://webbusconnect.com/owa/');
 
I have error messages like:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at [ http://webbusconnect.com/owa/api.php?owa_siteId=e3e5acb68b21c390fedc7fe50023fddc&owa_period=last_seven_days&owa_do=getResultSet&owa_metrics=visits,uniqueVisitors,pageViews,bounceRate,pagesPerVisit,visitDuration&owa_dimensions=date&owa_sort=date&owa_format=json ]( http://webbusconnect.com/owa/api.php?owa_siteId=e3e5acb68b21c390fedc7fe50023fddc&owa_period=last_seven_days&owa_do=getResultSet&owa_metrics=visits,uniqueVisitors,pageViews,bounceRate,pagesPerVisit,visitDuration&owa_dimensions=date&owa_sort=date&owa_format=json ). (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
 
and
 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at [ http://webbusconnect.com/owa/modules/base/templates/filter_period.tpl ]( http://webbusconnect.com/owa/modules/base/templates/filter_period.tpl ). (Reason: CORS request did not succeed).
 
I can't figure out why these requests are being blocked. Any idea what the problem might be?
 
Alan
 
 


-----Original Message-----

**Comment by alanjayg99** [comment]
Hi Peter,
 
Never mind, I got it to work. I changed the url to
[ http://www.webbusconnect.com/owa/ ]( http://www.webbusconnect.com/owa/ ) [added 'www']
 
Thank you for taking the time to respond to my requests.
 
Alan


-----Original Message-----

**Comment by padams** [comment]
No worries. Which browser was throwing the errors?

**Comment by alanjayg99** [comment]
I was looking at the rror messages in Firefox. But the application didn't work in any browser. Now it does.


-----Original Message-----
