### ISSUE TITLE
Another Domain Addes: not visible

### ISSUE THREAD

**Issue by valeriodistefano** [Open-Web-Analytics/Open-Web-Analytics#657]
I have added the website https://www.valeriodistefano.com on my OWA account but it is not visible by accessing.
![Annotazione 2020-07-18 165138](https://user-images.githubusercontent.com/68471908/87855274-68ecc680-c917-11ea-9402-695040c10315.png)

**Comment by padams** [comment]
Not sure what you mean by "not visible by accessing". Feel free to re-open with more information.
