### ISSUE TITLE
owa_template question

### ISSUE THREAD

**Issue by qqqcccjjj** [Open-Web-Analytics/Open-Web-Analytics#659]
Thanks to a previous answer, I am in the process of attempting to write a custom module. I am seeing an error that I'm not sure how to resolve. I was able to use the hello module to make a skeleton module that was properly activated. I also made a report.php within the custom module that contains (stripped down):

<pre>
class owa_reportCustomModuleView extends owa_view {
    function render() {
          $this->body->set_template('templaefile.php');
    }
}
</pre>

But when I click on the report link, I see the following error in the log file:

<pre>
templatefile.php not found in any template directory
</pre>

The error comes up because OWA is looking in the ...modules/base/templates directory and not ...modules/customModule/templates.

Looking in owa_template.php, I see that the search paths are set in the __construct function:

<pre>
if(!empty($caller_params['module'])):
            $this->_setTemplateDir($module);
        else:
            $this->_setTemplateDir('base');
        endif;
</pre>

The result of _setTemplateDir is

module_local_template_dir - /var/www/wordpress/wp-content/plugins/owa/modules/base/templates/local/
theme_template_dir - /var/www/wordpress/wp-content/plugins/owa/themes//
module_template_dir - /var/www/wordpress/wp-content/plugins/owa/modules/base/templates/

**Question**
It looks like my code is not properly setting the module name and the owa_template construct function is not being called with the module or any parameters. So, default, it is set to search in base. Where should I set the module name and parameters so owa_template can find the template file? Also, in set_template I added

<pre>
 if (file_exists($file)):
                $this->file = $file;
</pre>

to the top of the if elseif stack to check if a file given with an absolute path exists. Perhaps that my be useful.

**Comment by padams** [comment]
looks like you might not have actually created a new module but rather just a class inside the base module... See the Hello World Module for an example.
