### ISSUE TITLE
Opt-in to tracking cookies

### ISSUE THREAD

**Issue by williamsthr** [Open-Web-Analytics/Open-Web-Analytics#661]
I use the PHP Tracking Method and do not with to use the Javascript method.
Is it possible to specify whether tracking cookies are set via the PHP method, so I can capture opt-in from users to remain GDPR compliant?

Thanks

**Comment by padams** [comment]
That is something you can do by wrapping the OWA javascript tag in a php conditional. If opt-in cookie present... then add OWA cmds... etc.
