### ISSUE TITLE
Can I delete rows in owa_document database

### ISSUE THREAD

**Issue by sderrick** [Open-Web-Analytics/Open-Web-Analytics#662]
When I started using owa I was inadvertently collecting data on pages I don;t want data collected on.

I now block collection of data on these sub folders, html/owa being one of them.

I would like to delete the rows in the owa_document table that refer to these pages I incorrectly collected.

Would that cause a problem?

thanks, 

Scott

**Comment by eniorankedbrain** [comment]
@sderrick as I was using the PHP tracking code, it was not capturing the page name correctly, so once I changed to the JS code I had to wipe the document table to it start working. It takes some time to refresh (probably depending on cookie settings), but I have not faced any problem.

**Comment by sderrick** [comment]
I'm not asking about a full wipe of the document table.  I'm asking about deleting specific rows.  

Wish there was an answer....

**Comment by padams** [comment]
Is the id of the rows are not referenced by events in the fact tables then you can delete them.

**Comment by sderrick** [comment]
OK! I will check.  If they are referenced do I need to also delete the rows in the "fact" tables with those id's?

many thanks, scott

**Comment by padams** [comment]
I think you want to delete from the fact tables (request and session) though. Not the owa_document dimension table.

**Comment by sderrick** [comment]
The items won't show up if there aren't any matching entries by ID in the fact table?

**Comment by padams** [comment]
Old unused rows in a dimension table generally don't effect anything. If you want to get rid of data then delete from the fact tables.

Doing the opposite will cause joins to fail when calculating stats because the facts will still be there but the dimensions will not...

**Comment by padams** [comment]
They will not. All of the database queries use the fact tables as the base table and then join to dimension tables to get more data about its rows. 

If there is no fact then a tracking event never happened. 

What is tricky about deleting rows selectively is that you would need to delete from both the request fact table and the session fact table. 

Requests contain session ids. If you delete all the requests but then not the related session things will go a bit sideways. So be sure you delete the related sessions first then the requests or else you will lose track of the session_id. 🙁

You might be better off deleting from both fact tables by date. Ie facts that occurred before a particular yyyymmdd. That's a cleaner approach IMHO but both will work.

**Comment by sderrick** [comment]
OK, many thanks, I'll post the results.  ;-)

**Comment by padams** [comment]
Closing.
