### ISSUE TITLE
How can I track downloads with OWA?

### ISSUE THREAD

**Issue by valeriodistefano** [Open-Web-Analytics/Open-Web-Analytics#665]
I need to track downloaded files from my websites.

What can I do? I don't find any documentation about this theme in the wiki.

Can someone help me?

**Comment by brizido** [comment]
Hi - you can use "Action Tracking" to do so (https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Action-Tracking).

For example:
`OWATracker.trackAction('Downloads', 'Music Download',  'File 1');`

**Comment by padams** [comment]
Closing.
