### ISSUE TITLE
API Configuration

### ISSUE THREAD

**Issue by kumar-harshvardhan** [Open-Web-Analytics/Open-Web-Analytics#666]
**Description**  
I want to use the REST API to get the data, but the example you have provided is not working.

**Example**  

I have included the code which is mentioned on the portal inside /owa/api/index.php

$params = array('request_method' => "GET",
				'module'        => "base",
                'version'       => "v1",
                'do'            => "reports",
                'metrics'       => "visitDuration,bounces,repeatVisitors,newVisitors,visits,pageViews",
                'dimensions'    => "date,browserType",
				'constraints'   => "browserType=Firefox 3.5",
                'startDate'     => "20100312",
                'endDate'       => "20100331",
                'sort'          => "date-,browserType",
                'limit'         => 10,
                'siteId'        => "site id");				
$result_set = owa_coreAPI::executeApiCommand($params);

But not getting any result. can anybody help me to solve the issue and steps to use the REST API using PHP script. The example which is given by you is not sufficient.

**Comment by padams** [comment]
This is not an enhancement, If you are having problems wit the API, you need to turn on development logging (see the troubleshooting guide) and pinpoint the query that is not returning expected results or any errors you find. It is impossible to help without that as no one can see what's in your database.

Thats said `'siteId' => "site id"` is an obvious error. You need a proper siteId for any query to work.
