### ISSUE TITLE
Error 403 returned on a new install and no data returned

### ISSUE THREAD

**Issue by rogereab** [Open-Web-Analytics/Open-Web-Analytics#668]
**Description**  

Have just changed service hosting to Web Host UK and have done a clean install of Open Web Analytics 1.6.9 in a subdirectory. 
I have created the profiles required and inserted the tracking code as supplied in each profile and on each site the server is returning an error code 403 as viewed in the console.
I have read and double checked the permissions of OWA as in the wiki documentation but still have the problem.
Could this be a server issue in some way? The literature states that it is: Wordpress hosting accelerated by powerful LiteSpeed webserver, HTTP/3, PHP-FPM and OpCache Caching.

Any comments or help appreciated

Roger B

**Comment by emmsdan** [comment]
@rogereab Am having the same issue, please, how did you resolve this.

**Comment by padams** [comment]
Impossible to tell without seeing request headers and error.log. See the troubleshooting guide for how to debug this.
