### ISSUE TITLE
Open web analytics fails to show heatmap and domstreams

### ISSUE THREAD

**Issue by saivamshi-dobbali** [Open-Web-Analytics/Open-Web-Analytics#669]
Dashboard shows all the other statistics, but when it comes to heatmap and domstream, when I click open new tab keeps on reloading, even in fire fox, I could see following error :
Some issue with cookie, can any one please help me, I have deployed owa on Kubernetes as docker image.

Uncaught SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 188 of the JSON data
    decodeCookieValue https://Mydomain/modules/base/js/owa.tracker-combined-min.js:89
    checkForOverlaySession https://Mydomain/modules/base/js/owa.tracker-combined-min.js:157
    tracker https://Mydomain/modules/base/js/owa.tracker-combined-min.js:148
    push https://Mydomain/modules/base/js/owa.tracker-combined-min.js:142
    process https://Mydomain/modules/base/js/owa.tracker-combined-min.js:146
    <anonymous> https://Mydomain/modules/base/js/owa.tracker-combined-min.js:247
    <anonymous> https://Mydomain/modules/base/js/owa.tracker-combined-min.js:247
owa.tracker-combined-min.js:89:145

**Comment by padams** [comment]
Not a generalizable bug as far a I can tell. did you ever get this to work? If so feel free to re-open with more info.
