### ISSUE TITLE
Redistribute OWA under MIT license

### ISSUE THREAD

**Issue by vishaldhiman** [Open-Web-Analytics/Open-Web-Analytics#670]
My organization would really like to use OWA & maybe contribute to it, but GPLv2's copyleft requirements are very stringent and basically would mean we would need to make our entire product open source. Is there any plans to change OWA to distribute it under MIT license?

PS: This is what reactjs & other tools are also doing

**Comment by padams** [comment]
No plans but are you redistributing the source code of your product or is the product SaaS?

**Comment by vishaldhiman** [comment]
Hi,
  No we are not redistributing the source code of the product. I work for
Vertica (https://www.vertica.com/ - which is owned by Microfocus). Vertica
is a database & it's official tool called management console is used to
manage vertica databases. It is a webapp which users install on their own
servers (typically on-prem or on cloud). For analytics, I'd really like to
use OWA but microfocus has very strict requirements for GPLv2 and advises
against dynamic linking (For ex, using <script> tag to include the owa.js).
However, if OWA was distributed under MIT license we would be ok and would
be able to use OWA.

I suppose MIT license will increase OWA's adoption as GPLv2 license is
restrictive so I think you might an increase in adoption of OWA.

Sincerely,
Vishal

**Comment by padams** [comment]
Seems overly aggressive to me. If you are not modifying the owa.tracker.js library and are just including it in a web page and are using published interfaces, then you should be good. Hard to see how you are creating a derivative work by doing that.

**Comment by vishaldhiman** [comment]
Hi Peter,
  Is there any way I can get a few examples of companies who are using OWA
in a commercial setting?

Vishal

**Comment by vishaldhiman** [comment]
Hi Peter,
   I spoke to my legal & compliance team and they said if there is any
previous versions of OWA distributed under either "LGPL" or "GPL with
classpath exception" then we can use it. Does such a version for owa exist?
Any chance you'd be willing to do this on your side?

Sincerely,
Vishal
413-281-3508

**Comment by padams** [comment]
I'm going to re-license the tracker under a BSD license now.

**Comment by vishaldhiman** [comment]
That would be great. I'll keep an eye out for it. I am sure this will be a
great addition to us.

Sincerely,
Vishal

**Comment by padams** [comment]
It's in master now so i'll close this.
