### ISSUE TITLE
Log in does not work anymore

### ISSUE THREAD

**Issue by mstamboo** [Open-Web-Analytics/Open-Web-Analytics#674]
HELP Please!  
The log in worked fine.  (For open web analytics)   
Now it won't work anymore. 
After I type the  Username and password, nothing happens. 

I do have the correct username and password!

**Comment by eniorankedbrain** [comment]
I'm having the same problem with Chrome, even clearing the cache/cookies and incognito doesn't work. Works fine in the other browsers.

**Comment by mstamboo** [comment]
Thanks!  I tried that and yes, I was in!    (in another browser)

How is it possible?  Any idea?




Citeren eniorankedbrain <notifications@github.com>:

**Comment by psdantonio** [comment]
Fairly certain this has to do with a recent cookie security update in Chrome. If you look at the login request, you can see the browser blocks two 'Set-Cookies' and the console displays the following message:

> A cookie associated with a resource at [DOMAIN] was set with `SameSite=None` but without `Secure`. It has been blocked, as Chrome now only delivers cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.

**Comment by eniorankedbrain** [comment]
> Change to strict... WHERE can you do that? Citeren eniorankedbrain <notifications@github.com>:
> […](#)
> > Fairly certain this has to do with a recent cookie security update > in Chrome. If you look at the login request, you can see the > browser blocks two 'Set-Cookies' and the console displays the > following message: > > > A cookie associated with a resource at [DOMAIN] was set with > `SameSite=None` but without `Secure`. It has been blocked, as > Chrome now only delivers cookies marked `SameSite=None` if they are > also marked `Secure`. You can review cookies in developer tools > under Application>Storage>Cookies and see more details at > https://www.chromestatus.com/feature/5633521622188032. > > You can work around this either by upgrading your cookies to > 'Secure' which will require sending them over HTTPS or by changing > 'SameSite' to 'Strict'. Either of those changes will need to be > done in the saveCredentials() function within owa_auth.php. For an > immediate workaround in Chrome, you can also just set the cookies > yourself, grabbing the key/values from the response after > attempting to login. Awesome, changing to strict worked, thanks a lot! -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#674 (comment)](https://github.com/Open-Web-Analytics/Open-Web-Analytics/issues/674#issuecomment-678485944)

As psdantonio indicated, in the saveCredentials() function within owa_auth.php. Need to change it from SameSite=None to SameSite=Strict, I guess it's in 4 different lines.

**Comment by mstamboo** [comment]
I am sorry, I am bad at this.

I see the two cookies. owa-s  and owa-v

But I have no following message about....



Citeren eniorankedbrain <notifications@github.com>:

**Comment by padams** [comment]
This is fixed in master. will go out in the next release.

**Comment by padams** [comment]
fixed in v1.7.0

**Comment by mstamboo** [comment]
Great that it is fixed. 
But how do I go further? 
I download the ...tar or the ... zip    and where do I put it on my site?

**Comment by mstamboo** [comment]
thanks.
