### ISSUE TITLE
tacking data is not showing

### ISSUE THREAD

**Issue by kathula** [Open-Web-Analytics/Open-Web-Analytics#675]
<head>

<script type='text/javascript'>
//<![CDATA[
var owa_baseUrl = 'https://www.analytics.cloud88.org/';
var owa_cmds = owa_cmds || [];
owa_cmds.push(['setSiteId', 'fbf1cceab5df742b2562b438968bdc71']);
owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);

(function() {
    var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
    owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
    _owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';
    var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
}());
//]]>
</script>

using 1.6.9 version. I am not able to get data, I placed tracking code in the head section, google analytics code is working, this code is placed in blogger website. please help me out.

**Comment by ovidem** [comment]
I'm having the same issue! Same version, installed on my hosted server. I put my Javascript code in the footer before the closing body tag. I'm running the latest version of PHP, database appears to be working, file permissions are in place.

**Comment by ifacta** [comment]
Same problem here. 1.6.9 installed on a hosted server.I tried to install JS code on html head and just before closig body tag... No reporting... but the whole admin interface works fine.

**Comment by padams** [comment]
Please read the troubleshooting guide before filing an issue like this. No one can help if you do not provide any debug info.

**Comment by djedi** [comment]
I'm having the same issues on a brand new install. I have this error in my error log:
```text
14:28:35 2020-09-04 8098 [debug_log] <errorentry>
        <datetime>2020-09-04 14:28:35 (PDT)</datetime>
        <errornum>2</errornum>
        <errormsg>require_once(/home/example/domains/analytics.example.com/public_html/vendor/autoload.php): failed to open stream: No such file or directory</errormsg>
        <scriptname>/home/example/domains/analytics.example.com/public_html/modules/base/classes/browscap.php</scriptname>
        <scriptlinenum>20</scriptlinenum>
</errorentry>
```

**Comment by padams** [comment]
Please follow the installation instructions. You need to run `composer install`.

**Comment by JoshWho** [comment]
Why doesn't the Download just have to full complete version as the tarball? Every answer on here is the same Look at the wiki. Maybe if the project was put together correctly people wouldn't repeat these questions.

Why can't this be a normal git project where we can clone and run git pull? 

These instruction about the tarball should be on the first page of the project and not in the wiki. The wiki is for further details not for basic installation.

I can see why so many r frustrated here. I am browsing through all the closed tickets with every answer check the Wiki
