### ISSUE TITLE
Responsive mouse tracker

### ISSUE THREAD

**Issue by IKetchup** [Open-Web-Analytics/Open-Web-Analytics#677]
**Description**  
Hello,

I would like to know if Open Web Analytics handle different screen size for the mouse tracker. If I have  2 clients with different window size of 1600*1200: if they click on the same button will the coordinates be register at the same normalized coordinates ( for example to generate heatmap).

Thanks 

**Example**

**Comment by padams** [comment]
Not currently. all the data is captured and sent down to the javascript (`x, y, page_width, page_height`) though. so all that is needed is to patch owa.heatmap.js in the right places. Feel free to reopen as an enhancement ticket if for you or someone to work on it.
