### ISSUE TITLE
Unable to login via Google Chrome browser (using https)

### ISSUE THREAD

**Issue by vishaldhiman** [Open-Web-Analytics/Open-Web-Analytics#679]
I have installed Open Web Analytics and put it on a public facing URL. Installed the ssl certificate 

OWA version: 1.6.9
PHP Version: 7.4.10
Webserver: Apache
Browser: Chrome (Version 85.0.4183.83 (Official Build) (64-bit))
Standalone installation.

I can provide logs if you need.

PS: It works fine on firefox

**Comment by fra-kuk** [comment]
Having the same behaviour. "No" for Chrome, "Yes" for Firefox.

**Comment by padams** [comment]
this has now been fixed in the v1.7.0
