### ISSUE TITLE
How do I setup emailer so that password reset starts working?

### ISSUE THREAD

**Issue by vishaldhiman** [Open-Web-Analytics/Open-Web-Analytics#680]
When new user is created owa is trying to send email directly to the new user. However, I am guessing owa setup needs to be configured with SMTP or some other email protocol and I am unable to find the documentation for it?

Vishal

**Comment by padams** [comment]
OWA uses phpmailer which in turn uses whatever MTA php is set to use. There are configs to override that and set an SMTP directly in OWA but if your php's MTA setup isn't working then i would start by fixing that.

**Comment by darsv** [comment]
IMO you need to tweak setting in includes/phpmailer.../src/phpmailer.php, at least I'm in the same situation and trying to get it fixed too.

**Comment by padams** [comment]
Phpmailer config can be set in the owa-config file. No need to modify the class file. Search the closed issues as I know this has been covered in the past.

**Comment by darsv** [comment]
Found something, just wanna check if should be this way in the owa-config file
`define('OWA_MAILER_HOST', 'your host');   
define('OWA_MAILER_PORT', 'your port');   
define('OWA_MAILER_USE_SMTP', true);   
define('OWA_MAILER_SMTPAUTH', true);   
define('OWA_MAILER_USERNAME', 'your user name');   
define('OWA_MAILER_PASSWORD', 'your password');`

**Comment by vishaldhiman** [comment]
What would really help is sample working configuration for gmail? I don't
want to configure MTA setup, so how I can override SMTP directly in OWA to
use gmail?

Vishal

**Comment by padams** [comment]
https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Configuration#enabling-an-alternative-smtp-gateway

**Comment by darsv** [comment]
Many would be grateful, me included, to have those options in the configuration file. Just disabled of course.
@padams the URL you shared has no the same syntax used in owa-config file, so the way I asked before is ok?

**Comment by padams** [comment]
No. Follow the syntax I posted.

**Comment by darsv** [comment]
El 2020-09-21 16:39, Peter Adams escribió:
> No. Follow the syntax I posted.

Ok, thanks

**Comment by vishaldhiman** [comment]
I got it to work with gmail as follows:
$this->set( 'base', 'mailer-host', 'ssl://smtp.gmail.com');
$this->set( 'base', 'mailer-port', '465');

It is important to have the mailer-host begin with ssl://...

Vishal
