### ISSUE TITLE
Add a Containerfile to support Docker/Podman and other alternatives

### ISSUE THREAD

**Issue by chintan-mishra** [Open-Web-Analytics/Open-Web-Analytics#682]
**Description**  

Containers are de-facto method to deploy applications for most organisations and indie developers. It allows users to quickly use an application with little to no extra effort. The current process to install PHP and other applications on the host are hefty. These cannot be easily replicated across various environments.

[vladk1m0/docker-owa](https://github.com/vladk1m0/docker-owa) provides a docker image but it uses PHP 5.*. The docs recommend PHP 7+. Also, this repository has't been updated in 18 months.

I am working on a container image that uses CentOS 8 as base image and builds upon it. If the community, maintainers, and developers are interested in this then I would love to send a PR.

**Example**  

NA

**Comment by chintan-mishra** [comment]
Here is the simplest Containerfile/Dockerfile that will make do most of the use cases. The base PHP image exposes port 80. In order to expose port 80, the container needs to run as root. Due to security reasons you may not want to do this. So, simply put the application behind a reverse proxy like EnvoyProxy, HAProxy, Apache, Nginx, etc.
```Dockerfile
FROM php:7.4.10-apache

RUN docker-php-ext-configure mysqli && \
        docker-php-ext-install mysqli

RUN curl -OL https://github.com/Open-Web-Analytics/Open-Web-Analytics/releases/download/1.7.0/owa_1.7.0_packaged.tar

RUN tar -xvf owa_* && \
        chown -R www-data:www-data /var/www/html
```
You can run this image like following:
```bash
# Podman/Docker
podman run \
    --network dev --name dev-owa \
    -dit owa:1.7.0-php7.4.10-apache
```

In the base image you can replace `php:7.4.10-apache` by `php:7.4.10-fpm`. But then you have to conform with PHP-FPM requirements. The major concern would be sharing the volumes from OWA container and FastCGI server like Apache, Nginx. This discussion is out of scope of this issue, so, I will leave it to the reader to figure out the finer details related to running PHP-FPM containers.

**Comment by jhughes2112** [comment]
https://hub.docker.com/r/jhughes2112/openwebanalytics
You're welcome to use my image.  I just built a super lightweight Alpine/Nginx image.

**Comment by chintan-mishra** [comment]
@jhughes2112 great job. I believe we can close this issue as anyone looking for container version can easily use your repo.
