### ISSUE TITLE
Composer.lock file does not reflect latest changes to composer.json in release 1.7.0

### ISSUE THREAD

**Issue by criterion9** [Open-Web-Analytics/Open-Web-Analytics#685]
- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: 1.7.0

**PHP Version**: 7.4 FPM, composer latest-stable

**Webserver**: Apache

**Browser**: N/A

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [x] Standalone

**Description**  
Using git checkout release-1.7.0 followed by composer install shows a message that the composer.lock file does not reflect the latest changes in composer.json.

**How to reproduce**  
Checkout the release branch and run the composer install.

**Possible Solution**  
Run composer update and commit the updated .lock file as part of the release process.

**Comment by padams** [comment]
updated in master.
