### ISSUE TITLE
API requests without permission still return status 200 instead of 403 in >1.6.7

### ISSUE THREAD

**Issue by criterion9** [Open-Web-Analytics/Open-Web-Analytics#686]
- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: >1.6.7

**PHP Version**: 7.4 FPM

**Webserver**: Apache

**Browser**: N/A

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [x] Standalone

**Description**  
API user accounts that had "analyst" permission in v1.6.7 and were able to retrieve reports over the REST interface receive an unauthorized message in the returned body but the header status is still 200 OK instead of 403 FORBIDDEN in v1.7.0.

Not sure if this would be considered a bug, but setting the account to "admin" role restores the expected results with the report details. If the roles/permissions intentionally changed between 1.6.7 and 1.7.0 it should be documented for those using the APIs.

**Possible Solution**  
The unauthorized message response should also set the correct header code (403 in this case) so API clients can react correctly without needing to parse the body for various possible error messages.

**Comment by padams** [comment]
No permissions changed but are you sure your analyst has permissions to view that specific website?

**Comment by padams** [comment]
The REST API now throws a 401 error when auth credentials fail.
