### ISSUE TITLE
In Dashboard, where do I see visitor clickstream, and heatmap?

### ISSUE THREAD

**Issue by vishaldhiman** [Open-Web-Analytics/Open-Web-Analytics#687]
Hi,
  Maybe I am confused, but where do I go to see visitor clickstream and heatmap on the OWA dashboard? Screenshot below:

![image](https://user-images.githubusercontent.com/6261636/95355971-268eb200-0894-11eb-9e7d-307238b89c30.png)

**Comment by Maaiins** [comment]
Navigate to a page detail page (e.g. Content -> Top Pages -> "Your Page"), in dashboard simply click on "Your Page" in the "Top Content" section. Scroll down and take a look on the right, it´s called "Heatmap Overlay" / "Domstreams" (Has to be enabled in Settings -> Modules -> Domstream)
