### ISSUE TITLE
Clicking the Funnel Visualization link under Goals in 1.7.0 displays "No API Method Found" where Goal 1 was configured

### ISSUE THREAD

**Issue by criterion9** [Open-Web-Analytics/Open-Web-Analytics#688]
- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: 1.7.0 (upgrade from 1.6.4->1.6.7->1.7.0)

**PHP Version**: 7.4 FPM

**Webserver**: Apache

**Browser**: Latest Chrome and Firefox

**Installation Type**
- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [x] Standalone

**Description**  
After upgrade from 1.6.4->1.6.7->1.7.0, the "Funnel Visualization" link in the left menu returns "No API Method Found" when clicked only for sites where the Goal 1 funnel had been configured. ("index.php?owa_siteId=####################&owa_period=last_seven_days&owa_do=base.reportGoalFunnel")

**How to reproduce**  
Click a the "Funnel Visualization" on a site that has Goal 1 funnel crafted. Sites where Goal 1 had not been configured load as expected.

**Possible Solution**  
Unknown

**Additional context**

**Comment by padams** [comment]
Fixed in master. will go out in next release.

**Comment by vishaldhiman** [comment]
Any update on when 1.7.1 will be released?
