### ISSUE TITLE
PHP message: PHP Notice:  Undefined variable: remote_host 

### ISSUE THREAD

**Issue by nkrings-nettersheim** [Open-Web-Analytics/Open-Web-Analytics#689]
After a fresh new installation with Version 1.7.0 and 5 days of work a take a look in the error log from Apache and there are a lot messages like this:

------
[Wed Oct 07 07:59:15 2020] [error] [pid 31599] mod_proxy_fcgi.c(860): [client 2003:6::] AH01071: Got error 'PHP message: PHP Notice:  Undefined variable: remote_host in /var/www/virtual/[ersetzt]/html/owa/modules/base/classes/trackingEventHelpers.php on line 613PHP message: PHP Notice:  Undefined variable: remote_host in /var/www/virtual/[ersetzt]/html/owa/modules/base/classes/trackingEventHelpers.php on line 614PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/virtual/[ersetzt]/html/owa/owa_db.php on line 356PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/virtual/[ersetzt]/html/owa/owa_db.php on line 356PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/virtual/[ersetzt]/html/owa/owa_db.php on line 356PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/virtual/[ersetzt]/html/owa/owa_db.php on line 356'

---------------
I understand that there is a problem with the remote_host, but I've no idea how can I fix this. Any ideas?

**Comment by padams** [comment]
Fixed in master. Will go out in the next release.
