### ISSUE TITLE
install.php is not disabled after installation is complete

### ISSUE THREAD

**Issue by jhughes2112** [Open-Web-Analytics/Open-Web-Analytics#691]
**Affected Version(s)**: 1.7.0

**PHP Version**: 7.3.23 FPM

**Webserver**: Nginx

**Browser**: Any

**Installation Type**

Docker image built from dist tar.

**Description**  
I did a basic install of the image, have 4 sites configured with it.  Out of curiosity, I decided to see what would happen if I directly went to /install.php, hoping it would refuse.  It didn't.  The install page is unsafe.

**How to reproduce**  
Install.  Try to re-run install.

**Possible Solution**  
OWA_INSTALLING is enabled before the $owa object is created, and it doesn't attempt to contact the DB to get configuration, so the disabled endpoints list is empty,  Probably want to check if it's installed before defining OWA_INSTALLING.  Chicken/egg problem.

**Additional context**  
Please let me know as soon as you have a fix, so I can update my Docker image with your new code.  Every install that goes out is insecure at the moment.

For anyone who is reading along, just move install.php out of your /var/www/html folder until this is fixed.

**Comment by padams** [comment]
This is fixed in master. if you'd like to test it out.

**Comment by jhughes2112** [comment]
Thanks for jumping on this!  My workflow for updating the Docker image requires a new dist-release tar, so the autoload.php file is in the right place, among other things.

**Comment by l2dy** [comment]
Is this some kind of vulnerability? Have you requested a CVE for this? @jhughes2112

**Comment by jhughes2112** [comment]
Yes.  I expected a new version of the docker image to be built immediately after the fix, but I stopped using OWA after discovering this.  Anyone who is currently running OWA in a docker container may have their install completely wiped, assuming their docker container is exposed to the internet.

**Comment by padams** [comment]
Weird. not sure why this didn't go out. Will push a new release later today.
