### ISSUE TITLE
Error loading tracking script in Firefox

### ISSUE THREAD

**Issue by LeftShoeSize47** [Open-Web-Analytics/Open-Web-Analytics#695]
I have installed OWA version 1.7.0 on a vps running webserver "caddy 2.2.0" on Centos 7.10.
Then I have added a website I want to track and added the js tracker code.
Now when I open the website in IE, the tracker script loads perfectly and all data about the visit is reported in OWA. When I open the site in Firefox however, the visit is detected by OWA, but visit length is 0.
When checking the console (F12) in Firefox, it comes up with this error:

> Loading failed for the <script> with source “https://www.mysite.nl/owa/modules/base/js/owa.tracker-combined-min.js”.

This is the tracker code on the website
<pre>
<code>
` <script type="text/javascript">
var owa_baseUrl = 'https://www.mysite.nl/owa/';
document.write(unescape("<script src='" + owa_baseUrl + "'modules/base/js/owa.tracker-combined-min.js' type='text/javascript'> </script>"));
</script>
</code></pre>
<pre>
<code>
<script type="text/javascript">
try {
   OWA.setSetting('baseUrl', owa_baseUrl);
   OWATracker = new OWA.tracker();
   OWATracker.setSiteId('d273bd6335ae1aae69f46f08eaca1f86');
   OWATracker.trackPageView();
   OWATracker.trackClicks();
   OWATracker.trackDomStream();
} catch(err) {}

</script>	</code></pre>
`
Any ideas?

**Comment by oyvindsaether** [comment]
![nope](https://user-images.githubusercontent.com/68732993/96356237-e9c08780-10eb-11eb-96e6-40eda150d8a8.jpg)

It's a bit odd that your current configuration works with IE, it shouldn't. www.mysite.nl is serving a HTTPS certificate for server.balansinternet.nl. You should probably close this as a OWA bug and fix your configuration.

**Comment by Maaiins** [comment]
> ![nope](https://user-images.githubusercontent.com/68732993/96356237-e9c08780-10eb-11eb-96e6-40eda150d8a8.jpg)
> 
> It's a bit odd that your current configuration works with IE, it shouldn't. [www.mysite.nl](http://www.mysite.nl) is serving a HTTPS certificate for server.balansinternet.nl. You should probably close this as a OWA bug and fix your configuration.

Closing this issue due miss configuration, I can reproduce the szenario
