### ISSUE TITLE
[Feature Request] Cookie-less Session Tracking would be nice

### ISSUE THREAD

**Issue by oyvindsaether** [Open-Web-Analytics/Open-Web-Analytics#696]
OWA lacks any means of disabling cookies. Don't care if they are supposedly session cookies, cookies are cookies. The only way I see to disable them is to comment out setcookie around line 1160 in owa_coreAPI.php. That works fine.

OWA seems to think every page view is a new visitor without cookies. It would be nice if it could understand that two consecutive page loads from the same IP with the same User-Agent is _probably_ the same person. It would be nice if OWA could figure that out on it's own. Also, it would be nice to know if it's possible to $owa->setsomething to give it a session ID that way when it's implemented using PHP.

There's plenty of ways to get a "session ID" with no cookies. The first 5 bytes of the sha256 of the IP + the first 5 bytes of the sha256 of the user-agent creates a 10 byte session ID that's perfectly fine. It can't track someone over time the same way a cookie does, but it's good enough.

I don't plan on using OWA or fiddling with it beyond what I did to write a review of it so I don't care if it becomes usable without cookies or not. I just see it as a basic feature it should have and a big minus worth mentioning.

**Comment by padams** [comment]
Many have tried this over the years (including me) and it does not produce accurate results. The big disadvantage of trying to use IP + UA is the reality that A LOT of users are behind proxies. Corporations and some big ISPs are notorious for this.  And now with VPN's being so popular it's even worse. The net result is that you could have thousands of users all coming from the same IP and mostly using Chrome on Windows...

**Comment by oyvindsaether** [comment]
Yes, there's a few downsides, just like there's a downside to using OWA with the JavaScript vs implementing it with PHP: It doesn't count half your visitors. Potential OWA users have a choice between using PHP or JavaScript and they can decide what trade-offs they want. OWA could offer the same choice on cookies: Those who won't want it to set any cookies ever could get the option to turn them off and still have some basic session tracking using IP/UA (or something else) and those (primarily outside the EU) who think setting cookies are acceptable can do that.

Matomo (option to turn it off) and Plausible Analytics (off by default) both do just fine without cookies. There are trade-offs to turning cookies off in Matomo, just like there would be if OWA got that option. 

I've got no idea how many people in the EU would use OWA if it supported a cookie-less mode, so it may not matter. I do know I can't recommend it as long as it gives everyone a cookie willy nilly.

**Comment by Maaiins** [comment]
Hey @oyvindsaether,

i've implemented an session cookie based tracking in the past. You have to add `$this->set('base', 'cookie_persistence', 'false');` in your `owa-config.php`. This is fine to use in the eu, on the downside you will lose the "user was already there" feature.

**Comment by daemon-byte** [comment]
> Hey @oyvindsaether,
> 
> i've implemented an session cookie based tracking in the past. You have to add `$this->set('base', 'cookie_persistence', 'false');` in your `owa-config.php`. This is fine to use in the eu, on the downside you will lose the "user was already there" feature.

How is this legal in the EU? I'm trying to get my head around all the legal stuff and my understanding is any cookie (session based or persistent) that isn't strictly required for functional reasons is not legal without consent.

**Comment by Maaiins** [comment]
> How is this legal in the EU? I'm trying to get my head around all the legal stuff and my understanding is any cookie (session based or persistent) that isn't strictly required for functional reasons is not legal without consent.

I talked to some lawyers and they said it´s ok. But it´s plausible, I never thought about that...
But I think it´s possible to build the stuff around and use the session cookie for tracking. So you have to add the analytics part to your legal notice but don´t need an consent

**Comment by daemon-byte** [comment]
> > How is this legal in the EU? I'm trying to get my head around all the legal stuff and my understanding is any cookie (session based or persistent) that isn't strictly required for functional reasons is not legal without consent.
> 
> I talked to some lawyers and they said it´s ok. But it´s plausible, I never thought about that...
> But I think it´s possible to build the stuff around and use the session cookie for tracking. So you have to add the analytics part to your legal notice but don´t need an consent

It's been driving me nuts trying to work it out so the company is just going to hire a specialist lawyer we can ask questions to. Whole thing is ridiculous. Making it so complicated nobody knows what they should be implementing, most of the stuff out there is definitely illegal (pre checked boxes, the refuse is buried deeep in screens or not available at all, even seen refused access) but still it remains up. Bureaucrats looking for headlines but no knowledge on the subject. If we can't use session data then stats is done. We literally have no interest in personal info and store nothing like that. We just want to track what parts of the website users visit, their paths through the website, where they click and what they do etc etc. All so we can improve the website's workflow while seeing where people struggle, what parts are popular etc. I can't do that without tracking users within the session so I was actually really hopeful when I saw your comment that you might have some insight :) If I can only collect stats for people who specifically check a box to allow it then I'm going to get bugger all
