### ISSUE TITLE
Error log shows "[debug_log]  is not a supported database."

### ISSUE THREAD

**Issue by paulchoix** [Open-Web-Analytics/Open-Web-Analytics#698]
**Before you open an issue:**

- [X ] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [X ] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting)

**Affected Version(s)**: 1.7.0

**PHP Version**: 7.2 FPM

**Webserver**: Apache/Nginx

**Browser**: Brave/Chromium: 86.0.4240.99

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [X ] Standalone

**Description**  
I am trying to install OWA on a subdomain and when I enter the initial configuration information, I get a 500 error. The error log simply states "[debug_log]  is not a supported database." There seems to be two consecutive spaces in the log as though it should say "X is not a supported database" but X returns empty. I can't seem to find any problems accessing the SQL database. I am using MySQL. I tried manually configuring owa-config.php but then I got 500 errors on the index page.

**Additional context**  
I've configured Nginx as a Web Server and reverse proxy for Apache as per this guide although I also had to adapt it for use with a subdomain: https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-as-a-web-server-and-reverse-proxy-for-apache-on-one-ubuntu-18-04-server

**Comment by Maaiins** [comment]
Which SQL Server are you using? Currently there is only mysql supported

**Comment by amv42** [comment]
Same error - mysql is installed....

**Comment by paulchoix** [comment]
> Which SQL Server are you using? Currently there is only mysql supported

Yes, I am using MySQL (mysql-server).

**Comment by Maaiins** [comment]
Please take a look into your owa-config.php is this line set to mysql? Like the example below

`define('OWA_DB_TYPE', 'mysql'); // options: mysql`

**Comment by paulchoix** [comment]
I get the same error message whether I use the OWA installation page or whether I configure owa-config.php manually with the following settings:
define('OWA_DB_TYPE', 'mysql');
define('OWA_DB_NAME', 'owadb');
define('OWA_DB_HOST', 'localhost');
define('OWA_DB_USER', 'owadbuser');
define('OWA_DB_PORT', '3306');

I also set the public URL and created unique entries for the nonce key, nonce salt, auth key and auth salt.

**Comment by Maaiins** [comment]
Can you turn on logging and post the result here?

Uncomment the following lines and take a look into `owa-data/logs`
`define('OWA_ERROR_HANDLER', 'development');`
`define('OWA_LOG_PHP_ERRORS', true);`

**Comment by paulchoix** [comment]
Thanks for the tip. I activated the error logs and found "Call to undefined function mysqli_connect()". The installation guide I used had not mentioned I needed php-mysqli. I installed it with "sudo apt install php-mysqli". Works now!
