### ISSUE TITLE
Disappointed this is such a battle

### ISSUE THREAD

**Issue by DamonMedek** [Open-Web-Analytics/Open-Web-Analytics#699]
**Description**  
Really liked the idea of this but I've been battling this program for almost two day now. Im running on a lamp stack on google cloud I've installed OWA multiple times to track my website pages with no luck. I've installed no problem, I can create "new site" and see it update mysql in its dedicated table. I've change mysql to strict mode off. I've opened all folders and files to chmod 777. I'm placing the javascript tracker in the header and the body to see if it makes a difference, it doesn't. I see 200 on owa-tracker-combined-min.js but I don't see any logs.php in chrome network inspector. I've tried using the php debugger but its not creating any new files in logs folder for me. yes, I removed the comment //. Any help would be appreciated.

Seems like every tutorial on this is 5 to 11 years old and I've very disappointed this has been such a battle. 
 
**Example**

**Comment by padams** [comment]
Are there any JS errors in the console? Do you have don't track turned on in the browser? Or a cookie blocker?

**Comment by DamonMedek** [comment]
I now see log.php sending owa_timestamp etc... the JS is working, I disabled adblocker and set all cookies allowed and turned off "Do Not Track" off in browsing traffic.  Even now with the log.php working I'm still not seeing my views updated. I just deleted all cookies to reset the browser. Any else I can try?

**Comment by DamonMedek** [comment]
The problem could be a composer issue. there is no vendor folder in version 1.7 OWA. I have used composer for other things and put my vendor folder in there to see if it would work. Still nothing, could you explain what I need to do to composer to make it open the stream?

<errormsg>require_once(/var/www/html/owa/vendor/autoload.php): failed to open stream: No such file or directory</errormsg>
	<scriptname>/var/www/html/owa/modules/base/classes/browscap.php</scriptname>
	<scriptlinenum>20</scriptlinenum>
</errorentry>

 
[21-Oct-2020 14:06:11 America/Los_Angeles] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/owa/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/owa/modules/base/classes/browscap.php on line 20
14:06:16 2020-10-21 14380 [debug_log] check for http host

**Comment by DamonMedek** [comment]
I figured it out I had to run composer in command line (from same directory where composer.json is located) /var/www/html/owa  point to directory ssh and run command. **composer install** I'm getting a view count, but I'm gonna keep this thread open for a bit longer.

**Comment by padams** [comment]
The wiki has instructions for installing from GitHub source. 

Or you could just use the "packaged" release tarball which contains all the vendor dependencies.
