### ISSUE TITLE
Add a check for the vendor directory during install

### ISSUE THREAD

**Issue by Maaiins** [Open-Web-Analytics/Open-Web-Analytics#702]
**Description**  
Many users won´t use the packaged installation, add a check during install

**Comment by kiliandr** [comment]
i wondered why there were no users logged and i found in the logs this line:
PHP Fatal error:  require_once(): Failed opening required '/xyz/vendor/autoload.php'

i did not use package installation.

**Comment by Maaiins** [comment]
> PHP Fatal error: require_once(): Failed opening required '/xyz/vendor/autoload.php'
> 
> i did not use package installation.

There is already your problem. Use the packaged installation and all will went fine
