### ISSUE TITLE
Relationship of owebanalytics.com to Open-Web-Analytics?

### ISSUE THREAD

**Issue by oddhack** [Open-Web-Analytics/Open-Web-Analytics#703]
**Description**  
Recently a group of users of a browser extension, The Great Suspender, realized that the extension had been sold to an unknown party some months ago, and since then, has been updated on the Chrome store inconsistently with its github repository, and appears to be loading new analytics code from the domain 'owebanalytics.com' for unknown purposes. The new extension / repository owner is unresponsive to questions. See https://github.com/greatsuspender/thegreatsuspender/issues/1175#issuecomment-723287167 . Would your project have any insights into whether this is or is not a trustworthy domain, has any relationship to the actual OWA project, etc.? It's obviously not your responsibility that someone may be posing as you, but something it seems you would reasonably be concerned about, so any feedback you have is welcome.

**Comment by padams** [comment]
Not affiliated with this project in any way.
