### ISSUE TITLE
Any way to turn off do not track without editing the js.

### ISSUE THREAD

**Issue by uhexos** [Open-Web-Analytics/Open-Web-Analytics#705]
**Description**  

Is there any setting or cleaner method to disregard the browser do not track setting when using OWA. Currently I've had to edit the combined.min.js  directly. Also please don't shoot the messenger I didn't make this decision.

**Comment by padams** [comment]
Not really... That said you can modify the non minified version of the tracker and then rebuild the combined package via the command line `build` command. See the command line page on the wiki.

**Comment by uhexos** [comment]
thanks
