### ISSUE TITLE
owa_format parameter does not return the specified format

### ISSUE THREAD

**Issue by uhexos** [Open-Web-Analytics/Open-Web-Analytics#706]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide

- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: 1.7.0

**PHP Version**: 7.2.34-2+ubuntu18.04.1+deb.sury.org+1 

**Webserver**: Apache

**Browser**: Firefox 81.0 and Postman

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [x] Standalone

**Description**  

Using the data access API the only format that gets returned is JSON. The owa_format parameter appears to be completely ignored.
**How to reproduce** 
Enter any valid endpoint and set the owa_format to anything other than json. Example
 `http://localhost/owa/api/?owa_format=html&owa_apiKey=358bb5882ef73515810a89322d8951ff&owa_module=base&owa_version=v1&owa_do=reports&owa_metrics=pageViews&owa_dimensions=pagePath,date,customVarValue1,customVarName1&owa_startDate=20201113&owa_endDate=20201114&owa_limit=10&owa_siteId=d59871d8a95931b3793baf168edac9a0&owa_constraints=customVarValue1==3`

**Possible Solution**  

**Additional context**  

output
![Screenshot from 2020-11-14 02-49-36](https://user-images.githubusercontent.com/14164093/99136256-341e2100-2624-11eb-8fe6-4480934bf5a7.png)

**Comment by padams** [comment]
The old API used ot return other formats but the new API should only return JSON. This is a bug in the documentation which I'll fix now. ;)
