### ISSUE TITLE
Getting error code 406 on log.php

### ISSUE THREAD

**Issue by screamingfingers** [Open-Web-Analytics/Open-Web-Analytics#707]
**Description**  

I installed the current version of OWA. Everything appears to work. 

I've installed the tracking script in the head section of the website.

No data is being tracked by the OWA installation.

So I followed the troubleshooting steps. I see that the log.php is getting a 406 code. 

The domain name is correct, and the path to the files is correct.

I'm on Cpanel using PHP 7.4.

Any help would greatly be appreciated.

**Comment by padams** [comment]
Sounds like an odd server config issue. You would need to post actual http headers here if you want someone to dig into it. See the troubleshooting page on the wiki.
