### ISSUE TITLE
beginner question

### ISSUE THREAD

**Issue by Posteinwurf** [Open-Web-Analytics/Open-Web-Analytics#710]
Dear all, 

just a quick simple question: Do I have to put a different Code and ID on each page that I want to track? Or can I use the same ID for each subpage on my website?

Thanks 

Malte

**Comment by Posteinwurf** [comment]
Additional beginner question (sorry, could not find the answer in the Wiki or forums): Is it easier / better to use php or javascript? My pages are already php (not html).

Thanks in advance for your helpful answers!

**Comment by padams** [comment]
One siteId per website. The JavaScript tracker has more features and benefits.

**Comment by Posteinwurf** [comment]
Thank you very much for the precise answer. 
So I have one SiteID, so I can put the same code on each subpage that I want to track?
That would be great!

**Comment by padams** [comment]
Yes same JavaScript goes on every page you want to track.

**Comment by Posteinwurf** [comment]
Great, thank you! Perfect.
