### ISSUE TITLE
Database Schema Installation failed. Please check the error log file for more details

### ISSUE THREAD

**Issue by Buliwif** [Open-Web-Analytics/Open-Web-Analytics#713]
Hi,

I know the problem was closed for some users but I don't understand how to solve this issue.

In my apache error.log I only have a warning : 
PHP Warning:  Use of undefined constant OWA_ERROR_HANDLER - assumed 'OWAuture version of PHP) in /var/www/html/owa/modules/base/templates/config_dom.tpl on line 15, referer: 

I take a look on my database but it seems different thane the schema you give : 
+-------------------------------+
| Tables_in_owadb               |
+-------------------------------+
| owa_action_fact               |
| owa_ad_dim                    |
| owa_campaign_dim              |
| owa_click                     |
| owa_commerce_line_item_fact   |
| owa_commerce_transaction_fact |
| owa_configuration             |
| owa_document                  |
| owa_domstream                 |
| owa_exit                      |
| owa_feed_request              |
| owa_host                      |
| owa_impression                |
| owa_location_dim              |
| owa_os                        |
| owa_queue_item                |
| owa_referer                   |
| owa_request                   |
| owa_search_term_dim           |
| owa_session                   |
| owa_site                      |
| owa_site_user                 |
| owa_source_dim                |
| owa_ua                        |
| owa_visitor                   |
+-------------------------------+

I don't know what should I do. Can you help me please ?

**Comment by padams** [comment]
Can't help without. Proper debug info. Please see the troubleshooting page on the wiki and refine with debug info.
