### ISSUE TITLE
Upgrading from 1.6.2 to 1.7.0

### ISSUE THREAD

**Issue by joho1968** [Open-Web-Analytics/Open-Web-Analytics#716]
**Affected Version(s)**: 1.7.0

**PHP Version**: 7.2 FPM

**Webserver**: Nginx

**Browser**: Chrome 80.x.x

**Installation Type**

- [ ] Standalone

**Description**  

I tried upgrading from 1.6.2, which was running successfully, to 1.7.0. All files seems to be in place, I have no error messages in the PHP log, etc. When I go into admin, I'm greeted with:

    Some Modules need to create or update their database tables.
    Here is the list of modules that have updates that needs to be applied:

        base

    It is recommended that you backup your database before applying updates.

So I click on "Apply updates" and get this on the screen:

        Error! Updates failed. Check OWA's error log file for more details and try again.
    no error messages

(The above is a verbatim copy of the error message)

The OWA error log shows:

    21:55:15 2020-12-08 10898 [debug_log] Applying Update 10 (owa_base_010_update)
    21:55:15 2020-12-08 10898 [debug_log] Pre Update Proceadure Suceeded
    21:55:15 2020-12-08 10898 [debug_log] Adding page_width to owa_domstream failed.
    21:55:15 2020-12-08 10898 [debug_log] Update Proceadure Failed
    21:55:15 2020-12-08 10898 [debug_log] Update Failed

**Comment by padams** [comment]
Sounds like the database user in your OWA config file might not have ALTER table privileges.
