### ISSUE TITLE
Can OWA get page title automatically with php

### ISSUE THREAD

**Issue by Posteinwurf** [Open-Web-Analytics/Open-Web-Analytics#719]
Dear all,

thanks for contributing to this program. Works great! I only have 2 questions. 

I have added the owa code to my master frame (php).

1) It this the right thing to do? OWA seems to recognise each page the is requesting the master frame.

2) Is it possible to use a php code that will automatically get the page title? The default line is 

$owa->setPageTitle('somepagetitle');

and I think "somepagetitle" should be manually replaced by the page title. Is there a way to do it automatically (when the actual page request happens) instead of manually?

Thank you very much.

Malte

**Comment by padams** [comment]
Your php application should be populating a page title variable that you then feed to setPageTitle.

Re: the frame issue... OWA doesn't know anything about frames. It only tracks what you tell it to.
