### ISSUE TITLE
cli.php: Undefined variable: mailer_domain

### ISSUE THREAD

**Issue by l2dy** [Open-Web-Analytics/Open-Web-Analytics#720]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: 1.7.0

**PHP Version**: 7.1

**Webserver**: Apache

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [x] Standalone

**Description**  

Executing `php owa/cli.php cmd=update` warns the following:

```
PHP Notice:  Undefined variable: mailer_domain in .../owa/modules/base/classes/settings.php on line 646
PHP Stack trace:
PHP   1. {main}() .../owa/cli.php:0
PHP   2. owa_caller->__construct() .../owa/cli.php:60
PHP   3. owa_caller->__construct() .../owa/owa_caller.php:73
PHP   4. owa_coreAPI::configSingleton() .../owa/owa_base.php:78
PHP   5. owa_coreAPI::supportClassFactory() .../owa/owa_coreAPI.php:142
PHP   6. owa_lib::factory() .../owa/owa_coreAPI.php:455
PHP   7. owa_settings->__construct() .../owa/owa_lib.php:513
PHP   8. owa_settings->getDefaultSettingsArray() .../owa/modules/base/classes/settings.php:62
```

**How to reproduce**  
`php owa/cli.php cmd=update`

**Possible Solution**  
Set a fallback value for `mailer_domain`.

**Additional context**

**Comment by padams** [comment]
This should be fixed so long as you have properly set  a PUBLIC_URL in your config file.
