### ISSUE TITLE
Geolocation is not working

### ISSUE THREAD

**Issue by OldKrupnik** [Open-Web-Analytics/Open-Web-Analytics#721]
I am using Open Web Analytics 1.7.0 with Maxmind GeoIP module activated but the geolocation still does not work ("not set" values for countries, cities etc.)
I modified the owa-config.php file several times:

    define('OWA_MAXMIND_DATA_DIR', OWA_DATA_DIR.'/maxmind/');
But then I received this error:

    [debug_log] Maxmind DB file could is not present at: OWA_DATA_DIR/maxmind/ 

Then I tried:

    define('OWA_MAXMIND_DATA_DIR', ’/home/my_website/www/analytics/owa-data/maxmind/’);

And I received this error:

    [debug_log] Maxmind DB file could is not present at: /home/my_website/www/analytics/owa-data/maxmind/ 

I also tried:

    define('OWA_MAXMIND_DATA_DIR', ’https://my_website.com/analytics/owa-data/maxmind’’);

But it did not work.

What should I do to make it work ?

**Comment by padams** [comment]
Did you download the SB file from maxmind? See the wiki for instructions.

**Comment by OldKrupnik** [comment]
> Did you download the DB file from maxmind? See the wiki for instructions.

Yes, I downloaded the "GeoLite2-City.mmdb" file (65 Mo) and put it under owa-data/maxmind

**Comment by OldKrupnik** [comment]
Any ideas how to solve this issue ?

**Comment by padams** [comment]
If you are absolutely sure the file in the right directory then check the permissions on the file.

**Comment by OldKrupnik** [comment]
> If you are absolutely sure the file in the right directory then check the permissions on the file.

The permissons of the GeoLite2-City.mmdb file are 604.

**Comment by padams** [comment]
That could be your issue. Did you try making them 777 or 755 just to test?

**Comment by OldKrupnik** [comment]
I changed permissions to 777 and I still have the issue :(

    14:54:59 2021-01-27 1381 [debug_log] Maxmind DB file could is not present at: OWA_DATA_DIR/maxmind/
