### ISSUE TITLE
trackingEventHelpers.php Undefined variable remote_host

### ISSUE THREAD

**Issue by Wild-Var** [Open-Web-Analytics/Open-Web-Analytics#722]
**Before you open an issue:**

- [X] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [X] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: 1.7.0

**PHP Version**: 7.2.24

**Webserver**: Apache

**Browser**: Not Browser Related

**Installation Type**
- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [X] Standalone

**Description**  
My server error log shows:
`PHP Notice:  Undefined variable: remote_host in [REDACTED]/modules/base/classes/trackingEventHelpers.php on line 614
PHP Notice:  Undefined variable: remote_host in [REDACTED]/modules/base/classes/trackingEventHelpers.php on line 613`

Query:
`/log.php?owa_timestamp=1609911844&owa_event_type=dom.click&owa_dom_element_name=%28not+set%29&owa_dom_element_value=%28not+set%29&owa_dom_element_id=%28not+set%29&owa_dom_element_class=%28not+set%29&owa_dom_element_tag=P&owa_page_url=https%3A%2F%2Fexample.com%2F%3Fp%3D1332%23&owa_page_width=605&owa_page_height=696&owa_html_element_text=&owa_dom_element_x=39&owa_dom_element_y=3933&owa_click_x=282&owa_click_y=3956&owa_is_new_visitor=true&owa_visitor_id=1609909917028534188&owa_fsts=1609909917&owa_dsfs=0&owa_last_req=&owa_session_id=1609909917358989627&owa_is_new_session=true&owa_nps=0&owa_dsps=0&owa_medium=organic-search&owa_source=bing.com&owa_search_terms=%28not+provided%29&owa_session_referer=https%3A%2F%2Fwww.bing.com%2F&owa_site_id=15efbf3601b0bc00044719a496870e8b&owa_HTTP_REFERER=https%3A%2F%2Fwww.bing.com%2F&owa_page_title=The+PostTitle+%282003%29+%E2%80%93+ExampleDomain&`
(Website name and URL redacted)

IP:

> 2800:5f0:81a:821:b855:9d6:1c58:8e42

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by padams** [comment]
Are you running under a fully qualified domain name or localhost/ip address?

**Comment by Wild-Var** [comment]
Full Qualified Domain

**Comment by padams** [comment]
This has been fixed.
