### ISSUE TITLE
Added JavaScript Tracking Code to My Opencart Website but Not working

### ISSUE THREAD

**Issue by Ferguson230** [Open-Web-Analytics/Open-Web-Analytics#724]
Hello, I successfully installed Open Web Analytics and Added JavaScript Tracking Code to My Opencart 3.0.2 Website, but on the Open Web Analytics Dashboard page, nothing is tracking - everything there is showing 0, though when I use developer tools in chrome browser under Network, I see that `https://example.com/ow/modules/base/js/owa.tracker-combined-min.js` and `log.php?owa_timestamp=56...`
Did I do anything wrong?
Thank you.

**Comment by tawoni1** [comment]
Hi I installed master version and got the same issue.

**Comment by tawoni1** [comment]
Hi I installed master version and got the same issue.

**Comment by tawoni1** [comment]
Hello.
I got the same issue but I found solution from previous issue log.
If you installed master code, you need to add vendor folder into owa folder. 
you can get package from 
https://github.com/Open-Web-Analytics/Open-Web-Analytics/releases/download/1.7.0/owa_1.7.0_packaged.tar

I hope  my comment is help for you.

**Comment by Ferguson230** [comment]
Thank you @tawoni1 Your comment helped, now I it's working.

**Comment by Ferguson230** [comment]
@tawoni1 How do you get it to track Revenue for the eCommerce aspect, for now it is only tracking page visits, though e-commerce Reporting is set to On.

**Comment by tawoni1** [comment]
That's great. ^0^
I didn't get the data yet. I just succeed to get base data when I leave comment.
There are documents for setting up web.
https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki

It will be help for you I hope.

**Comment by Ferguson230** [comment]
@tawoni1 Thank you, I checked the sub-link under the link you provided for eCommerce https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Ecommerce-Tracking and the values there are static...
`owa_cmds.push(['addTransaction', 
           'order123', // the id of the order, comes from your ecommerce system -required
           'test-app',  // the source or store name that originated the transaction
           '100.50', // the total amount of revenue - required
           '1.25', // amount of tax
           '3.50',  // amount of shipping
           'paypal', // transaction gateway name
           'United States', // country
           'CA', //state
           'Palo Alto' //city
]);
owa_cmds.push(['addTransactionLineItem', 'order123', 'SKU123', 'widget', 'things', 10.00, 5]);
owa_cmds.push(['addTransactionLineItem', 'order123', 'SKU456', 'widget', 'things', 10.10, 5]);
owa_cmds.push(['trackTransaction']);`

But I am going to try to replace the values with Opencart's similar twig code for checkout to see if it's going to work...
