### ISSUE TITLE
Tracking a second web site with the same owa installation / directory

### ISSUE THREAD

**Issue by Posteinwurf** [Open-Web-Analytics/Open-Web-Analytics#727]
Dear @padams, Dear all, 

I want to track a second site with the same owa installation, but it does not work:

1) I already track www.freiblatt.de This works great (thanks again to everyone involved in owa!)

2) I want to track www.freiblatt.com as well. Is it possible to just add the php tracking code to the .com-site and point it to the owa directory that already exists: www.freiblatt.de/owa ?

I tried this, but the result is, that the www.freiblatt.com page is not displayed any more (I created a new site ID and php tracking code in the sites roster for www.freiblatt.com and inserted the code between the head tags).

Thank you very much in advance!

Malte

**Comment by padams** [comment]
To track an additional site via the same OWA instance:


1. Generate anew site profile via the admin interface or REST API

2. Copy the siteID of the newly created site profile. 

3. Substitute the siteID in the JS tracker Code.
