### ISSUE TITLE
the owa server does not collect data  - please advice where to look

### ISSUE THREAD

**Issue by JonasJJJJJ** [Open-Web-Analytics/Open-Web-Analytics#728]
**Description**  

owa server side:    server - debian 10, php 7.3, mariadb 10.3 apache webserver
owa web side webpage - php,html,   owascript - js

serverside installed, configured and we got the js code which was inserted in web page. 
webpage started, available on internet  on https and subdomain.  the browser inspector does show ok, but no data received on server side. completely no reaction at all. 
subdomain dns outside network, owa server and webpage server is on the same apache web server instance, inside ournetwork. 
the same with php script.
please support where may we look further. 

**Example**  

Status   Method Domain  			File 						Remote IP                   Transferred
200			**I**GET **I**domain.lt   **I**          /						**I**	ournetworkip:443    **I**  2.12 Kb
304 		        **I** GET**I** ajax.googleapi.**I**    Jquery.mln.Js				  **I**      142.250.74.202:443 **I**   cached
304			**I**GET**I** cdnjs.cloudflar.. **I**  popper.mln.Js				   **I**     104.16.18.94:443     **I**  cached
304			**I**GET **I**maxcdn. bootst..  **I**  bootstrap. min.js			 **I**        209.197.3.15:443  **I**   cached
200			**I**GET **I**domain.lt   **I**        owa.tracker-combined-min.js        **I**      ournetworkip:443  **I**   19.97 Kb
200			**I**GET**I** domain.lt    **I**       log.php?owa_timestamp=161       **I**      ournetworkip:443  **I**   383 B
200			**I**GET **I**domain.lt     **I**      owa.tracker-combined-min.js        **I**     ournetworkip:443  **I**  19.97 Kb
304			**I**GET **I**domain.lt      **I**     Log03.png                                   **I**       ournetworkip:443**I**  cached
200                 **I** GET **I**domain.lt        **I**   2favicon.png                                 **I**       unknown              **I**  cached

**Comment by padams** [comment]
Please step through the troubleshooting guide on the wiki. No one can help unless you are explicit about where in the process that is set out in that guide you are seeing an issue.

**Comment by JonasJJJJJ** [comment]
Thanks for response. on the browser I do see:  according troubleshooting  5  -  response code is 200 then all is well.  on the server side number 6 I see nothing. tested from multiple devices multiple networks.

**Comment by padams** [comment]
You see a 200 status code for a request to log.php and no entries in OWA's debug log?

**Comment by macedo6466** [comment]
I would like to jump into this thread... I recently installed the OWA on my server and noticed It wasn't recording any information from my website. I looked into the error_log and noticed one error: Function get_magic_quotes_gpc() deprecated.
If this is the problem how can it be fixed without rewriting PHP? 
Thank you.

**Comment by padams** [comment]
Can you post the exact error as seen in the log file?

**Comment by macedo6466** [comment]
[09-Feb-2021 17:59:19 America/Los_Angeles] PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in www.myurl.com/modules/base/installCheckEnv.php on line 78

**Comment by padams** [comment]
That's unlikely to be your issue as it's only a warning. Please see the troubleshooting page on the wiki and open a new ticket detailing the steps you have taken to debug. No help can be provided unless you walk through the steps outlined in the troubleshooting guide.
