### ISSUE TITLE
is it possible to track users?

### ISSUE THREAD

**Issue by sduddupudi** [Open-Web-Analytics/Open-Web-Analytics#730]
How hard to config owa to track user id  ? I wanted to just track users by emails which are attending to the website live event.

**Comment by dorier-group** [comment]
how could I pass my visitor ID ? is it possible please help guys thanks :)

**Comment by padams** [comment]
You gotta search past issues. This has been answered in #489.

**Comment by sduddupudi** [comment]
thanks, i sort out all issues the only issue is how can i search the reports using the username ? it doesn't filter
