### ISSUE TITLE
Free access to install.php after installation

### ISSUE THREAD

**Issue by AlexanGusev** [Open-Web-Analytics/Open-Web-Analytics#735]
After installation install.php is still in the free access by http://yourdomain/path/to/owa/install.php
Anyone can start it again. Any solution?

**Comment by AlphaDG** [comment]
Use your 'file manager', or FTP client and delete the file. I am curious how you installed the programs in the first place?

**Comment by jgarruba** [comment]
I also still have the install.php file in my OWA dir after a full new install. year ago i remeber doing an installation of owa and it prompted to delete it.

**Comment by AlphaDG** [comment]
For anyone who installs Any software or programs, its always a best practice to look through all the directories for anything that was used for the install and delete those files! Its nice if the original programmer puts in some security to check for install files, or have the software delete them automatically after install, but I would never expect it.

**Comment by padams** [comment]
There is something wrong with your install as once OWA is properly installed accessing install.php no longer brings you to the install flow.
