### ISSUE TITLE
IP6 addresses are not being anonymized

### ISSUE THREAD

**Issue by criterion9** [Open-Web-Analytics/Open-Web-Analytics#736]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: 1.7.0

**PHP Version**: 7.4 FPM

**Webserver**: Apache2.4

**Browser**: Chrome 88.0.4324

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [x] Standalone

**Description**  

IPv4 addresses are having the final octet set to 0 as expected when the anonymize IP addresses setting is enabled. IPv6 addresses however do not appear to be saved with a replaced final octet. This should probably be a pretty high priority to address if people are relying on the anonymized IP data as part of their GDPR compliance strategy.

Example IPv6 address:
2001:db8:85a3:8d3:1319:8a2e:370:7348

Same IPv6 anonymized:
2001:db8:85a3::

**How to reproduce**  
Trigger a tracking event across an IPv6 connection.

**Possible Solution**  

Code below anonymizes IPs based on the existence of '.' where IPv6 uses ':'. It should be able to adjust for either type substituting a different "final octet" string if the IP is IPv6.

```
modules/base/classes/trackingEventHelpers.php:309
// Anonymize IP if needed.
         if ( owa_coreAPI::getSetting( 'base', 'anonymize_ips' ) ) {
             if ( $ip && strpos( $ip , '.' ) ) {

                $ip = explode( '.', $ip );
                array_pop($ip);
                $ip = implode('.', $ip);
                $ip .= '.0';
            }
        }
```
**Additional context**

**Comment by padams** [comment]
Merged in #749.
