### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by matthewbaynham** [Open-Web-Analytics/Open-Web-Analytics#737]
**Description**  
Does Open Web Analytics use Cookies?

You would think that in theory I could just look at my website, however I haven't got Open Web Analytics to work yet and I want to just launch my website before fixing the Open Web Analytics.  I've got other things to fix that take priority over this, but cookie warning are a matter of EU law, so the warning is more important than if it actually works or not.

So I need to write my cookie warning now, which means I need to know if Open Web Analytics uses cookies before I fix it.

**Comment by padams** [comment]
Yes it does.
