### ISSUE TITLE
Site not actually tracking

### ISSUE THREAD

**Issue by frodinjon** [Open-Web-Analytics/Open-Web-Analytics#738]
**Description**  

I have OWA installed on a site (https://www.zukmusic.com) which is still being developed, so the tracking code is not on every page at this time. However, I have used several different computers on different internet providers to access the site (and had others do so as well), and the tracking still shows 0 across the board. No results. This is odd, though, because my Firefox has Ghostery installed which does show OWA as a tracker on that site. So, it is registering with Ghostery as a tracker, but the tracking results do not appear anywhere? I'm just confused a bit about this. This is my first site using OWA. Note: I disabled Ghostery when I was trying to verify tracking and I also did not use secondary computers (4 of them) with it or any other tracking blocker installed. Any help/advice would be greatly appreciated. Thanks for the time.
**Example**  

![image](https://user-images.githubusercontent.com/63606954/108534762-5cef2b80-728f-11eb-901f-bd285244d11c.png)
![image](https://user-images.githubusercontent.com/63606954/108534916-8740e900-728f-11eb-94d6-7c5ad564807f.png)

**Comment by padams** [comment]
Please read the troubleshooting page on the wiki and repost with the exact steps you have taken to diagnose the problem.
