### ISSUE TITLE
No consent for cookies

### ISSUE THREAD

**Issue by matthewbaynham** [Open-Web-Analytics/Open-Web-Analytics#739]
If the user does not give their consent for cookies to run then under EU law cookies must not be added.

As an example look how the German government website handles it's cookies https://www.bundesregierung.de/breg-en before consent there is only one cookie that is required for consent because this is necessary for functioning of the website.  If no consent is given there are not more cookies.  Once consent is given then there are more cookies.

So how do I disable OWA cookies until consent is given?

If this means that OWA is totally disabled until consent is given then so be it, as long as there are no cookies beyond what is necessary for the basic functioning of the website (OWA is not part of the basic functioning of the website).

**Comment by padams** [comment]
Just wrap the tracker code in a conditional that checks for presence of a consent cookie that you set.

**Comment by matthewbaynham** [comment]
> Just wrap the tracker code in a conditional that checks for presence of a consent cookie that you set.

Do you have a simple example of how to do that?

**Comment by padams** [comment]
Not handy but it's trival for any JavaScript programmer.
