### ISSUE TITLE
HTTPS on website

### ISSUE THREAD

**Issue by rugk** [Open-Web-Analytics/Open-Web-Analytics#740]
Your website http://www.openwebanalytics.com/ does not support HTTPS.
This is bad, as you should always use HTTPS, e.g. with a free cert by Let's Encrypt.

Why you should always use HTTPS (no matter whether the site is static etc.):
* https://doesmysiteneedhttps.com/
* IT security specialist: https://scotthelme.co.uk/still-think-you-dont-need-https/
* Google: https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

**Comment by padams** [comment]
Thanks

**Comment by rugk** [comment]
Well… it's still HTTP. Should not you keep this issue open until it is resolved?
