### ISSUE TITLE
Tracking different website with single installation.

### ISSUE THREAD

**Issue by josowa** [Open-Web-Analytics/Open-Web-Analytics#741]
**Description**  

Hello There, let's say I installed OWA in a directory of my main webiste mainste.com/owa/ 
I have that tracking code that works.
I have another site anothersite.com in my webhosting service. I created other website and get the respective tracking code.
I visisted anotheriste.com a few times but nothing is being tracked.
Does single installation track online the main site were OWA is installed?

**Example**  

Main site
mainsite.com
Analytics are gathered and showed

Anothersite.com
Another website and track code were created, no data is being logged.

Both sites are in the same hosting service.

Regards.

JP

**Comment by padams** [comment]
If you set the tracking code up correctly it should yes.
