### ISSUE TITLE
Lists subdomain don't exists

### ISSUE THREAD

**Issue by jcubic** [Open-Web-Analytics/Open-Web-Analytics#743]
**Description**
I just wanted to ask question in support mailing list, but the subdomain don't exists.

http://lists.openwebanalytics.com/

**Comment by padams** [comment]
Hasn't existed in a long time. You can post your issue here ass a question. Thanks.

**Comment by jcubic** [comment]
Sorry, it was more than 6 months I don't remember what I was supposed to ask.
