### ISSUE TITLE
No Tracking

### ISSUE THREAD

**Issue by frodinjon** [Open-Web-Analytics/Open-Web-Analytics#744]
I have a website that I am trying to get tracking using the OWA tool. The following are the troubleshooting steps I've taken and I still cannot see any visitors on the reports.
1. Read and confirmed the technical requirements. PHP v 7.4 in use on the site with safe mode off.
2. installed on qualified domain name
3. OWA database user has all privileges
4. owa-config file does use the https now but have tried it with both in a previous installation with the same issue
5. created vendor directory in parent directory

JavaScript (i am using the javascript tracker)
1. owa.tracker-combined-min.js is accessible via the URL in a browser
2. have included the tracking code in the website. Have tried it in the <head> section and in the <body> section and neither work. currently it is in the <head> only.
3. no javascript errors present on inspect tool
4. there are requests made to the log.php
5. response code on log request is 200 so according to troubleshooting doc - all is good
6. tried clearing cookies and accessing the site on a computer that has not accessed it before and still no tracking
7. siteId is correct in the tracking code
8. unsure what this one is - doNotTrack properties. Have used IE, Firefox, Edge, and Chrome, though.

So, those are the troubleshooting steps I've taken so far and I'm still not certain why I can't get any tracking data. Any help or guidance would be greatly appreciated.

**Comment by padams** [comment]
Whe you say you created a vendor directory what do you mean? Did you run composer?

**Comment by frodinjon** [comment]
> 
> 
> Whe you say you created a vendor directory what do you mean? Did you run composer?

I was not sure how to run that, but in another thread someone said they made the folder in their OWA parent folder so that's what I did.

**Comment by padams** [comment]
That's likely your issue. If you checkout the code from GitHub you need to run composer.

If you don't know how to run composer then use the "packaged" tarball attached to the latest release as it includes all the vendor libraries.
