### ISSUE TITLE
Can open web analytics plug-in the users flow tool?

### ISSUE THREAD

**Issue by u2420123** [Open-Web-Analytics/Open-Web-Analytics#745]
Based on Google analytics , it will block files in mainland China, so we tried to use Can open web analytics, but unfortunately it has very few functions. The most important user flow, it is missing. Does anyone know whether user flow can be plugged in or write related modules?

I myself have inquired about another web analytics called matomo It has a user flow tool, but this function must be charged

user flow like this pic
https://i.stack.imgur.com/ji0t1.png

**Comment by padams** [comment]
There is a basic flow report and you can write your own modules as well.
