### ISSUE TITLE
Can I use this to track staff flow though a transaction?

### ISSUE THREAD

**Issue by liquidcms** [Open-Web-Analytics/Open-Web-Analytics#746]
**Description**  
We have a new site where staff go through our ecom site on behalf of clients and complete a product purchase. Occasionally orders are being messed up and it is difficult to repeat what the staff has done to cause the issue (because people rarely do what they said they did). Will OWA allow us to see path through a web site for a specific user?

**Comment by padams** [comment]
Yes. You can see the page view  stream of any session.
