### ISSUE TITLE
All page views being reported as Unique

### ISSUE THREAD

**Issue by peteraylin** [Open-Web-Analytics/Open-Web-Analytics#750]
Hi,
In my Dashboard, every page view is being reported as 'Unique", even though the IP Address is being logged correctly. ie a new Visitor ID is being created for every individual page request. Is there something I need to turn on? I'm using the Javascript API. Any suggestionis would be appreciated. Thanks

**Comment by vishaldhiman** [comment]
Hi,
  This is happening to us too but only on Chrome browser. It's working fine on firefox. Did anyone else had this issue and may have a solution?

**Comment by padams** [comment]
Likely a browser setting issue. the browser is likely setup to reject cookies.
