### ISSUE TITLE
How to Migrate OWA Server

### ISSUE THREAD

**Issue by vishaldhiman** [Open-Web-Analytics/Open-Web-Analytics#751]
**Description**  

We want to move OWA Server from 1 box to another (more hardware). I wanted advice on how to migrate the data including site data and users etc? Can we just setup OWA in the new box and then backup mysql database from old server and restore it to the new one? Please help?

**Example**

**Comment by vishaldhiman** [comment]
Please, does anyone have experience in migrating OWA server to a new machine?

**Comment by padams** [comment]
Yes. just move the filesystem and restore mysql from a dump.
