### ISSUE TITLE
API owa_limit has no effect on result

### ISSUE THREAD

**Issue by zsitro** [Open-Web-Analytics/Open-Web-Analytics#752]
**Description**  
Hi, is it possible that an old version of OWA **1.5.7** doesn't support the limit parameter `owa_limit=2` when retrieveing data from the API? The example call follows the rules from current documentation.

It seems it completely ignores the value, I always receive the same amount of results.

**Example**  
`api.php?owa_apiKey=XXXX&owa_constraints=source%3d%3dqr_code&owa_dimensions=source&owa_startDate=20210301&owa_endDate=20210331&owa_siteId=XXXX&owa_format=json&owa_limit=2&owa_sort=visits-`

```
owa_apiKey=XXXX&
owa_constraints=source%3d%3dqr_code&
owa_dimensions=source&
owa_startDate=20210301&
owa_endDate=20210331&
owa_siteId=XXXX&
owa_format=json&
owa_limit=2&
owa_sort=visits-`
```

Thanks

**Comment by padams** [comment]
It's possible. Can you update to the latest release and try?
