### ISSUE TITLE
Session with multiple visitors

### ISSUE THREAD

**Issue by mariana-s-fernandes** [Open-Web-Analytics/Open-Web-Analytics#754]
**Description**  
When I query the table `owa_action_fact`, 
```
select session_id, count(distinct visitor_id) from owa_action_fact
group by 1
order by 2 desc;
```
I can see that there are different visitors (hundreds of them) with the same session. I checked the data type in case it didn't have enough space for the number, but it does not seem to be the problem. Any ideas why this is happening? By definition, a session should belong to only one visitor, or am I missing something?

**Comment by mariana-s-fernandes** [comment]
Fixed, it was a problem with the domain of the visitor cookie.

**Comment by vishaldhiman** [comment]
@mariana-s-fernandes  Did you fix this by setCookieDomain or something else?

**Comment by mariana-s-fernandes** [comment]
@vishaldhiman I was not the one fixing that at my company so I don't know exactly how it was fixed. But it was happening that the cookie domain was different between pages so it was assigning a different `visitor_id` to the same user every time they switched pages. Hope this helps
