### ISSUE TITLE
log.php Returning 500 Error After Successful Installation 

### ISSUE THREAD

**Issue by WallaceSociety** [Open-Web-Analytics/Open-Web-Analytics#755]
I am having an issue getting the tracking code to work. I have checked the troubleshooter document, however under the log.php 500 response it just states that it was not installed correctly. The install steps are listed below and there is nothing in the logs other than the data telling me it installed the tables correctly.

1. I installed the script by modifying the config file. 
2. I then visited owa/install.php and completed the process and was given a JS tracking code
3. I placed the tracking code in its own js file and inject it into the head tag
4. A request is made to {mydomain.com}/owa/log.php with a whole slew of parameters 
5. Server error 500 occurs

I have also tried to access log.php directly, but also get a server error. 

I am able to log into the admin just fine. 

Thank you in advance for your help.

**Comment by rmarku** [comment]
@WallaceSociety , can you try my simple modification at #763 . On line 71 or 72 of log.php, add at the final a  'c'. The code should look like this:
![imagen](https://user-images.githubusercontent.com/1113370/124131621-5dc27600-da56-11eb-9151-e120103da9fd.png)


It is only a  C at the end of the '%c' chain

**Comment by padams** [comment]
closing as this was fixed in a more recent version.
