### ISSUE TITLE
Issue not reporting site 

### ISSUE THREAD

**Issue by barne77** [Open-Web-Analytics/Open-Web-Analytics#758]
I have installed the software to my website and have used the install which created the DB and allowed me to login to the portal 

I installed to /owa/ directory 

Then i went to GEt tracking Code and copied the Javascript Content.
I pasted this into my site page x.php under the <html> tags but nothing is being reported in the console
I also tried the php one under the <?php area but this stopped the site working completely 

any help

**Comment by padams** [comment]
Please read the troubleshooting guide on the wiki. It's impossible to tell if you have encountered a bug or if it's an issue with your server environment. Feel free to reopen with the necessary info.
