### ISSUE TITLE
Import Google Analytics

### ISSUE THREAD

**Issue by SLCPS** [Open-Web-Analytics/Open-Web-Analytics#759]
Ability to import Google Analytics (UA- properities) so you can view all your web analytics data in Open Web Analytics.

**Comment by padams** [comment]
Not sure exactly what you want to import but it's unlikely the data modules would or granularity would match. Feel free to reopen with a more specific request.

**Comment by SLCPS** [comment]
If someone wanted to get away from Google Analytics, but didn't want to lose all that juicy data, importing it would be key.  This feature is something you can do in Matomo 
https://matomo.org/docs/google-analytics-importer/
Because of google limitations with how much you can export within a timeframe, Matomo does it in batches.

Regarding OWA, I assumed if you could send data "to" google analytics, that the opposite could be done.

**Comment by padams** [comment]
I'm not 100% but I believe matmoto is importing summary data. OWA does not use disconnected summaries. All statistics are built off of observed fact events created by OWA's tracker clients. That's just how the OWA data model works. There is just no places  to import that kind of disconnected summary data.
