### ISSUE TITLE
Installation not possible: OWA not defined

### ISSUE THREAD

**Issue by piiskop** [Open-Web-Analytics/Open-Web-Analytics#762]
**Before you open an issue:**

- [ x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x ] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: SVN-TRUNK

**PHP Version**: 7.4.3 (cli)

**Webserver**: Apache/Nginx

**Browser**: Chrome 91.0.4472.77 (Official Build) (64-bit)

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [ x] Standalone

**Description**  

After loading _install.php_, clicking _Let's Get Started..._ doesn't do anything. Further investigation brings to ECMAScript error message:
```
install.php?owa_action=base.installCheckEnv:15 Uncaught ReferenceError: OWA is not defined
    at install.php?owa_action=base.installCheckEnv:15
```
**How to reproduce**  
1. Follow the [instructions for getting OWA](http://www.openwebanalytics.com/download/)!
2. Configure your web server to serve OWA!
3. Run _install.php_!
4. Click the yellow button with the text _Let's Get Started..._!
5. Experience that no installation process starts and an ECMAScript error will be printed into the console of the browser instead!

**Possible Solution**  

**Additional context**

**Comment by AlphaDG** [comment]
Did you look at that file, on line 15 and see what it is trying to do?? Short of purchasing software, this is github, and a lot of code here is not plug 'n play. You should have some basic knowledge of code, and don't expect it to just run every time.

**Comment by piiskop** [comment]
I don't know which file to look into. I tested out _trunk_ version in another machine and after visiting http://owa-svn:2, it redirected to http://owa-svn:2/index.php?owa_action=base.updates& and the result was:

> This page isn’t workingowa-svn redirected you too many times.
> Try clearing your cookies.
> ERR_TOO_MANY_REDIRECTS

Please don't make me fix a software that I haven't written. Github version works fine although I discovered that OWA doesn't do its job well, for instance, I can't even find a log of visits with exact times.
