### ISSUE TITLE
Track multiple Wordpress sites from one OWA instance and still use the plugin

### ISSUE THREAD

**Issue by jgarruba** [Open-Web-Analytics/Open-Web-Analytics#764]
I have multiple Wp sites I want to run one instance of OWA. But it seems the only documented way to use OWA with the wp plugin that automatically adds the tracking code setting to WP is to do a full install in the WP plugins folder of each site.  

I have OWA setup as a stand alone instance and i want to add just the features of the plugin that add the menu links to WP and the tracking code setup page in WP. 

Is this possible. Or do i have to manually add the tracking code to each site. 

I don't want an unused instance of OWA siting on each site just to get the setting i need. there should be a plugin only install for WP.

**Comment by padams** [comment]
You can and should use the new official WordPress plugin to do this. It's installable via the WordPress plugin repo and also has it's own GitHub and install docs:

https://github.com/Open-Web-Analytics/owa-wordpress-plugin/wiki
