### ISSUE TITLE
Apache-error: H01071: Got error 'PHP message: PHP Warning:  Illegal string offset 'siteid'

### ISSUE THREAD

**Issue by Vivimagic** [Open-Web-Analytics/Open-Web-Analytics#765]
**Before you open an issue:**

**Affected Version(s)**: WordPress 5.7.2

**PHP Version**: 7.3 FPM

**Webserver**: GoDaddy WordPress. 

**Browser**: 91.0.4472.124 (Official Build) (64-bit)

**Installation Type** WordPress Zip 1.7.1

- [ ] Wordpress Open-Web-Analytics-1.7.1

**Description**  
Getting an apache error. 

[Tue Jul 06 06:25:08.844006 2021] [proxy_fcgi:error] [pid 46315] [client redacted] AH01071: Got error 'PHP message: PHP Warning:  Illegal string offset 'siteid' in /home/storm/sites/infiled-tech/public/wp-content/plugins/open-web-analytics-plugin/openwebanalyticsplugin.php on line 228PHP message: PHP Warning:  Illegal string offset 'owa_host' in /home/storm/sites/iwebsitename/public/wp-content/plugins/open-web-analytics-plugin/openwebanalyticsplugin.php on line 233PHP message: PHP Warning:  Illegal string offset 'owa_host' in /home/storm/sites/websitename/public/wp-content/plugins/open-web-analytics-plugin/openwebanalyticsplugin.php on line 234PHP message: PHP Warning:  Illegal string offset 'owa_baseurl' in /home/storm/sites/websitename/public/wp-content/plugins/open-web-analytics-plugin/openwebanalyticsplugin.php on line 234PHP message: PHP Warning:  Illegal string offset 'siteid' in /home/storm/sites/websitename
[apache-error (2).log](https://github.com/Open-Web-Analytics/Open-Web-Analytics/files/6775567/apache-error.2.log)
/public/wp-content/plugins/open-web-analytics-plugin/openwebanalyticsplugin.php on line 239'

**How to reproduce**  
No to sure how to reproduce. I do have a text file with the errors if required. 

**Possible Solution**  

**Additional context**

**Comment by padams** [comment]
That plugin is not part of the OWA distribution.
