### ISSUE TITLE
Dom Streams player does not play records from other domains 

### ISSUE THREAD

**Issue by Dzhenzherya** [Open-Web-Analytics/Open-Web-Analytics#766]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: git->master(07/07/2021)

**PHP Version**: 7.4 FPM

**Webserver**: Apache

**Browser**: Chrome 91.0.4472.124

**Installation Type**

- [x] Standalone

**Description**  

I have three sites on different domains:
firstSite.com
secondSite.com
thirdSite.com
<img width="554" alt="error1" src="https://user-images.githubusercontent.com/8728095/124829833-ce4f2280-df81-11eb-9076-3681f3e6add5.png">

Open Web Analytics installation:
owa.firstSite.com

I have an error in the domstreams player on the site:
secondSite.com
thirdSite.com
<img width="621" alt="2" src="https://user-images.githubusercontent.com/8728095/124829892-dc9d3e80-df81-11eb-84fd-50d16950902e.png">

When I press the play button, nothing happens. In chrome console script error: "Failed to load resource: the server responded with a status of 401 (Unauthorized)"
<img width="134" alt="3" src="https://user-images.githubusercontent.com/8728095/124829912-e2931f80-df81-11eb-943d-fedecdf4fafd.png">
<img width="1120" alt="4" src="https://user-images.githubusercontent.com/8728095/124829920-e4f57980-df81-11eb-9ceb-cab8bdff91ab.png">

Then I copied owa.firstSite.com to owa.secondSite.com with one database and changed the tracking code to owa.secondSite.com After that the player started working.

**Additional context**  

00:19:54 2021-07-08 93776 [debug_log] check for http host
00:19:54 2021-07-08 93776 [debug_log] Setting cookie domain to .firstSite.com
00:19:54 2021-07-08 93776 [debug_log] *** Starting Open Web Analytics vmaster. Running under PHP v7.4.3 (Linux) ***
00:19:54 2021-07-08 93776 [debug_log] Request URL:GET /api/?owa_jsonpCallback=jQuery164009863371023710865_1625692793824&owa_siteId=6c61d678fea34b416107cec429396d8c&owa_period=last_seven_days&owa_action=domstreams&owa_domstream_guid=1625689017818832471&owa_module=domstream&owa_version=v1&_=1625692793828
00:19:54 2021-07-08 93776 [debug_log] User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36
00:19:54 2021-07-08 93776 [debug_log] Host: firstSite.com
00:19:54 2021-07-08 93776 [debug_log] check cache file: /var/www/firstSite.com/owa-data/caches/1/owa_configuration/fafe1b60c24107ccd8f4562213e44849.php
00:19:54 2021-07-08 93776 [debug_log] CACHE HIT (Cold) - Retrieved Object from Cache File - Collection: owa_configuration, id: fafe1b60c24107ccd8f4562213e44849
00:19:54 2021-07-08 93776 [debug_log] Caller configuration overrides applied.
00:19:54 2021-07-08 93776 [debug_log] request container says params are:
00:19:54 2021-07-08 93776 [debug_log] Array
(
    [owa_jsonpCallback] => jQuery164009863371023710865_1625692793824
    [owa_siteId] => 6c61d678fea34b416107cec429396d8c
    [owa_period] => last_seven_days
    [owa_action] => domstreams
    [owa_domstream_guid] => 1625689017818832471
    [owa_module] => domstream
    [owa_version] => v1
    [_] => 1625692793828
)

00:19:54 2021-07-08 93776 [debug_log] Modules present are:
00:19:54 2021-07-08 93776 [debug_log] Array
(
    [2] => base
    [3] => domstream
    [4] => hello
    [6] => maxmind_geoip
    [7] => remoteQueue
    [8] => visitor_map
)

00:19:54 2021-07-08 93776 [debug_log] Filtering register_build_package
00:19:54 2021-07-08 93776 [debug_log] Filtering register_build_package
00:19:54 2021-07-08 93776 [debug_log] Filtering register_build_package
00:19:54 2021-07-08 93776 [debug_log] base Schema version is 10
00:19:54 2021-07-08 93776 [debug_log] base Required Schema version is 10
00:19:54 2021-07-08 93776 [debug_log] domstream Schema version is 1
00:19:54 2021-07-08 93776 [debug_log] domstream Required Schema version is 1
00:19:54 2021-07-08 93776 [debug_log] maxmind_geoip Schema version is 1
00:19:54 2021-07-08 93776 [debug_log] maxmind_geoip Required Schema version is 1
00:19:54 2021-07-08 93776 [debug_log] visitor_map Schema version is 1
00:19:54 2021-07-08 93776 [debug_log] visitor_map Required Schema version is 1
00:19:54 2021-07-08 93776 [debug_log] hello Schema version is 1
00:19:54 2021-07-08 93776 [debug_log] hello Required Schema version is 1
00:19:54 2021-07-08 93776 [debug_log] check cache file: /var/www/firstSite.com/owa-data/caches/1/owa_site/ada225d731f664da45e27461bffacc16.php
00:19:54 2021-07-08 93776 [debug_log] CACHE HIT (Cold) - Retrieved Object from Cache File - Collection: owa_site, id: ada225d731f664da45e27461bffacc16
00:19:54 2021-07-08 93776 [debug_log] CACHE HIT (Warm) - Retrieved Object from Cache - Collection: owa_site, id: ada225d731f664da45e27461bffacc16
00:19:54 2021-07-08 93776 [debug_log] Getting state - store: u key:
00:19:54 2021-07-08 93776 [debug_log] Notifying listeners of init
00:19:54 2021-07-08 93776 [debug_log] no listeners registered for this event type.
00:19:54 2021-07-08 93776 [debug_log] EHS: Responses - Array
(
)

00:19:54 2021-07-08 93776 [debug_log] EHS: Event was handled successfully by all handlers.
00:19:54 2021-07-08 93776 [debug_log] Handling request with params: Array
(
    [jsonpCallback] => jQuery164009863371023710865_1625692793824
    [siteId] => 6c61d678fea34b416107cec429396d8c
    [period] => last_seven_days
    [do] => domstreams
    [domstream_guid] => 1625689017818832471
    [module] => domstream
    [version] => v1
)

00:19:54 2021-07-08 93776 [debug_log] Generating REST API route controller...
00:19:54 2021-07-08 93776 [debug_log] Array
(
    [class_name] => owa_domstreamsRestController
    [file] => /var/www/firstSite.com/modules/domstream/controllers/domstreamsRestController.php
    [conf] => Array
        (
        )

)

00:19:54 2021-07-08 93776 [debug_log] Performing Action: owa_domstreamsRestController
00:19:54 2021-07-08 93776 [debug_log] Getting state - store: u key:
00:19:54 2021-07-08 93776 [debug_log] Could not find any credentials to authenticate with.
00:19:54 2021-07-08 93776 [debug_log] Filtering auth_status
00:19:54 2021-07-08 93776 [debug_log] Assembling view: owa_restApiView
00:19:54 2021-07-08 93776 [debug_log] Total session time: 0.015082120895386
00:19:54 2021-07-08 93776 [debug_log] Goodbye from OWA
00:19:54 2021-07-08 93776 [debug_log] starting to persist cache...
00:19:54 2021-07-08 93776 [debug_log] There seem to be no dirty objects in the cache to persist.
00:19:54 2021-07-08 93776 [debug_log] Cache Statistics:
00:19:54 2021-07-08 93776 [debug_log] There seem to be no dirty objects in the cache to persist.
00:19:54 2021-07-08 93776 [debug_log] Cache Statistics:
                          Total Hits: 3 (Warm/Cold: 1/2)
                          Total Miss: 0
                          Total Added to Cache: 0
                          Total Replaced: 0
                          Total Persisted: 0
                          Total Removed: 0

**Comment by padams** [comment]
This should be fixed in the latest version of OWA.
