### ISSUE TITLE
Attribution Model modes: direct or original 

### ISSUE THREAD

**Issue by petsoukos** [Open-Web-Analytics/Open-Web-Analytics#768]
**Description**  
I'd like to know more about the attribution model. It seems it supports two modes, direct, and original. Where can I find more information about this?

**Example**

**Comment by petsoukos** [comment]
I actually found in the Wiki [page](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Campaign-Tracking#traffic-attribution) what I was looking for.

Also after much fiddling around the source code I think I found how to switch modes when using the async tracker code
```
<script type="text/javascript">
//<![CDATA[
var owa_baseUrl = 'http://your.domain.com/path/to/owa/';
var owa_cmds = owa_cmds || [];

// HERE ??
owa_cmds.push(['OWATracker.setOption', 'trafficAttributionMode', 'original']); // defaults to 'direct'

owa_cmds.push(['setSiteId', 'your_site_id']);
owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);
owa_cmds.push(['trackDomStream']);

(function() {
	var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
	_owa.src = owa_baseUrl + 'modules/base/js/owa.tracker-combined-min.js';
	var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
}());
//]]>
</script>
```
Is this the correct way? Is it placed correctly? Should I place it before or after the setSiteId command? Because I couldn't find any other documentation on how to set other tracker options other than modifying the source script and building it every time.

**Comment by Dzhenzherya** [comment]
I would like to know the difference from 'original' and 'direct'

owa_cmds.push(['setOption', 'trafficAttributionMode', 'original']);

**Comment by padams** [comment]
Look right. Order doesn't matter so long at it's Devore the track... methods.

**Comment by padams** [comment]
And I don't think you need to specify the OWATracker object. Just the setOption method name.
