### ISSUE TITLE
php and JS

### ISSUE THREAD

**Issue by daemon-byte** [Open-Web-Analytics/Open-Web-Analytics#770]
Hi,

I was wondering if there's a way of doing both JS and PHP together and the system recognising the user and combining the results so people don't trigger double records?

**Comment by padams** [comment]
Yes as log as you run OWA on the same server as your PHP. Basically they just have to be serving from the same domain and share a db.

**Comment by daemon-byte** [comment]
So if my webserver is a different server to my OWA server I can't use the php method or I can but the JS and php methods would not sync?

**Comment by padams** [comment]
This is what the owa-php-sdk is for. It's a completely separate module in its own repository that allows you to use the OWA php tracker as a library in your php application. 

The php tracker will sends the tracking requests just like the js tracker does to a standalone OWA server. 

Check out that repo and files issues there if you run into issues!

**Comment by daemon-byte** [comment]
ok thanks
