### ISSUE TITLE
1GB Webpage, 9GB Stats

### ISSUE THREAD

**Issue by BlutVampir** [Open-Web-Analytics/Open-Web-Analytics#771]
**Description**  
I have a small WordPRess Website, which uses OWA. We analyse the traffic of the past 3 month or so, not further back. The OWA needs around 9 GB on the drive now, but was only running for around a year.

How can I clean up old visitor data or archive it somehow? Mantomo had such a feature, to consolidate data (see only overview statistics but no details anymore) or to completly delete the data.

Are such features existing? Could they be added? Otherwise I need to reinstall the OWA again and again to clean up the space and directories.

**Comment by padams** [comment]
It's on the roadmap. Right now you'd have to truncate the fact tables (request, session, action) by date.

**Comment by jcubic** [comment]
Any instructions how to do this? This should be in the Wiki.
