### ISSUE TITLE
New password mail notification not sent.

### ISSUE THREAD

**Issue by hcuevas** [Open-Web-Analytics/Open-Web-Analytics#772]
**Before you open an issue:**

- [X] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [X] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: 1.7.1

**PHP Version**: 7.3.27 FPM

**Webserver**: Nginx

**Installation Type**

- [X] Standalone

**Description**  

The mail for "Change password for this user" displays a "Success" message, but it's never delivered.

**How to reproduce**  

Select a user from "Settings > User management > Edit > 'Change password for this user' "
Enter an e-mail address

**Possible Solution**  

As per the log message, setting the "From" field may be related

**Additional context**  

Enabling the debug option, the log (owa/owa-data/logs) shows:

XX:XX:XX 2021-07-29 18476 [debug_log] Mailer Failure. Was not able to send with subject of 'Your New OWA Password'. Error Msgs: 'Invalid address:  (From): root@localhost'

**Comment by padams** [comment]
Are you running OWA under localhost?

**Comment by hcuevas** [comment]
Yes, indeed.

**Comment by padams** [comment]
Running under localhost will affect the cookies which require a FQDN. As for the mail, that's a php/server setup issue. You need ot get php's native mail() method to hand off to an MTA using a local sendmail or an SMTP agent.
