### ISSUE TITLE
owa isn't registering my event

### ISSUE THREAD

**Issue by daemon-byte** [Open-Web-Analytics/Open-Web-Analytics#774]
For long reasons I'm trying to create my own request to OWA from php and to do it I'm trying to mimic the call the JS script would make. for testing I'm just using curl from the php server. I'm getting a 200 and a gif image but nothing is being registered on OWA. I checked the logs and the only strange thing I found was this message below but no helpful information on how to figure out the problem. Anyone able to point me in the right direct would be great. 

**url I'm calling:** /log.php?owa_event_type=base.page_request&owa_timestamp=1628102267&owa_visitor_id=1628084115496591168&owa_fsts=1628101990&owa_dsfs=0&owa_last_req=1628101990&owa_session_id=1628084115702798979&owa_nps=0&owa_medium=direct&owa_source=%28none%29&owa_search_terms=%28none%29&owa_session_referer=%28none%29&owa_site_id=a743f3777a1edd6f7e8a1a48c4b5ed96&owa_page_url=http%3A%2F%2Fowa.portal-branch.hr-zcs.com%2Fen%2Fanniversary&owa_HTTP_REFERER=http%3A%2F%2Fowa.portal-branch.hr-zcs.com%2Fen&owa_page_title=At+a+glance

**extraction from log**
20:56:03 2021-08-04 41558 [debug_log] EHS: Event was not handled successfully by some handlers. 
20:56:03 2021-08-04 41558 [debug_log] Array
(
    [0] => owa_dbEventQueue
    [1] => /opt/owa/modules/base/classes/dbEventQueue.php
)
[errors_5ea97392452bfe164db1c833ace7940f.txt](https://github.com/Open-Web-Analytics/Open-Web-Analytics/files/6933825/errors_5ea97392452bfe164db1c833ace7940f.txt)

**Comment by padams** [comment]
That's what the the owa-php-sdk is for. It's in a separate repo.

**Comment by daemon-byte** [comment]
> That's what the the owa-php-sdk is for. It's in a separate repo.

which would be great except it doesn't do what I want. The website sits behind varnish so if I just run the sdk on page load it will miss most of my visits. If I rely on Javascript I'm going to lose count to DNT, blockers etc. So I needed a reliable way to obtain good figures, while still respecting GDPR and privacy. The solution I came up with was this. Every page triggers an ajax call to a status url. So it knows if the person is logged in or not, if there's any news to put in the ticker etc. So I'm passing some basic data such as page url along with that status request call. In the php that handles that request I'm creating the call to OWA putting in more or less data depending upon which switches the user has agreed to in my privacy popup. 

From what I can see in this SDK I can't change the ip, user agent or page url. So All OWA will have is 100% of visits all to 1 page from 1 ip. Although it might be worth me looking into potentially forking it and adding in the options I need. That might be the quicker path and then there's always the option of contribing it back if anyone else is interested in it. Unless you know of some way to do this already?

**Comment by padams** [comment]
I'm not following. If you are already resigned to use JS to initiate an Ajax call then why are you worried about the OWA js client making its own call?

DNT signal is a verrrry low percentage. And I'm not aware of a blocker that blocks OWA running in a first party implementation.

**Comment by daemon-byte** [comment]
A few reasons. A stakeholder had a chrome extension that blocked it because the filename contained the word "tracker" and that spooked him. Another one had the DNR turned on and that spooked her. So they already distrust that method. But the biggest issue is the legal team and the lack of control on the data OWA processes. Under GDPR we have to request their permission to process and/or any personal data of the user. If that user denies it (as most do because every hits the reject all button) they believe we can not do any processing or storing of the user data. This would include things like IP and user agent. We could also not store cookies on their machine to track them. However I have no control over that so I have to turn off owa for those users and then we're back to the incomplete data we now have with GA. Maybe the legal team are wrong on their interpretation of GDPR but there's absolutely no way I'm sticking myself on the line by ignoring their recommendations. Hence this convoluted work around where I had control over what does and doesn't get sent to OWA on a per user basis and what alternative data I want to fill in.

**Comment by padams** [comment]
Yeah I hear you but OWA is not a third party data processor. It's a library that's part of your app like WordPress is a part of your website if you have a blog.

You can control what OWA records to the DB and drop any data element by simply writing a server side filter for the param. You can probably even filter the GET request via JavaScript if you really wanted to drop something before it hits the server.

Also, if you don't like the name "tracker" then just rename the file and its reference.

I think trying to reimplement OWA's internals using your own custom JS client is a can of worms. You might get it working now but it will certainly break over time and very few people are likely to help you troubleshoot something custom like that. Best to stick with the API and SDKs and filter.

**Comment by daemon-byte** [comment]
Yeh. I didn't know about this SDK, only the php stuff that's in the main repo and that didn't work well for me at all and I was trying hard to avoid doing any changes to the OWA server itself :) I will play around with the SDK tomorrow and maybe that will lead me to a better solution than the janky mess I currently have :) Thanks for the help
