### ISSUE TITLE
Heatmap - Check API key or permissions for this user.

### ISSUE THREAD

**Issue by fapth** [Open-Web-Analytics/Open-Web-Analytics#776]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: 1.7.1

**PHP Version**: 7.2.24 FPM

**Webserver**: Apache

**Browser**: Chrome 80. / Vivalid and Firefox

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [x] Standalone

**Description**  

I started the Heatmap Report and getting this error. There is also no Heatmap to see.:

**Error: 401 Check API key or permissions for this user.**

URL: api/index.php?owa_jsonpCallback=jQuery... 

When i copy the link and open it in a Browsertab I cann see a json.

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by padams** [comment]
This was refactored quite a bit in 1.7.3.
