### ISSUE TITLE
Remove dependency for emails for create new account & change password

### ISSUE THREAD

**Issue by vishaldhiman** [Open-Web-Analytics/Open-Web-Analytics#777]
Currently, emails need to be working for creating new account & resetting passwords. This dependency is a blocker for us as setting up emails is complicated. If we can remove this dependency, this can be a much better product.

Allow admin users to create new users with their passwords. Also allow admin users to change other user's passwords.

**Comment by padams** [comment]
Please see the CLI docs for changing the password of a user. https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Command-Line-Interface-(CLI)#change-password
