### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [Open-Web-Analytics/Open-Web-Analytics#778]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by padams** [comment]
Good idea. In the meantime you can message me privately.

**Comment by amammad** [comment]
dear padam, I am Amammad who reports security vulnerabilities in Huntr platform, Can I ask you create a SECURITY.md file or give a contact way such email to huntr team please?
You can also signup on huntr.dev website and from reports section, you can see all reports related to your repositories.

best regards.

**Comment by padams** [comment]
There is an email address on the repo. You can send there for now.

**Comment by amammad** [comment]
Hello dear we try to find the email but can't found anything? 
can you please give us a email?

**Comment by padams** [comment]
You can't be looking very hard then. 

https://github.com/Open-Web-Analytics

**Comment by amammad** [comment]
Ahhh 
I looking into website, the whole repo and your profile but noting there and I miss this one.
thanks.
