### ISSUE TITLE
Log.php 406 ERROR (HELP pls)

### ISSUE THREAD

**Issue by Matheusupbr00** [Open-Web-Analytics/Open-Web-Analytics#784]
- [X] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [X] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: 1.7.2

**PHP Version**: 7.3 / 7.4

**Webserver**: Apache/Nginx

  **Browser**: Versão 93.0.961.52 (Compilação oficial) (64 bits) / Chrome 94 (94.0.4606.50)

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [X] Standalone

**Description**  

my site does not receive tracking data, it shows an error in the Log.php file which is returning error 406

**How to reproduce**  
Acess macrocar.com.br

**Possible Solution**  
????? help

**Additional context**  

![image](https://user-images.githubusercontent.com/12530731/134256417-aaee423d-0c9e-45e0-b8cb-52efeb834337.png)
![image](https://user-images.githubusercontent.com/12530731/134256475-6f1c626e-fd79-48c4-8857-6a0c73f3b1ec.png)
![image](https://user-images.githubusercontent.com/12530731/134256488-b1afc438-a312-48c4-811e-47cf9ab19e99.png)

**Comment by padams** [comment]
That error doesn't tell us much. You need to put OWA into debug mode and look in the error log. Please read the troubleshooting guide and reopen with the necessary debug info.
