### ISSUE TITLE
Graph no update correctly

### ISSUE THREAD

**Issue by angerangel** [Open-Web-Analytics/Open-Web-Analytics#785]
The graph on the main page does't show more than 2 moths. I updated the range to this year, but I get just the last 2 months:

![IScreenshot]( http://www.rometec.it/temp/dashboards.jpg  )

**Affected Version(s)**: 1.6.4
**PHP Version**: 7
**Webserver**: Apache
**Browser**: Chrome

**Comment by padams** [comment]
I can't reproduce this. Please update to the latest version of OWA and see if you still have problem.  Also, if you want help you will have to post debug info such as any JavaScript errors etc. see the troubleshooting page on the wiki.
