### ISSUE TITLE
Can you generate PDF with report?

### ISSUE THREAD

**Issue by jcubic** [Open-Web-Analytics/Open-Web-Analytics#789]
**Description**
I was asked to generate PDF from Google Analytics from my website, and I wanted to reply that I don't use GA but OWA. Does the library support the generation reports in PDF? So I can set PDF from OWA instead of GA?

If something like this doesn't exist maybe you can guide me on how to create something like this?
Maybe I will find some free time to actually implement a solution for this.

**Comment by padams** [comment]
Hard to say as the reports are mostly generated client side. Feel free to open an enhancement ticket if you do figure out a way forward.
