### ISSUE TITLE
Status Code: 406 

### ISSUE THREAD

**Issue by gituncar** [Open-Web-Analytics/Open-Web-Analytics#791]
**Description**  
I installed on hostgator Open Web Analytics 1.7.3, via softacolous, I added my website and on 1 html I added tracking tag. But I can see reports. I get error 406 on log.php

I enable debugging, attached file. But I don't know what happening.

**Example**  
Request URL: https://owa.solucionespetabyte.com/log.php?owa_timestamp=1637353918&owa_event_type=base.page_request&owa_visitor_id=1637352793527830092&owa_fsts=1637352793&owa_dsfs=0&owa_last_req=1637353903&owa_session_id=1637352794662679653&owa_nps=0&owa_dsps=0&owa_medium=direct&owa_source=%28none%29&owa_search_terms=%28none%29&owa_session_referer=%28none%29&owa_site_id=3d9c7523b2bdc1713c4fa70a44d98ae0&owa_page_url=https%3A%2F%2Fsolucionespetabyte.com%2Flinkbio.html&owa_HTTP_REFERER=&owa_page_title=TIMID0x&
Request Method: GET
Status Code: 406 
Remote Address: 192.254.189.166:443
Referrer Policy: strict-origin-when-cross-origin

[errors_fda3c1cb5de7bb9dbb9ce8c6dad3db6c.txt](https://github.com/Open-Web-Analytics/Open-Web-Analytics/files/7572919/errors_fda3c1cb5de7bb9dbb9ce8c6dad3db6c.txt)

**Comment by padams** [comment]
406 status code is very likely a server configuration issue. Feel free to update the ticket if you figure out what might be causing this.

**Comment by rahulsharmaah** [comment]
Hye did you figure out the issue i am also facing the same issue

**Comment by itpundit** [comment]
You can not believe that issue is because we are using owa_session_id in get url which is not supported from server because of mod_security perhaps and the another issue is of page_title need to be encodedURIComponent

enjoy

**Comment by rahulsharmaah** [comment]
@itpundit 😅😅Thank you for your response hope it works fine now

**Comment by rahulsharmaah** [comment]
@itpundit 😅😅Thank you for your response hope it works fine now
