### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by Gyrene251** [Open-Web-Analytics/Open-Web-Analytics#792]
Trying to reset my password but it does not appear to recognize the change. Unable to login to my stats.

https://www.vmfa251.org/stats/

Any suggestions appreciated.

Browsers used Edge, Chrome and Firefox, Server is Apache, PHP version is 7.X
**Before you open an issue:**

- [ ] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [ ] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: x.y.z

**PHP Version**: 7.x FPM

**Webserver**: Apache/Nginx

**Browser**: Chrome 80.x.x

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [x] Standalone

**Description**  

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by padams** [comment]
Please read the troubleshooting guide on the wiki. It's impossible to diagnose if this is a legit bug or an issue with your server environment. Feel free to reopen with the necessary debug info.
