### ISSUE TITLE
User Roll Analyst Has no access to adding a website or getting the code

### ISSUE THREAD

**Issue by JoshWho** [Open-Web-Analytics/Open-Web-Analytics#793]
How can this be set to allow users to add their own site and copy their own tracking code without giving them full admin rights?

**Comment by padams** [comment]
Right now only an admin can add sites. You can alter the user role/capability scheme using methods in your config file. see: https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/User-Permissions
