### ISSUE TITLE
Why all the runarounds?

### ISSUE THREAD

**Issue by JoshWho** [Open-Web-Analytics/Open-Web-Analytics#796]
Why doesn't the Download just have to full complete version as the tarball? 

Every answer on here is the same "Look at the wiki". Maybe if the project was put together correctly people wouldn't repeat these questions.

Why can't this be a normal git project where we can clone and run git pull? 

These instruction about the tarball should be on the first page of the project and not in the wiki. The wiki is for further details not for basic installation.

I can see why so many r frustrated here. I am browsing through all the closed tickets with every answer "check the Wiki" and not even a link to where in the wiki for the question.

**Comment by JoshWho** [comment]
This is great project but it does drive up a factor for anyone that needs help, for something that could be as simple as (Example)check the config for https etc...

**Comment by padams** [comment]
Because that's not how GitHub release tarballs work and we don't store the vendor directory in the repo. 

You can always clone the repo and run composer. The presence of the composer.json file is the tip off.

**Comment by JoshWho** [comment]
I understand iit but I think many others do not is all I am saying. I am skimming through for some real techy kind of questions and mainly all I see is common user error ones. Just saying could avoid all of that if it was instructed and organised better.

I love the project, and I see a huge future to this.

**Comment by JoshWho** [comment]
So far I have made a ton of little tweaks here and there and I can really see this being big.

**Comment by padams** [comment]
Feel free to clone the wiki and suggest changes to the docs. Also, happy to look at any pull requests.
