### ISSUE TITLE
How can i delete site via REST API??

### ISSUE THREAD

**Issue by JKwang00** [Open-Web-Analytics/Open-Web-Analytics#797]
I tried to it. but can't
how can i delete site??

$curl = curl_init();
curl_setopt($curl, CURLOPT_URL, "http://MyDomain.com/plugin/OpenWebAnalytics/api/base/v1/sites/");
curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode(["owa_siteId" => $owaSiteId]));
curl_setopt($curl, CURLOPT_DELETE, true);
curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "DELETE");
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
$headers = array(
   "x-api-key:fd323bb373c81d7b6784e8fbcc15ca46",
);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);
//for debug only!
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);

$resp = curl_exec($curl);
curl_close($curl);
var_dump($resp);

**Comment by padams** [comment]
Please read the troubleshoot guide on the wiki.No one can possibly help diagnose a bug with our seeing your full http headers and response codes. Feel free to reopen once you read the guide and provide that info.
