### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by krzimmer** [Open-Web-Analytics/Open-Web-Analytics#798]
**Affected Version(s)**: 1.7.2

**PHP Version**: 7.2 FPM

**Webserver**: Nginx

**Browser**: FF 95, Safari 15.1

**Installation Type**
- [X] Standalone

**Description**  
When attempting to login, 502 Bad Gateway error is received. Previous logins were successful.

**How to reproduce**  
Not sure. This error occurs after a number of successful previous logins. 

**Possible Solution**  
Clearing cookies and site data resolves the issue. 

**Additional context**  
URL Requested: https://pushpullpixel.com/owa/index.php
URL Returned: https://pushpullpixel.com/owa/index.php?owa_do=base.loginForm&owa_go=https%3A%2F%2Fpushpullpixel.com%2Fowa%2Findex.php%3Fowa_do%3Dbase.loginForm%26owa_go%3Dhttps%253A%252F%252Fpushpullpixel.com%252Fowa%252Findex.php%253Fowa_do%253Dbase.loginForm%2526owa_go%253Dhttps%25253A%25252F%25252Fpushpullpixel.com%25252Fowa%25252Findex.php%25253Fowa_do%25253Dbase.loginForm%252526owa_go%25253Dhttps%2525253A%2525252F%2525252Fpushpullpixel.com%2525252Fowa%2525252Findex.php%2525253Fowa_do%2525253Dbase.loginForm%25252526owa_go%2525253Dhttps%252525253A%252525252F%252525252Fpushpullpixel.com%252525252Fowa%252525252Findex.php%252525253Fowa_do%252525253Dbase.loginForm%2525252526owa_go%252525253Dhttps%25252525253A%25252525252F%25252525252Fpushpullpixel.com%25252525252Fowa%25252525252Findex.php%25252525253Fowa_do%25252525253Dbase.loginForm%252525252526owa_go%25252525253Dhttps%2525252525253A%2525252525252F%2525252525252Fpushpullpixel.com%2525252525252Fowa%2525252525252Findex.php%2525252525253Fowa_do%2525252525253Dbase.loginForm%25252525252526owa_go%2525252525253Dhttps%252525252525253A%252525252525252F%252525252525252Fpushpullpixel.com%252525252525252Fowa%252525252525252Findex.php%252525252525253Fowa_do%252525252525253Dbase.loginForm%2525252525252526owa_go%252525252525253Dhttps%25252525252525253A%25252525252525252F%25252525252525252Fpushpullpixel.com%25252525252525252Fowa%25252525252525252Findex.php%25252525252525253Fowa_do%25252525252525253Dbase.loginForm%252525252525252526owa_go%25252525252525253Dhttps%2525252525252525253A%2525252525252525252F%2525252525252525252Fpushpullpixel.com%2525252525252525252Fowa%2525252525252525252Findex.php%2525252525252525253Fowa_do%2525252525252525253Dbase.loginForm%25252525252525252526owa_go%2525252525252525253Dhttps%252525252525252525253A%252525252525252525252F%252525252525252525252Fpushpullpixel.com%252525252525252525252Fowa%252525252525252525252Findex.php%252525252525252525253Fowa_do%252525252525252525253Dbase.loginForm%2525252525252525252526owa_go%252525252525252525253Dhttps%25252525252525252525253A%25252525252525252525252F%25252525252525252525252Fpushpullpixel.com%25252525252525252525252Fowa%25252525252525252525252Findex.php%25252525252525252525253Fowa_do%25252525252525252525253Dbase.loginForm%252525252525252525252526owa_go%25252525252525252525253Dhttps%2525252525252525252525253A%2525252525252525252525252F%2525252525252525252525252Fpushpullpixel.com%2525252525252525252525252Fowa%2525252525252525252525252Findex.php%2525252525252525252525253Fowa_do%2525252525252525252525253Dbase.loginForm%25252525252525252525252526owa_go%2525252525252525252525253Dhttps%252525252525252525252525253A%252525252525252525252525252F%252525252525252525252525252Fpushpullpixel.com%252525252525252525252525252Fowa%252525252525252525252525252Findex.php%252525252525252525252525253Fowa_do%252525252525252525252525253Dbase.loginForm%2525252525252525252525252526owa_go%252525252525252525252525253Dhttps%25252525252525252525252525253A%25252525252525252525252525252F%25252525252525252525252525252Fpushpullpixel.com%25252525252525252525252525252Fowa%25252525252525252525252525252Findex.php%25252525252525252525252525253Fowa_do%25252525252525252525252525253Dbase.loginForm%252525252525252525252525252526owa_go%25252525252525252525252525253Dhttps%2525252525252525252525252525253A%2525252525252525252525252525252F%2525252525252525252525252525252Fpushpullpixel.com%2525252525252525252525252525252Fowa%2525252525252525252525252525252Findex.php%252525252525252525252525252526%2525252525252525252525252526%25252525252525252525252526%252525252525252525252526%2525252525252525252526%25252525252525252526%252525252525252526%2525252525252526%25252525252526%252525252526%2525252526%25252526%252526%2526%26&

**Comment by padams** [comment]
Please try 1.7.3 and see if that resolves your issue.
