### ISSUE TITLE
does not work, statistics remain at zero

### ISSUE THREAD

**Issue by kazzz57** [Open-Web-Analytics/Open-Web-Analytics#799]
**Before you open an issue:**

- [ ] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [ ] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting)

**Affected Version(s)**: 1.7.3

**PHP Version**: 7.4

**Webserver**: Apache/Nginx i suppose with OVH

**Browser**: last FIREFOX and BRAVE 

**Installation Type**
installation on OVH server PRO2014

**Description**  

does not work, statistics remain at zero

here is my configuration
OVH server
PHP version 7.4
SSL enabled

I tested the CHMOD on different software files
705 or 755 without success

I added the javascript tracker version in the HEAD and also the PHP version in the BODY

I can't find the problem
could someone help me?

**Additional context**

**Comment by padams** [comment]
Please read the troubleshoot guide to the wiki and perform those debug steps. Without that info there is no way to identify if there is a bug or an issue with your server environment. Feel free e to reopen with that info.
