### ISSUE TITLE
Referring Search Terms -  "(not provided)"

### ISSUE THREAD

**Issue by cerohazuri** [Open-Web-Analytics/Open-Web-Analytics#800]
**Description**  

Hello Community,

how can I get it to show "not provided" as a keyword?
<img width="1139" alt="Bildschirmfoto 2021-12-26 um 21 04 35" src="https://user-images.githubusercontent.com/34490466/147418878-b4ecf759-2045-4a50-ad39-a0fe0531eda8.png">

**Comment by padams** [comment]
You can't. Google hides them thus the "not provided" label.

**Comment by cerohazuri** [comment]
No Way or Hack tu turn that on? 

Thanks

 

Von: Peter Adams ***@***.***>
Antworten an: Open-Web-Analytics/Open-Web-Analytics ***@***.***>
Datum: Samstag, 8. Januar 2022 um 00:42
An: Open-Web-Analytics/Open-Web-Analytics ***@***.***>
Cc: cerohazuri ***@***.***>, Author ***@***.***>
Betreff: Re: [Open-Web-Analytics/Open-Web-Analytics] Referring Search Terms - "(not provided)" (Issue #800)

 

You can't. Google hides them thus the "not provided" label.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
