### ISSUE TITLE
Integration with wordpress plugin

### ISSUE THREAD

**Issue by jsidlauskas** [Open-Web-Analytics/Open-Web-Analytics#801]
I'm attempting a clean re-install of an OWA instance with WP integration. I deleted entirely the /wp-content/plugins/owa directory, removed both plugins and dropped the owa database entirely, created a new database, assigned user privs and installed as usual. The install seems to work fine, loads install.php and writes the owa-config.php file with keys and nonces, etc. I can't seem to get it to populate in the WP admin console the SITE ID.  

Instead, it keeps showing the old values, and the Site ID shows: "There has been a critical error on this website." Whenever I provide the proper AUTH_KEY and API values to the WP console (and the "save changes" button dissappears). 

Is there some other place this is being cached? I don't seem to be getting a clean install.

**Comment by padams** [comment]
Are you using the new OWA plugin as installed from the WordPress plugin repo? if so that plugin stores it's configuration in the WP options table. A critical error when you save the plugin config  sounds like an issue with the plugin and not your OWA Server install. Can you file a ticket in the repo for that plugin:

https://github.com/Open-Web-Analytics/owa-wordpress-plugin

Be sure to put WordPress into debug mode and provide any errors in your log file.

**Comment by wuzhongyi1105** [comment]
I get the same error and Wordpress debug log says:

```
[11-Jan-2022 13:52:16 UTC] Tracking WordPress feed request
[11-Jan-2022 13:52:16 UTC] PHP Fatal error:  Uncaught Error: Call to private method OwaSdk\Tracker\TrackerClient::makeEvent() from context 'owaWp_plugin' in /var/www/vhosts/example.com/blog.example.com/wp-content/plugins/open-web-analytics/owa-plugin.php:919
Stack trace:
#0 /var/www/vhosts/example.com/blog.example.com/wp-includes/class-wp-hook.php(303): owaWp_plugin->trackFeedRequest()
#1 /var/www/vhosts/example.com/blog.example.com/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#2 /var/www/vhosts/example.com/blog.example.com/wp-includes/plugin.php(470): WP_Hook->do_action()
#3 /var/www/vhosts/example.com/blog.example.com/wp-includes/template-loader.php(13): do_action()
#4 /var/www/vhosts/example.com/blog.example.com/wp-blog-header.php(19): require_once('/var/www/vhosts...')
#5 /var/www/vhosts/example.com/blog.example.com/index.php(17): require('/var/www/vhosts...')
#6 {main}
  thrown in /var/www/vhosts/example.com/blog.example.com/wp-content/plugins/open-web-analytics/owa-plugin.php on line 919
```
