### ISSUE TITLE
RSS-Feed does not function any more 😒

### ISSUE THREAD

**Issue by Herbert-Sg** [Open-Web-Analytics/Open-Web-Analytics#802]
If I activate the OWA plugin, my feed link doesn't work any more. I get this error message:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error>
<code>internal_server_error</code>
<title>
<![CDATA[ WordPress &amp;rsaquo; Fehler ]]>
</title>
<message>
<![CDATA[ &lt;p&gt;Es gab einen kritischen Fehler auf deiner Website.&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;https://wordpress.org/support/article/faq-troubleshooting/&quot;&gt;Erfahre mehr über die Problembehandlung in WordPress.&lt;/a&gt;&lt;/p&gt; ]]>
</message>
<data>
<status>500</status>
</data>
</error>

When I deactivate the plugin, it works again.

Thx!

**Comment by padams** [comment]
Please do not file a bug like this without any of the info that we ask for. No one can possibly help you without that info or seeing what steps you completed to identify that his is truly a bug and not an issue with your environment. 

Feel free to reopen with the proper info.

**Comment by Herbert-Sg** [comment]
Sorry, but which information is needed?

I am using WordPress 5.8.3 and tried OWA Version 2.1.1.
What else is needed?
Thx

**Comment by padams** [comment]
Put WordPress into debug mode and see what errors there are in the debug.log. Try disabling other plugins to see if there's a conflict. Without any errors msgs, it's impossible to tell what might be happening.

**Comment by wuzhongyi1105** [comment]
I got the same error and Wordpress debug log says:
```
[11-Jan-2022 13:52:16 UTC] Tracking WordPress feed request
[11-Jan-2022 13:52:16 UTC] PHP Fatal error:  Uncaught Error: Call to private method OwaSdk\Tracker\TrackerClient::makeEvent() from context 'owaWp_plugin' in /var/www/vhosts/example.com/blog.example.com/wp-content/plugins/open-web-analytics/owa-plugin.php:919
Stack trace:
#0 /var/www/vhosts/example.com/blog.example.com/wp-includes/class-wp-hook.php(303): owaWp_plugin->trackFeedRequest()
#1 /var/www/vhosts/example.com/blog.example.com/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#2 /var/www/vhosts/example.com/blog.example.com/wp-includes/plugin.php(470): WP_Hook->do_action()
#3 /var/www/vhosts/example.com/blog.example.com/wp-includes/template-loader.php(13): do_action()
#4 /var/www/vhosts/example.com/blog.example.com/wp-blog-header.php(19): require_once('/var/www/vhosts...')
#5 /var/www/vhosts/example.com/blog.example.com/index.php(17): require('/var/www/vhosts...')
#6 {main}
  thrown in /var/www/vhosts/example.com/blog.example.com/wp-content/plugins/open-web-analytics/owa-plugin.php on line 919
```

**Comment by padams** [comment]
closing as this is now logged in the plugin repo as an issue.
