### ISSUE TITLE
Tracking is not working

### ISSUE THREAD

**Issue by KT-Manish** [Open-Web-Analytics/Open-Web-Analytics#803]
**Before you open an issue:**

I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 

**Affected Version(s)**: Open Web Analytics 1.7.3

**PHP Version**: 7.4.20

**Webserver**: Apache/Nginx

**Browser**: Chrome Version 96.0.4664.110

**Installation Type**
![Open-Web-Analytics-tracking-issue](https://user-images.githubusercontent.com/86764015/148651365-aa3ecd4f-3eb2-444c-87b6-3f6e68becc0d.png)

 Standalone

**Description**  
I have followed all installation steps and also checked Troubleshooting but still, it is not tracking (visits, Page Views) 

**How to reproduce**  
Open site: https://kttest.skajn.com/

**Comment by padams** [comment]
It's impossible to determine if this isa bug or user error. Re-read the troubleshooting guide and run through the debug steps to determine where the logging request is getting stuck. feel free to reopen once you have more info.
