### ISSUE TITLE
1.7.4 - Embedded JS tracking scripts point to wrong location

### ISSUE THREAD

**Issue by quadcom** [Open-Web-Analytics/Open-Web-Analytics#813]
**OWA Version**: 1.7.4

**PHP Version**: 7.4

**Webserver**: Apache/Nginx

**Browser**: Chrome 80.x.x

**Description**  
the tracking scripts added to pages are looking for '/modules/base/dist/js/owa.tracker-combined-min.js'. the 'js' directory does not exist in the latest release. 'owa.tracker-combined-min.js' is located in '/modules/base/js'

**How to reproduce**  
Extract all the files from the tarball and check file structure.

![image](https://user-images.githubusercontent.com/7085931/152230413-47f3789d-ffdf-41eb-b8b9-e8e3287c3239.png)

![image](https://user-images.githubusercontent.com/7085931/152230604-2503160a-73c1-4375-be70-db1952413ed7.png)

![image](https://user-images.githubusercontent.com/7085931/152231173-5ca44553-e0c5-4347-aff8-29de8327f0a9.png)

**Comment by padams** [comment]
Fixing now. should be `modules/base/dist/owa.tracker.js`

**Comment by padams** [comment]
Fixed in release 1.7.5.
