### ISSUE TITLE
Data stuck at 0

### ISSUE THREAD

**Issue by vivetahiti** [Open-Web-Analytics/Open-Web-Analytics#815]
**Before you open an issue:**

- [ yep] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [ yep] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 
- [yep ] I have attached http headers, console/shell errors, or debug from OWA's error log file.
`AddHandler application/x-httpd-php .tpl

<IfModule mod_rewrite.c>

RewriteEngine On

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule api/(.*)$ api/index.php?owa_rest_params=$1 [QSA,NC,L]

# Rewrites for new tracker location (../base/js/owa.tracker-combined-min.js) to new location (../bas>
# need to properly sniff the protocol or else you could get a CSP error in the browser under https

RewriteCond %{REQUEST_URI} (.*)/modules/base/js/owa.tracker-combined-min.js$
RewriteCond %{HTTP:X-Forwarded-Proto} =https [OR]
RewriteCond %{HTTPS} =on [OR]
RewriteCond %{REQUEST_SCHEME} =https
RewriteRule owa.tracker-combined-min.js$ https://%{HTTP_HOST}%1/modules/base/dist/owa.tracker.js [NC>

RewriteCond %{REQUEST_URI} (.*)/modules/base/js/owa.(heatmap|vendors|player).js$
RewriteCond %{HTTP:X-Forwarded-Proto} =https [OR]
RewriteCond %{HTTPS} =on [OR]
RewriteCond %{REQUEST_SCHEME} =https
RewriteRule js$ https://%{HTTP_HOST}%1/modules/base/dist/owa.%2.js [NC,R=301,L]

RewriteCond %{REQUEST_URI} (.*)/modules/base/js/owa.tracker-combined-min.js$
RewriteCond %{HTTP:X-Forwarded-Proto} =http [OR]
RewriteCond %{HTTPS} =off [OR]
RewriteCond %{REQUEST_SCHEME} =http
RewriteRule owa.tracker-combined-min.js$ http://%{HTTP_HOST}%1/modules/base/dist/owa.tracker.js [NC,>

RewriteCond %{REQUEST_URI} (.*)/modules/base/js/owa.(heatmap|vendors|player).js$
RewriteCond %{HTTP:X-Forwarded-Proto} =http [OR]
RewriteCond %{HTTPS} =off [OR]
RewriteCond %{REQUEST_SCHEME} =http
RewriteRule js$ https://%{HTTP_HOST}%1/modules/base/dist/owa.%2.js [NC,R=301,L]

</IfModule>
`

**OWA Version**: 1.7.5

**PHP Version**: 7.4.3 with no fpm

**Webserver**: Apache

**Browser**: Firefox 96

**Description**  
all websites reports are stuck at 0
i made a clean and complete installation of the plugin on Word Press 5.9

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by padams** [comment]
What is the bug you are seeing? Reports stuck at zero could men anything. please provide an account of the step you took as outlined in the troubleshooting guide and re-open.

**Comment by vivetahiti** [comment]
I deployed OWA on a fresh VPS: no problem
I installed Word Press official Plugin: no problem
I configured the plugin correctly, with my OWA server php config data: connected
I chose a website ID within the provided list of the plugin config page: ok
I cliked on the Word Press OWA link "OWA/Analytics/Launch your OWA Dashboard and landed on my OWA distant server : ok
I went to Site Roster, then chose my website, and clicked View Reports : all is at 0
I did it for 7 websites, all is at 0
