### ISSUE TITLE
Trying to view dom stream recording: ReferenceError: OWA_instance is not defined

### ISSUE THREAD

**Issue by maksbotan** [Open-Web-Analytics/Open-Web-Analytics#817]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 
- [x] I have attached http headers, console/shell errors, or debug from OWA's error log file.

**OWA Version**: 1.7.5

**PHP Version**: 7.4

**Webserver**: Apache in php:7.4-apache docker image

**Browser**: Chrome 98.0.4758.80

**Description**  

I've just installed OWA locally for testing and connected it to my project. I am able to see page events, clicks and stuff, but when I click 'Play' next to a DOM stream, I see this error in browser's console:

```
owa.player.js:10 Uncaught (in promise) ReferenceError: OWA_instance is not defined
    at o.fetchData (owa.player.js:10:416)
    at o.init (owa.player.js:10:237)
    at owa.tracker.js:9:2122
```

Unminified code from Chrome dev tools at this position:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/275614/153721915-b383fb09-77cd-4d5a-aca1-8dd0baa08372.png">

**How to reproduce**  

Try to load any dom stream recording.

**Comment by padams** [comment]
Fixed in master will go out in next release shortly.

**Comment by maksbotan** [comment]
Thank you!
