### ISSUE TITLE
No folder with modules/base/dist/owa.tracker.js

### ISSUE THREAD

**Issue by edwardap42** [Open-Web-Analytics/Open-Web-Analytics#823]
**Before you open an issue:**

**Affected Version(s)**: x.y.z

**PHP Version**: 7.4 FPM

**Webserver**: Apache/Nginx

**Installation Type**

- [ ] Standalone

**Description**  

**Additional context**  

I installed twice.  I can't figure out why I don't have a modules/base/dist/owa.tracker.js folder nor file.   There is no dist folder.   There is no data coming in on the website I placed the script on.  I changed the permission of the modules folder after install to 777.

**Comment by padams** [comment]
You don't say what version of OWA you are running or how you installed (from source or via the packaged tarball).

**Comment by edwardap42** [comment]
Sorry......I figured it out.  I was running 1.7.7
