### ISSUE TITLE
1.7.7 Not working

### ISSUE THREAD

**Issue by maxralli** [Open-Web-Analytics/Open-Web-Analytics#827]
*OWA Version**: 1.7.7

**PHP Version**: 7.3

**Webserver**: IIS 8.5

**Browser**: Chrome 80.x.x

**Description**  
There is no data coming into the database.
I installed the release 1.7.6 and data was getting into the database (I had to copy from previous release some .js in the folder \modules\base\js  to make it work).

In my opinion some files are missing  in release 1.7.7 
What is the correct js url, ?  \modules\base\js ? or module\dist\ ?
 What files are the correct files to have in that folder ?
Seems also that it is not able to recognize the country of the visitor.
I m available to keep testing.

**Comment by padams** [comment]
If you are installing from GitHub source you need to build the tracker as of 1.7.7. If you are installing from the packaged tarball it's prebuilt. 

See install instructions on the wiki.

**Comment by maxralli** [comment]
Ok, now is working.
I just report you that  Geo-Location  seems not to work.
Thank you

**Comment by maxralli** [comment]
Tracking Tag seems to use an invalid url:
 'modules/base/dist/owa.tracker.js';
instead of
 'modules/base/js/owa.tracker.js';





<script type="text/javascript">
//<![CDATA[
var owa_baseUrl = 'https://owa/';
var owa_cmds = owa_cmds || [];
owa_cmds.push(['setSiteId', 'bdff7d3f92929e61b8a3e145bac0c4f8']);
owa_cmds.push(['trackPageView']);
owa_cmds.push(['trackClicks']);

(function() {
    var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
    owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
    _owa.src = owa_baseUrl + 'modules/base/dist/owa.tracker.js';
    var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
}());
//]]>

**Comment by padams** [comment]
Read the instructions for activating the maxmind module on the wiki. that's what does the geo location.

**Comment by maxralli** [comment]
Thank you for your patience and help.
I will check now.
