### ISSUE TITLE
Geo-Tracking

### ISSUE THREAD

**Issue by maxralli** [Open-Web-Analytics/Open-Web-Analytics#828]
I setup the module for  Geolocation. It works  fine but   it shows only the country  and not the city. The database i copied is the one with cities.
Can anybody help me to figure it out  where it is the issue  ? It will be useful to have the cities of visitors.
Everything else works great!
Thank you.

**Comment by padams** [comment]
I don't think this is a bug. Not every IP address if going to be in that DB. I see lot of cities resolved but not all.
