### ISSUE TITLE
Cannot Upgrade from 1.6.9

### ISSUE THREAD

**Issue by Quin452** [Open-Web-Analytics/Open-Web-Analytics#829]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 
- [ ] I have attached http headers, console/shell errors, or debug from OWA's error log file.

**OWA Version**: 1.6.9

**PHP Version**: 7.2 FPM

**Webserver**: Apache

**Browser**: Chrome 80.x.x

**Description**  

Following the [upgrade guide](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating), I downloaded and extracted the files.
I've tried copying (cp) the files, and I've tried moving (mv) the files, and yet I don't get anywhere.  Each time I try, it goes to a white screen.  I have tried with all 1.7 releases.

**How to reproduce**  

**Possible Solution**  

**Additional context**

**Comment by padams** [comment]
Hasn't been an issue for anyone else AFAIK. Next time, a failsafe way to upgrade is to extract into a new directory and then cp your owa-conf.php file in to the new directory.
