### ISSUE TITLE
 /api/base/v1/reports since 1.7.3?

### ISSUE THREAD

**Issue by pelle092** [Open-Web-Analytics/Open-Web-Analytics#830]
Thank you for a great analysis tool!

- [ ] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
no, installed via Softaculous
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 
- [ ] I have attached http headers, console/shell errors, or debug from OWA's error log file.
no, not sure this is of any help at this point

**OWA Version**: 1.7.7

**PHP Version**: 7.3.33

**Webserver**: Apache/Nginx

**Browser**: no

**Description**  
It seems the /api/base/v1/reports is not working. I did an update a while back including the updated API release 1.7.3 and since then all reports for this endpoint return an empty result set.

**How to reproduce**  
I was not able to follow the instructions at the REST API page. I had to include the api key in the canonical URL despite what it says there, to be able to match the keys (I used debugging to see if they matched). Also, the base64 encoder in the shell produced a different result than jq which I ended up using (since it worked).

**Possible Solution**  
Do not know how to debug this. Tried with as few parameters as possible, with dates that should produce results.

**Additional context**  
Happy to provide more information if needed.

**Comment by padams** [comment]
try putting owa into debug mode and check the errors log file to see where the request is getting hung up. Also debug mode forgoes the use of the request signature param so you can rule that in or out as the culprit. re-open if necessary.
