### ISSUE TITLE
Filter in Report doesn't work

### ISSUE THREAD

**Issue by maxralli** [Open-Web-Analytics/Open-Web-Analytics#838]
I tryed to use the report filter but seems not to work with any option or text I digit.
I was trying to filter the report result by Page Title.
Thank you

**Comment by ievann** [comment]
Same here. Every time I try to use filters or change secondary dimension I see 401 Unauthorized error in console. There are also no requests to `log.php`.

**Comment by dleigh** [comment]
Same here with secondary dimensions I get a 401 in the network console for the XHR request.  Looking at the response, I get: Object { headline: "Not authenticated.", msg: "Check API key or permissions for this user." }  In the Response headers I have: 

Status: 401 Unauthorized
Version: HTTP/2
Transferred: 475 B (178 B size)
Referrer Policy: strict-origin-when-cross-origin
Request Priority: Highest

Part of the Request Headers say: 
Sec-Fetch-Dest: 	empty
Sec-Fetch-Mode: 	cors
Sec-Fetch-Site: 	same-origin
Sec-GPC: 	1

I may well have misconfigured my installation, but I'm at a loss to know what step I skipped or screwed up.  So a bit of indulgence please.

**Comment by SenDeeZe** [comment]
The same problem. Did someone manage to solve it?
