### ISSUE TITLE
Goals / URL destination

### ISSUE THREAD

**Issue by bristolwebdesigner** [Open-Web-Analytics/Open-Web-Analytics#839]
When creating a Goal for URL destination, an error is returned. 
"goal_url is required."
There doesn't seem to be anywhere to enter a URL.
Would appreciate your guidance on this.
Installation, is a breeze, by the way.

**Comment by pcbits** [comment]
[js.tar.gz](https://github.com/Open-Web-Analytics/Open-Web-Analytics/files/9839811/js.tar.gz)

I know this is not the correct way to solve the issue but as a work around I put back the deleted JS files to get the JS working in the admin site. I place these in the folder of ./owa/modules/base/js folder. This lets the JS load correctly and gives you the goal_url field. All seems to be working after that.

**Comment by wpbryant** [comment]
This helped me as well, seems like a poor oversight.
