### ISSUE TITLE
Problem installing on Ubuntu 22.04 - PHP 8.1 - MariaDB

### ISSUE THREAD

**Issue by alejivo** [Open-Web-Analytics/Open-Web-Analytics#840]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting)

**Affected Version(s)**:  1.7.7

**PHP Version**: 8.1 FPM/Proxy

**Webserver**: Apache

**Browser**: Chrome 80.x.x

**Installation Type**

Handmade over ubuntu

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [ ] Standalone

**Description**  

Seems the table is never been created.

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'owa_db.owa_configuration' doesn't exist in /var/www/owa/plugins/db/owa_db_mysql.php:183\nStack trace:\n#0 /var/www/owa/plugins/db/owa_db_mysql.php(183): mysqli_query()\n#1 /var/www/owa/plugins/db/owa_db_mysql.php(223): owa_db_mysql->query()\n#2 /var/www/owa/owa_db.php(874): owa_db_mysql->get_results()\n#3 /var/www/owa/owa_db.php(477): owa_db->query()\n#4 /var/www/owa/owa_db.php(355): owa_db->_selectQuery()\n#5 /var/www/owa/owa_entity.php(477): owa_db->getOneRow()\n#6 /var/www/owa/owa_entity.php(442): owa_entity->getByColumn()\n#7 /var/www/owa/modules/base/classes/settings.php(277): owa_entity->getByPk()\n#8 /var/www/owa/owa_caller.php(99): owa_settings->load()\n#9 /var/www/owa/owa.php(24): owa_caller->construct()\n#10 /var/www/owa/install.php(38): owa->_construct()\n#11 {main}\n  thrown in /var/www/owa/plugins/db/owa_db_mysql.php on line 183', install.php?owa_action=base.installCheckEnv

**Additional context**

**Comment by padams** [comment]
This should be fixed in master now.
