### ISSUE TITLE
Installing in Invision Community Forums Breaks Browser Back Button

### ISSUE THREAD

**Issue by soundmedia** [Open-Web-Analytics/Open-Web-Analytics#843]
Recently discovered OWA and been most impressed by its capability. Proceeded to roll it out across the website, and all went well until we put the tracker code in the forum template. 

Once loaded, it rendered the Back button of the browser (multiple devices types and browsers) useless. We quickly realised that while the Back button was technically working, what was actually happening is that multiple instances of the page were being loaded in the background. So while you click Back it appears nothings happening because there are 5-6 versions of the page loaded.

![Screenshot 2022-07-02 142109](https://user-images.githubusercontent.com/54829590/176986215-5fe24e1d-a75e-4b28-9cc0-2be61136fc37.jpg)

We have tried moving the tracker code template location around (header, footer, inside body etc) but it's the same result. Any thoughts or ideas?

**Comment by padams** [comment]
Is the tracker recording domstreams (trackDomstream)? If so turn that off and see if it helps.

**Comment by soundmedia** [comment]
That did the trick. Thanks @padams
