### ISSUE TITLE
Export data and import to new database

### ISSUE THREAD

**Issue by ChandigarIT** [Open-Web-Analytics/Open-Web-Analytics#844]
**Description**  
Is it possible to export the data from a dbase for just one site, and then import it into a "master" dbase that has a number of other sites?

**Example**  
I have already created the new site in the master dbase, but the stats are out by a week, and I'd like to sync them.

This is the new data in the master dbase

![Screen Shot 2022-07-06 at 18 37 43](https://user-images.githubusercontent.com/108827431/177610671-dae7048b-73b0-4921-b403-ada9c386cd1a.png)
and this is in the original dbase
![Screen Shot 2022-07-06 at 18 37 03](https://user-images.githubusercontent.com/108827431/177610681-73fa0e9a-b211-4a71-9f4a-aa3e02bb8cee.png)

Thanks

**Comment by JMcrafter26** [comment]
Yes you can.

I just did it.
1. Log in to your phpmyadmin
2. Select the old database and navigate to export
3. Select sql as format and click OK
This should download a .sql file
4.Go to your new database in phpmyadmin (or create one) and navigate to import
5. Finally select your .sql file you just downloaded and click OK

TO CHANGE THE DATABASE IN OWA:
1. Find the owa-config.php file in your server files
2. Edit it and change the database cridentials 

You are done! Thank me later
