### ISSUE TITLE
baidu as search source

### ISSUE THREAD

**Issue by czosnkowy666** [Open-Web-Analytics/Open-Web-Analytics#847]
**Description**  
Right now I see traffic from baidu as referral. Do I need to modify some settings to have it recognized as organic-search medium?

**Comment by padams** [comment]
You can do this two ways:

1. create a supplemental searchengines.php files in the ```own-data``` directly (see the one in the conf/ director for the template).
2. You can create add Baidu as an entry in the list at runtime by filtering```conf.searchengines.php```.

That said we'll add this in the next release.

**Comment by padams** [comment]
actually Baidu is already in the core file.  The issue was that baidu and some other engines pass a short host name which failed the comparison check we were using.

**Comment by czosnkowy666** [comment]
@padams do I need to do something to fix past requests?
