### ISSUE TITLE
Can't get to install OWA with Php 8.1 & MariaDB

### ISSUE THREAD

**Issue by arladmin** [Open-Web-Analytics/Open-Web-Analytics#849]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 
- [x] I have attached http headers, console/shell errors, or debug from OWA's error log file.

**OWA Version**: 1.7.7

**PHP Version**: 8.1

**Webserver**: Apache

**Browser**: Chrome 104.0.5112.81

**Description**  
While running the installation wizard, i'm getting the error:
```
Fatal error: Uncaught mysqli_sql_exception: Table 'db.owa_configuration' doesn't exist in /path/to/owa/plugins/db/owa_db_mysql.php:183
```

**How to reproduce**  
1. Upload the decompressed folder to your web server
2. Go to domain.tld/owa
3. Fill out all the db related details in the first step of the installation wizard
4. Go to the next step. Encounter the error.

Note: My server type is MariaDB
![image](https://user-images.githubusercontent.com/64059154/183233732-4ba5279f-d801-4fe9-a8cd-07497fef78d2.png)

**Comment by neomafo88** [comment]
owa_caller.php:

```
// load config values from DB
// Applies config from db or cache
// check here is needed for installs when the configuration table does not exist.

if ($this->c->isConfigFilePresent())  {
   $this->c->load( $this->c->get( 'base', 'configuration_id' ) );
}
```

**Comment by padams** [comment]
This issue here is that PHP 8 is throwing an exception for the config query instead of a silent error as it did in prior versions. We need to refactor the installer to always check for the existence of the table instead of blindly querying for it.

**Comment by padams** [comment]
Here is the issue and the workaround: https://php.watch/versions/8.1/mysqli-error-mode
