### ISSUE TITLE
How to report error 404 (and eventually others)

### ISSUE THREAD

**Issue by c-orazio** [Open-Web-Analytics/Open-Web-Analytics#853]
**Description**  

It would be nice that all request resulting in an error 404 can be listed in a specific place so that we can fix all them at once, instead of looking one by one in reports...
**Example**

**Comment by padams** [comment]
If it's a 404 then your web server log files are the only place that those error would show up, not OWA.

**Comment by c-orazio** [comment]
I understand your point, I will try to be more precise. Now that we are using CMS, it is not any more the same person who install word-press (a server manager) and the person who write the content : a communication officer.
The communication officer update continuously the website and check the fantastic OWA regularly, checking how much all the recent changes improve the audience. This person can also be at the origin of 404 error that WP try to handle redirecting the website visitor on a 404 error message, we see it in OWA. But then the communication officer has no acces to the log, and this is an important information related to the traffic of a given website; When you are using OWA to monitor many websites on may machine,s it would make sens this kind of error to be reported... Don't you think? This is just an idea..; Thank you for  the good job done with OWA.
