### ISSUE TITLE
HTTP ERROR 500 while running the installation

### ISSUE THREAD

**Issue by vlad-riashentsev** [Open-Web-Analytics/Open-Web-Analytics#854]
[+] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
[+] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting)

OWA Version: 1.7.7

PHP Version: 7.4.29

MySQL Version | 5.6.51-cll-lve

Webserver: Apache Version | 2.4.54

Browser: Chrome 104.0.5112.81

Installation Type
1. Upload the decompressed folder to your web server (https://unitedprohandyman.com/owa/)
2. Change permissions (https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Required-permissions)
3. Create db
4. Create file owa-config and set db configurations and OWA_PUBLIC_URL

Description
HTTP ERROR 500 while running the installation
https://unitedprohandyman.com/owa/install.php

Additional context

Error log:
<pre>
[15-Aug-2022 12:15:16 UTC] PHP Fatal error:  Uncaught Error: Class 'Monolog\Logger' not found in /home/sanfrancisco2016/public_html/unitedprohandyman.com/owa/modules/base/classes/error.php:68
Stack trace:
#0 /home/sanfrancisco2016/public_html/unitedprohandyman.com/owa/owa_lib.php(489): owa_error->__construct(Array)
#1 /home/sanfrancisco2016/public_html/unitedprohandyman.com/owa/owa_coreAPI.php(487): owa_lib::factory('/home/sanfranci...', 'owa_', 'error', Array)
#2 /home/sanfrancisco2016/public_html/unitedprohandyman.com/owa/owa_coreAPI.php(158): owa_coreAPI::supportClassFactory('base', 'error')
#3 /home/sanfrancisco2016/public_html/unitedprohandyman.com/owa/owa_base.php(77): owa_coreAPI::errorSingleton()
#4 /home/sanfrancisco2016/public_html/unitedprohandyman.com/owa/owa_caller.php(76): owa_base->__construct()
#5 /home/sanfrancisco2016/public_html/unitedprohandyman.com/owa/owa.php(24): owa_caller->__construct(NULL)
#6 /home/sanfrancisco2016/public_html/unitedprohandyman.com/owa/index.php(35): owa->__construct()
#7 {main}
  thrown in /home/sanfrancisco2016/public_html/unitedprohandyman.com/owa/modules/base/classes/error.php on line 68
</pre>

**Comment by padams** [comment]
So you use the "packaged" tarball?

**Comment by vlad-riashentsev** [comment]
> So you use the "packaged" tarball?

Yes, [owa_1.7.7_packaged.tar](https://github.com/Open-Web-Analytics/Open-Web-Analytics/releases/download/1.7.7/owa_1.7.7_packaged.tar)

**Comment by izzyx6** [comment]
I get the HTTP ERROR 500 when I install OWA Version: 1.7.7. Please help

**Comment by padams** [comment]
Is the vendor directory present?

**Comment by izzyx6** [comment]
No it is not.

**Comment by izzyx6** [comment]
I installed the latest package v1.7.7.packaged.tar and the installation was successful. Thanks

**Comment by vlad-riashentsev** [comment]
> Is the vendor directory present?

Yes, but I just noticed that there is no src folder in the monolog folder.
Reinstalled, the installation page appeared.
I'm sorry, this issue has been resolved. Thanks for the tip!
