### ISSUE TITLE
Unable To Reset User Password

### ISSUE THREAD

**Issue by izzyx6** [Open-Web-Analytics/Open-Web-Analytics#855]
Hello, 
I am unable to reset the user password after setting up OWA on my host. Every time I click on reset password and input my email, I get a success message "Success! An e-mail containing instructions on how to complete the password reset process has been sent " but I never receive any email with instructions to reset my password.

I'm running a Linux Server with
PHP 7.4
OWA 1.7.7

**Comment by advalgo** [comment]
Mine sends the password reset to the user however on the owa admin it throws a 500 server error with the following:
`PHP Fatal error:  Uncaught TypeError: vsprintf(): Argument #2 ($values) must be of type array, null given in /var/www/html/owa/owa_base.php:105
Stack trace:
#0 /var/www/html/owa/owa_base.php(105): vsprintf()
#1 /var/www/html/owa/modules/base/passwordResetRequest.php(60): owa_base->getMsg()
#2 /var/www/html/owa/owa_controller.php(280): owa_passwordResetRequestController->action()
#3 /var/www/html/owa/owa_coreAPI.php(880): owa_controller->doAction()
#4 /var/www/html/owa/owa_coreAPI.php(867): owa_coreAPI::runController()
#5 /var/www/html/owa/owa_coreAPI.php(1411): owa_coreAPI::performAction()
#6 /var/www/html/owa/owa_caller.php(204): owa_coreAPI::handleRequest()
#7 /var/www/html/owa/owa_caller.php(146): owa_caller->handleRequest()
#8 /var/www/html/owa/index.php(45): owa_caller->handleRequestFromUrl()
#9 {main}`

**Comment by padams** [comment]
What version of php and OWA produced that fatal error for you?
