### ISSUE TITLE
Deprecated: Required parameter $XXX follows optional parameter $XXX

### ISSUE THREAD

**Issue by yangqiceng** [Open-Web-Analytics/Open-Web-Analytics#859]
Deprecated: Required parameter $value follows optional parameter $name in /www/wwwroot/owa_coreAPI.php on line 1232

Deprecated: Required parameter $data follows optional parameter $hash_type in /www/wwwroot/owa_lib.php on line 993

Deprecated: Required parameter $errmsg follows optional parameter $errno in /www/wwwroot/modules/base/classes/error.php on line 365

Deprecated: Required parameter $filename follows optional parameter $errno in /www/wwwroot/modules/base/classes/error.php on line 365

Deprecated: Required parameter $linenum follows optional parameter $errno in /www/wwwroot/modules/base/classes/error.php on line 365

Deprecated: Required parameter $vars follows optional parameter $errno in /www/wwwroot/modules/base/classes/error.php on line 365

Deprecated: Required parameter $params follows optional parameter $type in /www/wwwroot/owa_db.php on line 563

Deprecated: Required parameter $value follows optional parameter $name in /www/wwwroot/modules/base/classes/state.php on line 96

Deprecated: Required parameter $value follows optional parameter $name in /www/wwwroot/modules/base/classes/state.php on line 144

Deprecated: Required parameter $ref follows optional parameter $subgroup in /www/wwwroot/owa_module.php on line 424

Deprecated: Required parameter $anchortext follows optional parameter $subgroup in /www/wwwroot/owa_module.php on line 424

Deprecated: Required parameter $family follows optional parameter $label in /www/wwwroot/owa_module.php on line 901

**Comment by padams** [comment]
Closing as I think we got all of these fixed in master now.
