### ISSUE TITLE
error 500 when creating owa-config.php

### ISSUE THREAD

**Issue by PeriHartman** [Open-Web-Analytics/Open-Web-Analytics#861]
Hi. First time installing owa. I have a shared server running cpanel. I have copied the owa installation to a document directory "owa" and made a subdomain to access it. It opens index.php and gets started successfully.

Next, I am trying to setup owa-config.php. First I tried the form, which immediately results in error 500. So, then I followed the manual instructions and modified owa-config-disp.php and renamed it as requested. From the start page, I click "let's get started" and it immediately gives me http error 500.

My owa-config values are:
define('OWA_DB_TYPE', 'mysql'); // options: mysql
define('OWA_DB_NAME', 'owa'); // name of the database
define('OWA_DB_HOST', 'localhost'); // host name of the server housing the database
define('OWA_DB_USER', 'qcs_admin'); // database user
define('OWA_DB_PORT', '3306'); // port of database
define('OWA_DB_PASSWORD', '...'); // database user's password

Permissions on the file are -rw-rw-r--

Thanks.

**Comment by PeriHartman** [comment]
I also tried creating the database first, via cpanel. I discovered I need to prefix the names with my account name, thus the params changed a bit:
define('OWA_DB_TYPE', 'mysql'); // options: mysql
define('OWA_DB_NAME', 'quietcle_owa'); // name of the database
define('OWA_DB_HOST', 'localhost'); // host name of the server housing the database
define('OWA_DB_USER', 'quietcle_admin'); // database user
define('OWA_DB_PORT', '3306'); // port of database
define('OWA_DB_PASSWORD', '...'); // database user's password

Anyway, still get error 500.

**Comment by PeriHartman** [comment]
I found owa-data/logs. It's reporting:
[18:20:08 2022-10-08] [21120] [ERROR]  is not a supported database.

**Comment by ilangranot** [comment]
I see this is MySQL. Did you try using the root account to connect to this DB? Also did you try using phpMyAdmin to connect to this DB using the credentials above? I.e. user and password. Before suspecting OWA I would check you properly have permissions to access that DB

**Comment by ilangranot** [comment]
Also, if that doesn’t work look at my comment here to provide us with more info about this 500: 
https://github.com/Open-Web-Analytics/Open-Web-Analytics/issues/860#issuecomment-1279977259

**Comment by PeriHartman** [comment]
I'm on a shared server and don't have access to the root account. I can have multiple accounts, but none are root.

In my experimentation, I tried letting the setup script create the DB versus creating it through cpanel. In the latter case, I got a different error message, which I don't precisely remember, but it had something to do with empty tables. So, in that case, the script was apparently able to login but not deal with the empty DB.

Let me know what specific things you think I should try.

**Comment by advalgo** [comment]
I had to do a chmod -R +x owa to get it to work for me.

**Comment by padams** [comment]
1. Make sure the config file has the proper filesystem permissions 
2. that the db user you are specifying actually have privileged to create tables in the database specified.
3. That the specified database exists on your mysql server (OWA will not create it for you).

reopen with specific error msgs if you are still having issues.
