### ISSUE TITLE
error with website WP 6.1

### ISSUE THREAD

**Issue by c-orazio** [Open-Web-Analytics/Open-Web-Analytics#866]
Trying to configure OWA, I do not see the list of ID site, but this..
uncaught Error: Call to a member function createSites() on string in /xxx/wp-content/plugins/open-web-analytics/owa-plugin.php:1192
Is there a workaround to set option and have the owa runing properly??

**Comment by advalgo** [comment]
I am getting that same error. In order for me to use this at present I need to insert the script CDATA in the header.php

**Comment by padams** [comment]
Please use the official OWA plug-in from the Wordpress plug-in repo (or build from the related OWA GitHub repo). The bundled plug-in is out of date and will be removed in the next release.

**Comment by advalgo** [comment]
That is the plugin I tried. Has it been updated in the last 48 hours?

**Comment by padams** [comment]
There is now a new version that hopefully fixes this issue. If not feel free to open an issue ticket over in that repository:

https://github.com/Open-Web-Analytics/owa-wordpress-plugin
