### ISSUE TITLE
post upgrade to 1.7.8

### ISSUE THREAD

**Issue by czosnkowy666** [Open-Web-Analytics/Open-Web-Analytics#870]
**Before you open an issue:**

- [x] I followed the [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 
- [x] I have attached http headers, console/shell errors, or debug from OWA's error log file.

**OWA Version**: 1.7.8

**PHP Version**: 7.4.28

**Webserver**: Apache

**Browser**: Firefox 108.0.2

**Description**  
After upgrade to version 1.7.8 warning is throws by PHP 
```
Warning: Use of undefined constant OWA_DTD_BIGINT - assumed 'OWA_DTD_BIGINT' (this will throw an Error in a future version of PHP) in /home/my-dir/owa/modules/base/entities/configuration.php on line 37

Warning: Use of undefined constant OWA_DTD_BLOB - assumed 'OWA_DTD_BLOB' (this will throw an Error in a future version of PHP) in /home/my-dir/owa/modules/base/entities/configuration.php on line 40
```

And because of those warnings all JSON responses for charts are broken as it is causing invalid json 

**How to reproduce**  
Open owa dashboard and warnings are on top of each page. On each site sash board charts are not displaying 

**Possible Solution**  

**Additional context**

**Comment by padams** [comment]
Did you update via git or the packaged tarball?

**Comment by czosnkowy666** [comment]
via tarball I'm doing it again as I see some files didn't get updated for some reason :( will keep you posted once it is done and if issue is still there

**Comment by czosnkowy666** [comment]
my bad, update was somehow didn't get though after it is correctly done
