### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Undefined constant "OWA_DTD_BIGINT"

### ISSUE THREAD

**Issue by campio97** [Open-Web-Analytics/Open-Web-Analytics#872]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting)

**Affected Version(s)**: 1.7.8

**PHP Version**: 8.0.25

**Webserver**: Apache

**Browser**: Chrome 109.0.5414.87

**Description**  
Hello, im a new user, so this one is a fresh install.
When i try to access to the installation script "mywebserverowa.it/install.php", the browser reports error 500.
Below you can find the error logs

**Additional context**  

> [17-Jan-2023 14:30:38 UTC] PHP Fatal error:  Uncaught Error: Undefined constant "OWA_DTD_BIGINT" in /var/www/html/owa/modules/base/entities/configuration.php:37
Stack trace:
#0 /var/www/html/owa/owa_lib.php(489): owa_configuration->__construct('')
#1 /var/www/html/owa/owa_coreAPI.php(561): owa_lib::factory('/var/www/html/o...', '', 'owa_configurati...', '')
#2 /var/www/html/owa/owa_coreAPI.php(521): owa_coreAPI::moduleSpecificFactory('base.configurat...', 'entities', '', '', false)
#3 /var/www/html/owa/modules/base/classes/settings.php(72): owa_coreAPI::entityFactory('base.configurat...')
#4 /var/www/html/owa/owa_lib.php(489): owa_settings->__construct(Array)
#5 /var/www/html/owa/owa_coreAPI.php(487): owa_lib::factory('/var/www/html/o...', 'owa_', 'settings', Array)
#6 /var/www/html/owa/owa_coreAPI.php(142): owa_coreAPI::supportClassFactory('base', 'settings')
#7 /var/www/html/owa/owa_base.php(78): owa_coreAPI::configSingleton()
#8 /var/www/html/owa/owa_caller.php(76): owa_base->__construct()
#9 /var/www/html/owa/owa.php(24): owa_caller->__construct(NULL)
#10 /var/www/html/owa/index.php(35): owa->__construct()
#11 {main}
  thrown in /var/www/html/owa/modules/base/entities/configuration.php on line 37

**Comment by campio97** [comment]
I was able to install correctly by copying the owa-config-dist.php -> owa-config.php file and doing a manual configuration directly in the file

**Comment by edison23** [comment]
This issue is still valid and shouldn't be closed -- I'm getting errors in Apache error log, the install guide won't load and when I somehow managed to get OWA running, parts of the settings generated other errors. I was very careful to follow the required permissions and versions and everything, but it's unusable :(
However, I'm happy to help with testing, if devs are interested. I can't fix the problems myself, tho.

**Comment by ralfulrich** [comment]
I have the same problem. The installer seems to miss some kind of initialization.
