### ISSUE TITLE
CORS Error in API Request to Spot.IM Notifications Endpoint

### ISSUE THREAD

**Issue by dfinson** [Open-Web-Analytics/Open-Web-Analytics#885]
## Description:
When making a request to the Spot.IM API endpoint (`https://www.spot.im/api/notifications/my-notifications-and-reset-unseen`), a CORS (Cross-Origin Resource Sharing) error is encountered.

## Steps to reproduce:
1. Open Google Chrome browser.
2. Navigate to the website 'https://www.jpost.com/'.
3. Locate and click on the "Notifications" bell icon.
4. Observe the loading process for the notifications list or panel.

### Expected Result:
A successful API response containing notifications data.

### Actual Result:
A CORS error is encountered, preventing the request from being processed.

**Comment by mbtools** [comment]
https://github.com/Open-Web-Analytics/Open-Web-Analytics/pull/603 but not merged
