### ISSUE TITLE
Fatal Error on Fresh Install - Uncaught Error: Class 'Monolog\Logger' not found

### ISSUE THREAD

**Issue by pmi123** [Open-Web-Analytics/Open-Web-Analytics#917]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting)

**Affected Version(s)**: 1.7.8

**PHP Version**: 7.4.3

**Webserver**: Apache 2.4.41

**Browser**: Chromium 125.0.6422.141, 

**Installation Type**

- [ ] Wordpress x.y.z
- [ ] Mediawiki x.y.z
- [X ] Standalone from 1.7.8.tar.gz

**Description**  
Installation fails at step 3 - Start the installation wizard by pointing your web browser at: http://yourdomain/path/to/owa/install.php. 

**Additional context**  
Apache error log:
[Tue Jun 11 08:42:48.243603 2024] [php7:error] [pid 781166] [client 73.221.222.250:44656] PHP Fatal error:  Uncaught Error: Class 'Monolog\\Logger' not found in /var/www/html/owa/modules/base/classes/error.php:68\nStack trace:\n#0 /var/www/html/owa/owa_lib.php(489): owa_error->__construct()\n#1 /var/www/html/owa/owa_coreAPI.php(487): owa_lib::factory()\n#2 /var/www/html/owa/owa_coreAPI.php(158): owa_coreAPI::supportClassFactory()\n#3 /var/www/html/owa/owa_base.php(77): owa_coreAPI::errorSingleton()\n#4 /var/www/html/owa/owa_caller.php(76): owa_base->__construct()\n#5 /var/www/html/owa/owa.php(24): owa_caller->__construct()\n#6 /var/www/html/owa/index.php(35): owa->__construct()\n#7 {main}\n  thrown in /var/www/html/owa/modules/base/classes/error.php on line 68

Update:
I added a info.php file to /var/html/www/owa directory, and it loads just fine. I have attached a pdf of the output.
[PHP 7.4.3-4ubuntu2.22 - phpinfo().pdf](https://github.com/user-attachments/files/15793148/PHP.7.4.3-4ubuntu2.22.-.phpinfo.pdf)

**Comment by pmi123** [comment]
Looks like the project is dead and the code is broken.

**Comment by padams** [comment]
Not dead just no one is commenting on your obvious issue. You didn’t run composer when you installed from source. See the wiki on how to install from source or use a packaged release tarball.

**Comment by pmi123** [comment]
Your installation instructions need help. Nowhere does it say anything about running composer.

> 2. Get the latest OWA release
> 
>     Install OWA by [Downloading](https://github.com/padams/Open-Web-Analytics/releases) the latest release package.
>     Decompress the release package file
>     Move the decompressed owa folder somewhere within the document root of your web server. The owa folder must be accessible by web browsers.

No worries, however. I uninstalled OWA and switched to Matomo. 10 minute installation and I was up and running.
